import type { Country, PyramidType } from './types';

/**
 * Additional 12 countries to reach 50 country target
 * Covering key regions: Asia, Latin America, Africa, Europe
 * PyramidTypes mapped: GROWTH_RISK, COMPETENCE_TRUST, STABILITY_REDIS, PROBLEM_RENT, HYBRID_TRANSITION, RESOURCE_EXTRACTION
 */
export const additionalCountries: Country[] = [
  {
    id: 'vietnam',
    name: 'Vietnam',
    nameLocal: 'Việt Nam',
    iso2: 'VN',
    region: 'Southeast Asia',
    pyramidType: 'GROWTH_RISK' as PyramidType,
    ruleOfGold: 'Move fast, stay visible, build relationships before business.',
    pyramid: {
      top: 'Communist Party leadership and state-connected businesses',
      institutions: 'Government apparatus supporting rapid industrialization',
      gatekeepers: 'Local officials, provincial leaders, connected entrepreneurs',
      valueCreators: 'Manufacturing workers, tech talent, small business owners',
      base: 'Rural farmers and informal workers',
      realAsset: 'Labor force and manufacturing capability',
    },
    risks: {
      legal: 55,
      safety: 35,
      corruption: 60,
      volatility: 45,
      bureaucracy: 65,
    },
    whoWins: [
      'Foreign investors in manufacturing',
      'Tech entrepreneurs with government ties',
      'Export-focused businesses',
      'Those who understand local culture',
    ],
    whoLoses: [
      'Those expecting Western transparency',
      'Slow-moving businesses',
      'Anyone ignoring relationship building',
      'Critics of the system',
    ],
    playbook: {
      do: [
        'Build relationships before proposing business',
        'Learn basic Vietnamese - huge advantage',
        'Start in Ho Chi Minh City or Hanoi',
        'Partner with local companies initially',
        'Be patient with bureaucracy',
      ],
      dont: [
        'Criticize political system publicly',
        'Rush into deals without due diligence',
        'Ignore face and hierarchy',
        'Assume contracts alone protect you',
        'Underestimate local competition',
      ],
      plan30Days: [
        'Get 3-month tourist visa',
        'Explore major cities',
        'Network with expat communities',
        'Understand cost of living firsthand',
      ],
      plan12Months: [
        'Secure work permit or business visa',
        'Establish local partnerships',
        'Learn conversational Vietnamese',
        'Build Vietnamese professional network',
      ],
      plan5Years: [
        'Consider long-term residence',
        'Expand business across Vietnam',
        'Deepen local integration',
        'Explore investment opportunities',
      ],
      planB: 'Thailand or Malaysia as alternatives with similar growth but different systems.',
    },
    snapshot: {
      gdpPerCapita: 4164,
      population: 99000000,
      passportRank: 89,
      corruptionIndex: 42,
      freedomIndex: 19,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 0,
      notes: 'New digital nomad visa launched. Work permit process improving.',
    },
    costOfLiving: {
      index: 32,
      rentIndex: 15,
      groceriesIndex: 28,
      monthlyBudgetSingle: 800,
      monthlyBudgetFamily: 1800,
    },
    qualityOfLife: {
      healthcareRank: 104,
      educationIndex: 0.62,
      safetyIndex: 78,
      environmentIndex: 42,
      workLifeBalance: 5,
      internetSpeed: 60,
    },
    lgbtqRights: {
      index: 45,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'safe',
      notes: 'No legal recognition but increasing social acceptance in cities.',
    },
    positivePoints: {
      lifestyle: ['Incredible street food', 'Low cost of living', 'Beautiful landscapes', 'Vibrant cities'],
      economy: ['Fast-growing economy', 'Manufacturing hub', 'Young workforce', 'Tech startup scene'],
      culture: ['Rich history', 'Warm hospitality', 'Coffee culture', 'Traditional crafts'],
      infrastructure: ['Improving roads', 'Modern airports', 'Fast internet', 'Ride-hailing apps'],
      opportunities: ['Tech sector boom', 'English teaching', 'Manufacturing', 'Tourism'],
      nature: ['Ha Long Bay', 'Mekong Delta', 'Beautiful beaches', 'Mountain regions'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'moderate',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'high',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Typhoons in central/northern regions. Flooding common. Hot and humid.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 55,
      accessScore: 60,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Good private hospitals in major cities. International clinics available.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'chile',
    name: 'Chile',
    nameLocal: 'Chile',
    iso2: 'CL',
    region: 'South America',
    pyramidType: 'COMPETENCE_TRUST' as PyramidType,
    ruleOfGold: 'Credentials matter, but the right network opens every door.',
    pyramid: {
      top: 'Economic elite (6 families control 90% of wealth)',
      institutions: 'Strong institutions but serving established interests',
      gatekeepers: 'University networks, business associations',
      valueCreators: 'Professionals, entrepreneurs, skilled workers',
      base: 'Middle class and informal workers',
      realAsset: 'The appearance of meritocracy while networks dominate',
    },
    risks: {
      legal: 35,
      safety: 45,
      corruption: 35,
      volatility: 40,
      bureaucracy: 45,
    },
    whoWins: [
      'Well-connected professionals',
      'Graduates from elite universities',
      'Those with right family background',
      'International investors',
    ],
    whoLoses: [
      'Self-made without credentials',
      'Those outside traditional networks',
      'Lower-middle class aspirants',
      'Rural populations',
    ],
    playbook: {
      do: [
        'Get credentials from recognized institutions',
        'Network through professional associations',
        'Learn Chilean Spanish nuances',
        'Start in Santiago',
        'Understand local business culture',
      ],
      dont: [
        'Rely only on merit without networking',
        'Ignore social codes and hierarchy',
        'Underestimate cost of living in Santiago',
        'Skip credential validation',
        'Expect quick integration',
      ],
      plan30Days: [
        'Explore Santiago and regions',
        'Contact professional associations',
        'Understand visa requirements',
        'Research credential recognition',
      ],
      plan12Months: [
        'Obtain work visa or residence',
        'Build professional network',
        'Validate foreign degrees if needed',
        'Establish bank accounts',
      ],
      plan5Years: [
        'Consider permanent residence',
        'Expand professional network',
        'Build local reputation',
        'Explore citizenship (5 years)',
      ],
      planB: 'Uruguay or Argentina as alternatives with different dynamics.',
    },
    snapshot: {
      gdpPerCapita: 15355,
      population: 19500000,
      passportRank: 14,
      corruptionIndex: 67,
      freedomIndex: 90,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'Start-Up Chile program famous. New nomad visa available.',
    },
    costOfLiving: {
      index: 48,
      rentIndex: 25,
      groceriesIndex: 42,
      monthlyBudgetSingle: 1200,
      monthlyBudgetFamily: 2800,
    },
    qualityOfLife: {
      healthcareRank: 44,
      educationIndex: 0.81,
      safetyIndex: 58,
      environmentIndex: 52,
      workLifeBalance: 6,
      internetSpeed: 150,
    },
    lgbtqRights: {
      index: 62,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Same-sex marriage legal since 2022. Progressive for Latin America.',
    },
    positivePoints: {
      lifestyle: ['Beautiful landscapes', 'Wine country', 'Outdoor activities', 'Safe cities'],
      economy: ['Most stable in region', 'Strong institutions', 'Mining industry', 'Growing tech'],
      culture: ['European influence', 'Literary tradition', 'Warm hospitality', 'Food culture'],
      infrastructure: ['Excellent roads', 'Modern airports', 'Fast internet', 'Reliable utilities'],
      opportunities: ['Start-Up Chile program', 'Mining sector', 'Renewable energy', 'Agriculture'],
      nature: ['Atacama Desert', 'Patagonia', 'Easter Island', 'Andes mountains'],
    },
    naturalRisks: {
      seismicRisk: 'very_high',
      tsunamiRisk: 'high',
      floodRisk: 'moderate',
      droughtRisk: 'high',
      cycloneRisk: 'none',
      volcanoRisk: 'high',
      extremeHeat: 'rare',
      extremeCold: 'occasional',
      climateNotes: 'Very high earthquake risk. Tsunami threat on coast. Active volcanoes.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 75,
      accessScore: 72,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'moderate',
      insuranceRequired: true,
      notes: 'Good private healthcare. FONASA public system exists. Insurance recommended.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'colombia',
    name: 'Colombia',
    nameLocal: 'Colombia',
    iso2: 'CO',
    region: 'South America',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Relationships are everything, but verify everyone.',
    pyramid: {
      top: 'Oligarchic families and major landowners',
      institutions: 'Improving but still captured by interests',
      gatekeepers: 'Political connections, regional power brokers',
      valueCreators: 'Growing middle class, entrepreneurs, workers',
      base: 'Informal workers and rural populations',
      realAsset: 'Natural resources and strategic position',
    },
    risks: {
      legal: 55,
      safety: 55,
      corruption: 60,
      volatility: 50,
      bureaucracy: 55,
    },
    whoWins: [
      'Connected entrepreneurs',
      'International businesses with local partners',
      'Those in growth sectors (tech, tourism)',
      'Patient long-term investors',
    ],
    whoLoses: [
      'Those ignoring security considerations',
      'Naive investors without local knowledge',
      'Anyone in wrong regions',
      'Critics of powerful interests',
    ],
    playbook: {
      do: [
        'Choose your city carefully (Bogota, Medellin, Cartagena)',
        'Build deep local relationships',
        'Understand regional differences',
        'Stay informed on security',
        'Work with reputable local partners',
      ],
      dont: [
        'Ignore security advice',
        'Flash wealth publicly',
        'Go to high-risk areas unprepared',
        'Rely on informal agreements',
        'Underestimate complexity',
      ],
      plan30Days: [
        'Get Colombia Digital Nomad Visa',
        'Explore Medellin and Bogota',
        'Join expat communities',
        'Understand neighborhood safety',
      ],
      plan12Months: [
        'Transition to longer-term visa',
        'Build local business network',
        'Learn Colombian Spanish',
        'Establish banking relationships',
      ],
      plan5Years: [
        'Consider permanent residence',
        'Expand business or investments',
        'Deep local integration',
        'Explore citizenship path (5 years)',
      ],
      planB: 'Ecuador or Peru as alternatives. Mexico for larger economy.',
    },
    snapshot: {
      gdpPerCapita: 6630,
      population: 52000000,
      passportRank: 40,
      corruptionIndex: 39,
      freedomIndex: 63,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'Popular digital nomad destination. Investment visa from $145K.',
    },
    costOfLiving: {
      index: 32,
      rentIndex: 14,
      groceriesIndex: 28,
      monthlyBudgetSingle: 1000,
      monthlyBudgetFamily: 2200,
    },
    qualityOfLife: {
      healthcareRank: 22,
      educationIndex: 0.69,
      safetyIndex: 45,
      environmentIndex: 48,
      workLifeBalance: 6,
      internetSpeed: 80,
    },
    lgbtqRights: {
      index: 58,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'caution',
      notes: 'Legal equality but social acceptance varies by region.',
    },
    positivePoints: {
      lifestyle: ['Year-round spring weather (Medellin)', 'Vibrant nightlife', 'Friendly people', 'Coffee culture'],
      economy: ['Growing tech hub', 'Tourism boom', 'Young workforce', 'Strategic location'],
      culture: ['Music and dance', 'Colonial architecture', 'Diverse regions', 'Creative industries'],
      infrastructure: ['Modern metro (Medellin)', 'Improving airports', 'Good internet', 'Coworking spaces'],
      opportunities: ['Digital nomad hub', 'Tech startups', 'Tourism', 'Real estate'],
      nature: ['Caribbean coast', 'Amazon access', 'Coffee region', 'Andes mountains'],
    },
    naturalRisks: {
      seismicRisk: 'high',
      tsunamiRisk: 'low',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'low',
      volcanoRisk: 'moderate',
      extremeHeat: 'occasional',
      extremeCold: 'rare',
      climateNotes: 'Earthquake and flood risks. Varied climate by altitude.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 78,
      accessScore: 70,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Excellent healthcare value. Medical tourism destination.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'south_korea',
    name: 'South Korea',
    nameLocal: '대한민국',
    iso2: 'KR',
    region: 'East Asia',
    pyramidType: 'COMPETENCE_TRUST' as PyramidType,
    ruleOfGold: 'Hierarchy is sacred. Success comes from within the system.',
    pyramid: {
      top: 'Chaebol families and political elite',
      institutions: 'Efficient but serving corporate interests',
      gatekeepers: 'University entrance, corporate HR, military connections',
      valueCreators: 'Salaryman class, tech workers, entrepreneurs',
      base: 'Service workers and precariat',
      realAsset: 'Access to chaebol ecosystem',
    },
    risks: {
      legal: 25,
      safety: 15,
      corruption: 35,
      volatility: 25,
      bureaucracy: 45,
    },
    whoWins: [
      'Top university graduates',
      'Those in chaebol companies',
      'Tech talent in right sectors',
      'International business executives',
    ],
    whoLoses: [
      'Non-Korean speakers',
      'Those outside hierarchy',
      'Older job seekers',
      'Non-conformists',
    ],
    playbook: {
      do: [
        'Learn Korean - essential for integration',
        'Understand hierarchical culture',
        'Work for established company first',
        'Network through alumni and industry groups',
        'Respect social codes',
      ],
      dont: [
        'Expect easy integration as outsider',
        'Challenge hierarchy publicly',
        'Ignore work culture expectations',
        'Underestimate language barrier',
        'Be impatient with bureaucracy',
      ],
      plan30Days: [
        'Explore Seoul and Busan',
        'Assess language requirements',
        'Research visa sponsorship options',
        'Connect with expat community',
      ],
      plan12Months: [
        'Secure work visa through employer',
        'Begin intensive Korean study',
        'Build professional network',
        'Understand cultural codes',
      ],
      plan5Years: [
        'Consider F-2 long-term visa',
        'Deep professional integration',
        'Fluent Korean as goal',
        'Explore F-5 permanent residence',
      ],
      planB: 'Japan for similar culture, Taiwan for more accessible integration.',
    },
    snapshot: {
      gdpPerCapita: 34758,
      population: 51700000,
      passportRank: 2,
      corruptionIndex: 63,
      freedomIndex: 83,
    },
    visa: {
      workVisa: 'difficult',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'Strict work visa requirements. New digital nomad visa (Workcation).',
    },
    costOfLiving: {
      index: 72,
      rentIndex: 35,
      groceriesIndex: 68,
      monthlyBudgetSingle: 1800,
      monthlyBudgetFamily: 4200,
    },
    qualityOfLife: {
      healthcareRank: 6,
      educationIndex: 0.93,
      safetyIndex: 85,
      environmentIndex: 45,
      workLifeBalance: 4,
      internetSpeed: 200,
    },
    lgbtqRights: {
      index: 35,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Conservative society. No legal recognition. Cities more tolerant.',
    },
    positivePoints: {
      lifestyle: ['K-culture hub', 'Amazing food', 'Ultra-modern cities', 'Four seasons'],
      economy: ['Tech powerhouse', 'World-class companies', 'Innovation leader', 'Export giant'],
      culture: ['K-pop and cinema', 'Rich history', 'Traditional crafts', 'Unique identity'],
      infrastructure: ['Best public transport', 'Fastest internet', 'Smart cities', 'Ultra-efficient'],
      opportunities: ['Tech sector', 'Teaching English', 'Trade', 'Entertainment'],
      nature: ['Beautiful mountains', 'Islands', 'Traditional villages', 'National parks'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'low',
      floodRisk: 'moderate',
      droughtRisk: 'moderate',
      cycloneRisk: 'moderate',
      volcanoRisk: 'none',
      extremeHeat: 'occasional',
      extremeCold: 'occasional',
      climateNotes: 'Monsoon season with heavy rains. Hot humid summers. Cold winters.',
    },
    healthcare: {
      systemType: 'universal',
      qualityScore: 92,
      accessScore: 95,
      emergencyResponse: 'excellent',
      specialistAccess: 'excellent',
      chronicCareQuality: 'excellent',
      costForExpats: 'low',
      insuranceRequired: false,
      notes: 'World-class affordable healthcare. National health insurance.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    nameLocal: 'Indonesia',
    iso2: 'ID',
    region: 'Southeast Asia',
    pyramidType: 'GROWTH_RISK' as PyramidType,
    ruleOfGold: 'Patience and relationships trump speed and contracts.',
    pyramid: {
      top: 'Political families and conglomerate owners',
      institutions: 'Growing but still influenced by connections',
      gatekeepers: 'Military, religious leaders, regional elites',
      valueCreators: 'Growing middle class, digital economy workers',
      base: 'Rural farmers and informal workers',
      realAsset: 'Market size and natural resources',
    },
    risks: {
      legal: 55,
      safety: 45,
      corruption: 60,
      volatility: 45,
      bureaucracy: 60,
    },
    whoWins: [
      'Long-term investors',
      'Those with local partners',
      'Digital economy entrepreneurs',
      'Those understanding Islamic culture',
    ],
    whoLoses: [
      'Impatient investors',
      'Those ignoring cultural codes',
      'Solo entrepreneurs without partners',
      'Those not understanding regions',
    ],
    playbook: {
      do: [
        'Embrace long-term perspective',
        'Build genuine relationships',
        'Understand regional diversity',
        'Partner with local entities',
        'Respect religious practices',
      ],
      dont: [
        'Rush business decisions',
        'Ignore Islamic calendar and practices',
        'Assume Jakarta = Indonesia',
        'Work without proper permits',
        'Disrespect local customs',
      ],
      plan30Days: [
        'Explore beyond Bali (Jakarta, Yogyakarta)',
        'Understand visa options',
        'Connect with business communities',
        'Research sector opportunities',
      ],
      plan12Months: [
        'Secure appropriate visa (KITAS)',
        'Establish local entity if needed',
        'Build Indonesian network',
        'Learn bahasa basics',
      ],
      plan5Years: [
        'Consider permanent residence (KITAP)',
        'Expand across regions',
        'Deep market integration',
        'Long-term investment strategy',
      ],
      planB: 'Malaysia for easier integration, Thailand for tourism focus.',
    },
    snapshot: {
      gdpPerCapita: 4798,
      population: 277000000,
      passportRank: 70,
      corruptionIndex: 38,
      freedomIndex: 59,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 0,
      notes: 'New Second Home Visa. Digital nomad visa popular in Bali.',
    },
    costOfLiving: {
      index: 35,
      rentIndex: 12,
      groceriesIndex: 32,
      monthlyBudgetSingle: 900,
      monthlyBudgetFamily: 2000,
    },
    qualityOfLife: {
      healthcareRank: 92,
      educationIndex: 0.62,
      safetyIndex: 55,
      environmentIndex: 40,
      workLifeBalance: 6,
      internetSpeed: 35,
    },
    lgbtqRights: {
      index: 22,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Conservative society. Varies by region. Bali more tolerant.',
    },
    positivePoints: {
      lifestyle: ['Tropical paradise', 'Low cost of living', 'Diverse cultures', 'Warm hospitality'],
      economy: ['Massive market size', 'Growing middle class', 'Digital economy boom', 'Resources'],
      culture: ['Incredible diversity', 'Ancient temples', 'Traditional arts', 'Unique islands'],
      infrastructure: ['Improving rapidly', 'New airports', 'Digital payments', 'Startup ecosystem'],
      opportunities: ['Digital economy', 'Tourism', 'E-commerce', 'Resources'],
      nature: ['Bali beaches', 'Komodo dragons', 'Raja Ampat diving', 'Volcanoes'],
    },
    naturalRisks: {
      seismicRisk: 'very_high',
      tsunamiRisk: 'high',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'low',
      volcanoRisk: 'high',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Ring of Fire location. Active volcanoes. Tsunami risk. Monsoons.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 50,
      accessScore: 45,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Good private hospitals in Jakarta and Bali. Insurance essential.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'greece',
    name: 'Greece',
    nameLocal: 'Ελλάδα',
    iso2: 'GR',
    region: 'Southern Europe',
    pyramidType: 'STABILITY_REDIS' as PyramidType,
    ruleOfGold: 'Family and connections open doors. Strangers wait.',
    pyramid: {
      top: 'Shipping families, political dynasties',
      institutions: 'EU-aligned but locally captured',
      gatekeepers: 'Extended family networks, political connections',
      valueCreators: 'Tourism, shipping, small businesses',
      base: 'Young unemployed, pensioners',
      realAsset: 'Who you know, not what you know',
    },
    risks: {
      legal: 40,
      safety: 30,
      corruption: 45,
      volatility: 40,
      bureaucracy: 70,
    },
    whoWins: [
      'Those with Greek connections',
      'Tourism investors',
      'EU citizens with mobility rights',
      'Patient long-term investors',
    ],
    whoLoses: [
      'Those expecting efficiency',
      'Outsiders without networks',
      'Young Greeks without connections',
      'Anyone fighting bureaucracy alone',
    ],
    playbook: {
      do: [
        'Build genuine relationships',
        'Learn some Greek - hugely appreciated',
        'Understand slow pace outside Athens',
        'Consider Golden Visa if investing',
        'Embrace Mediterranean lifestyle',
      ],
      dont: [
        'Expect Northern European efficiency',
        'Rush the relationship process',
        'Fight bureaucracy alone',
        'Ignore local customs and festivals',
        'Underestimate summer tourism peak',
      ],
      plan30Days: [
        'Explore Athens and islands',
        'Understand EU mobility rights if applicable',
        'Research Golden Visa if investing',
        'Connect with expat community',
      ],
      plan12Months: [
        'Secure residence permit or visa',
        'Open Greek bank account',
        'Build local network',
        'Understand tax implications (non-dom regime)',
      ],
      plan5Years: [
        'Consider permanent residence',
        'Deep integration into local community',
        'Property investment if desired',
        'Citizenship path (7 years)',
      ],
      planB: 'Portugal or Spain for similar lifestyle with different dynamics.',
    },
    snapshot: {
      gdpPerCapita: 20867,
      population: 10400000,
      passportRank: 8,
      corruptionIndex: 52,
      freedomIndex: 87,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 7,
      notes: 'Golden Visa from €250K investment. Digital nomad visa available.',
    },
    costOfLiving: {
      index: 55,
      rentIndex: 22,
      groceriesIndex: 52,
      monthlyBudgetSingle: 1200,
      monthlyBudgetFamily: 2800,
    },
    qualityOfLife: {
      healthcareRank: 29,
      educationIndex: 0.84,
      safetyIndex: 75,
      environmentIndex: 65,
      workLifeBalance: 7,
      internetSpeed: 60,
    },
    lgbtqRights: {
      index: 55,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Same-sex marriage legal since 2024. Athens very progressive.',
    },
    positivePoints: {
      lifestyle: ['Mediterranean climate', 'Incredible food', 'Island life', 'Slow pace'],
      economy: ['Tourism powerhouse', 'Shipping industry', 'EU membership', 'Growing tech'],
      culture: ['Ancient heritage', 'Warm hospitality', 'Family focus', 'Vibrant festivals'],
      infrastructure: ['Improving transport', 'Good airports', 'Ferry networks', 'Digital services'],
      opportunities: ['Tourism', 'Golden Visa', 'Remote work', 'Retirement'],
      nature: ['Beautiful islands', 'Mountain villages', 'Ancient sites', 'Crystal waters'],
    },
    naturalRisks: {
      seismicRisk: 'high',
      tsunamiRisk: 'moderate',
      floodRisk: 'moderate',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'low',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Earthquake prone. Hot dry summers. Wildfires increasing.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 70,
      accessScore: 65,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Public system strained. Private healthcare affordable and good.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'kenya',
    name: 'Kenya',
    nameLocal: 'Kenya',
    iso2: 'KE',
    region: 'East Africa',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Tribes and connections determine opportunity.',
    pyramid: {
      top: 'Political dynasties and major landowners',
      institutions: 'Functional but ethnically influenced',
      gatekeepers: 'Tribal networks, political connections',
      valueCreators: 'Tech innovators, entrepreneurs, farmers',
      base: 'Rural farmers and urban informal workers',
      realAsset: 'The right tribal and political connections',
    },
    risks: {
      legal: 55,
      safety: 55,
      corruption: 65,
      volatility: 50,
      bureaucracy: 55,
    },
    whoWins: [
      'Connected entrepreneurs',
      'Tech innovators (Silicon Savannah)',
      'Those with political access',
      'International NGO workers',
    ],
    whoLoses: [
      'Those outside tribal networks',
      'Small farmers without connections',
      'Transparent businesses without protection',
      'Those ignoring security',
    ],
    playbook: {
      do: [
        'Understand ethnic dynamics sensitively',
        'Network through professional associations',
        'Consider Nairobi tech ecosystem',
        'Work with established local partners',
        'Stay security aware',
      ],
      dont: [
        'Ignore ethnic sensitivities',
        'Display wealth publicly',
        'Go to high-risk areas unprepared',
        'Rely on informal agreements alone',
        'Underestimate local competition',
      ],
      plan30Days: [
        'Explore Nairobi and Mombasa',
        'Connect with tech/business community',
        'Understand visa requirements',
        'Assess security situation',
      ],
      plan12Months: [
        'Secure work or business permit',
        'Build local partnerships',
        'Learn Swahili basics',
        'Establish banking relationships',
      ],
      plan5Years: [
        'Consider long-term residence',
        'Expand business across East Africa',
        'Deep market integration',
        'Regional expansion to Uganda, Tanzania',
      ],
      planB: 'Rwanda for efficiency, Tanzania for different market.',
    },
    snapshot: {
      gdpPerCapita: 2081,
      population: 55000000,
      passportRank: 74,
      corruptionIndex: 31,
      freedomIndex: 52,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 7,
      notes: 'ETA required. Work permit through employer. Business visa for entrepreneurs.',
    },
    costOfLiving: {
      index: 38,
      rentIndex: 15,
      groceriesIndex: 35,
      monthlyBudgetSingle: 1100,
      monthlyBudgetFamily: 2500,
    },
    qualityOfLife: {
      healthcareRank: 115,
      educationIndex: 0.55,
      safetyIndex: 42,
      environmentIndex: 55,
      workLifeBalance: 5,
      internetSpeed: 25,
    },
    lgbtqRights: {
      index: 18,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Criminalized. Discretion essential. Urban areas slightly more tolerant.',
    },
    positivePoints: {
      lifestyle: ['Wildlife safaris', 'Indian Ocean beaches', 'Vibrant culture', 'English speaking'],
      economy: ['Silicon Savannah', 'M-Pesa revolution', 'Regional hub', 'Growing middle class'],
      culture: ['Maasai heritage', 'Swahili coast', 'Music scene', 'Diverse ethnicities'],
      infrastructure: ['Modern airports', 'Growing roads', 'Mobile money leader', 'Tech infrastructure'],
      opportunities: ['Tech startups', 'Tourism', 'Agriculture', 'Regional trade'],
      nature: ['Maasai Mara', 'Mount Kenya', 'Coastal beaches', 'Lake Nakuru'],
    },
    naturalRisks: {
      seismicRisk: 'moderate',
      tsunamiRisk: 'low',
      floodRisk: 'moderate',
      droughtRisk: 'high',
      cycloneRisk: 'low',
      volcanoRisk: 'low',
      extremeHeat: 'occasional',
      extremeCold: 'rare',
      climateNotes: 'Drought frequent in north. Flooding in rainy seasons.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 45,
      accessScore: 40,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Good private hospitals in Nairobi. Insurance essential.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'poland',
    name: 'Poland',
    nameLocal: 'Polska',
    iso2: 'PL',
    region: 'Central Europe',
    pyramidType: 'GROWTH_RISK' as PyramidType,
    ruleOfGold: 'Hard work pays off, but EU connections accelerate everything.',
    pyramid: {
      top: 'Political elite and EU-connected businesses',
      institutions: 'Strong but politically influenced',
      gatekeepers: 'EU networks, government connections',
      valueCreators: 'Growing tech sector, manufacturing, services',
      base: 'Traditional workers and rural populations',
      realAsset: 'EU membership and strategic position',
    },
    risks: {
      legal: 30,
      safety: 25,
      corruption: 35,
      volatility: 35,
      bureaucracy: 45,
    },
    whoWins: [
      'EU citizens with mobility',
      'Tech workers and startups',
      'Manufacturing investors',
      'Those learning Polish',
    ],
    whoLoses: [
      'Non-EU workers (visa challenges)',
      'Those not learning language',
      'Traditional businesses facing competition',
      'Social progressives in some contexts',
    ],
    playbook: {
      do: [
        'Learn Polish - huge advantage',
        'Leverage EU membership benefits',
        'Consider growing tech hubs',
        'Network through business associations',
        'Understand conservative social elements',
      ],
      dont: [
        'Ignore language barrier',
        'Underestimate bureaucracy',
        'Assume Western European norms',
        'Ignore regional differences',
        'Dismiss traditional values',
      ],
      plan30Days: [
        'Explore Warsaw, Krakow, Wroclaw',
        'Assess language requirements',
        'Connect with expat community',
        'Understand EU mobility rights',
      ],
      plan12Months: [
        'Register residence (EU) or secure visa',
        'Begin Polish language study',
        'Build professional network',
        'Establish banking/tax presence',
      ],
      plan5Years: [
        'Consider permanent residence',
        'Fluent Polish as goal',
        'Deep professional integration',
        'Citizenship possible (varies)',
      ],
      planB: 'Czech Republic or Estonia for different EU options.',
    },
    snapshot: {
      gdpPerCapita: 18688,
      population: 37800000,
      passportRank: 10,
      corruptionIndex: 55,
      freedomIndex: 81,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 3,
      notes: 'EU citizens have free movement. Non-EU need work permit through employer.',
    },
    costOfLiving: {
      index: 42,
      rentIndex: 22,
      groceriesIndex: 38,
      monthlyBudgetSingle: 1000,
      monthlyBudgetFamily: 2400,
    },
    qualityOfLife: {
      healthcareRank: 55,
      educationIndex: 0.87,
      safetyIndex: 80,
      environmentIndex: 52,
      workLifeBalance: 6,
      internetSpeed: 130,
    },
    lgbtqRights: {
      index: 32,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'No legal recognition. Varies by region - cities more tolerant.',
    },
    positivePoints: {
      lifestyle: ['Low cost of living', 'Four seasons', 'Rich history', 'Growing cities'],
      economy: ['EU growth leader', 'Strong manufacturing', 'Tech hub growing', 'Strategic location'],
      culture: ['Medieval cities', 'Catholic traditions', 'Cuisine', 'Arts scene'],
      infrastructure: ['Modern highways', 'Good airports', 'Fast internet', 'EU investment'],
      opportunities: ['Tech sector', 'Shared services', 'Manufacturing', 'EU market access'],
      nature: ['Tatra Mountains', 'Baltic coast', 'Forests', 'Lakes'],
    },
    naturalRisks: {
      seismicRisk: 'none',
      tsunamiRisk: 'none',
      floodRisk: 'moderate',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'none',
      extremeHeat: 'rare',
      extremeCold: 'occasional',
      climateNotes: 'Cold winters. Occasional flooding. Stable climate overall.',
    },
    healthcare: {
      systemType: 'universal',
      qualityScore: 65,
      accessScore: 60,
      emergencyResponse: 'good',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: false,
      notes: 'Public healthcare with long waits. Private affordable and faster.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'egypt',
    name: 'Egypt',
    nameLocal: 'مصر',
    iso2: 'EG',
    region: 'North Africa',
    pyramidType: 'PROBLEM_RENT' as PyramidType,
    ruleOfGold: 'The state controls. Navigate quietly or be controlled.',
    pyramid: {
      top: 'Military establishment and connected elites',
      institutions: 'State apparatus serving military interests',
      gatekeepers: 'Military-owned companies, security services',
      valueCreators: 'Private sector (allowed spaces), tourism workers',
      base: 'Vast population dependent on subsidies',
      realAsset: 'Access to state-controlled opportunities',
    },
    risks: {
      legal: 65,
      safety: 50,
      corruption: 65,
      volatility: 55,
      bureaucracy: 70,
    },
    whoWins: [
      'Those connected to military economy',
      'International businesses with permits',
      'Tourism operators with protection',
      'Those navigating informality well',
    ],
    whoLoses: [
      'Independent entrepreneurs',
      'Those competing with military businesses',
      'Anyone attracting wrong attention',
      'Young graduates without connections',
    ],
    playbook: {
      do: [
        'Work with established local partners',
        'Stay politically neutral publicly',
        'Understand military economic dominance',
        'Learn Egyptian Arabic basics',
        'Respect religious practices',
      ],
      dont: [
        'Compete with military businesses directly',
        'Engage in political commentary',
        'Ignore security situation',
        'Display wealth inappropriately',
        'Underestimate bureaucratic complexity',
      ],
      plan30Days: [
        'Explore Cairo and Alexandria',
        'Understand visa requirements',
        'Connect with business community',
        'Assess economic opportunities',
      ],
      plan12Months: [
        'Secure appropriate visa/permit',
        'Establish local partnerships',
        'Learn Arabic basics',
        'Understand business regulations',
      ],
      plan5Years: [
        'Consider long-term residence',
        'Expand within allowed sectors',
        'Deep relationship building',
        'Regional expansion to Gulf',
      ],
      planB: 'Morocco for more liberal environment, Jordan for similar region.',
    },
    snapshot: {
      gdpPerCapita: 3699,
      population: 104000000,
      passportRank: 96,
      corruptionIndex: 30,
      freedomIndex: 18,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 10,
      notes: 'Visa on arrival for many. Work permit through employer.',
    },
    costOfLiving: {
      index: 25,
      rentIndex: 8,
      groceriesIndex: 22,
      monthlyBudgetSingle: 600,
      monthlyBudgetFamily: 1400,
    },
    qualityOfLife: {
      healthcareRank: 100,
      educationIndex: 0.61,
      safetyIndex: 55,
      environmentIndex: 35,
      workLifeBalance: 5,
      internetSpeed: 35,
    },
    lgbtqRights: {
      index: 12,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Criminalized. Extreme discretion essential.',
    },
    positivePoints: {
      lifestyle: ['Ancient wonders', 'Nile River', 'Red Sea diving', 'Rich culture'],
      economy: ['Strategic location', 'Suez Canal', 'Large market', 'Tourism potential'],
      culture: ['Pharaonic heritage', 'Islamic architecture', 'Hospitality', 'Cuisine'],
      infrastructure: ['New capital being built', 'Improving roads', 'Growing metro', 'Airports'],
      opportunities: ['Tourism', 'Trade', 'Manufacturing', 'Agriculture'],
      nature: ['Pyramids', 'Red Sea coral', 'Nile Valley', 'Sinai desert'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'low',
      floodRisk: 'low',
      droughtRisk: 'high',
      cycloneRisk: 'none',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Very hot summers. Water scarcity main concern. Dust storms.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 48,
      accessScore: 45,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Private hospitals in Cairo good. Insurance essential.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'ireland',
    name: 'Ireland',
    nameLocal: 'Éire',
    iso2: 'IE',
    region: 'Western Europe',
    pyramidType: 'COMPETENCE_TRUST' as PyramidType,
    ruleOfGold: 'The old school tie matters. Outsiders can succeed but rarely enter inner circles.',
    pyramid: {
      top: 'Old families, political dynasties, Big Tech executives',
      institutions: 'Strong but serving established interests',
      gatekeepers: 'School networks, political connections, professional bodies',
      valueCreators: 'Tech workers, professionals, entrepreneurs',
      base: 'Housing-stressed workers, rural communities',
      realAsset: 'Access to right networks and institutions',
    },
    risks: {
      legal: 20,
      safety: 20,
      corruption: 25,
      volatility: 25,
      bureaucracy: 35,
    },
    whoWins: [
      'Tech workers (tax benefits)',
      'Multinationals (IFSC)',
      'EU citizens with skills',
      'Those connected to establishment',
    ],
    whoLoses: [
      'Those seeking affordable housing',
      'Non-EU without tech skills',
      'Outsiders trying to enter circles',
      'Small businesses competing with MNCs',
    ],
    playbook: {
      do: [
        'Leverage tech sector opportunities',
        'Network through professional associations',
        'Understand GAA and local culture',
        'Be patient with housing market',
        'Enjoy the craic (social culture)',
      ],
      dont: [
        'Expect easy housing',
        'Underestimate cost of living',
        'Ignore local customs',
        'Be too direct (Irish indirectness)',
        'Dismiss importance of local networks',
      ],
      plan30Days: [
        'Explore Dublin, Cork, Galway',
        'Understand housing situation',
        'Connect with professional community',
        'Research visa requirements',
      ],
      plan12Months: [
        'Secure employment or startup',
        'Register for PPS number',
        'Build professional network',
        'Navigate housing market',
      ],
      plan5Years: [
        'Apply for Irish Stamp 4',
        'Consider citizenship (5 years)',
        'Deep community integration',
        'Property purchase if possible',
      ],
      planB: 'UK post-Brexit, Netherlands for similar environment.',
    },
    snapshot: {
      gdpPerCapita: 103685,
      population: 5100000,
      passportRank: 4,
      corruptionIndex: 77,
      freedomIndex: 97,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'EU citizens free movement. Non-EU need employer sponsorship.',
    },
    costOfLiving: {
      index: 82,
      rentIndex: 48,
      groceriesIndex: 72,
      monthlyBudgetSingle: 2200,
      monthlyBudgetFamily: 5000,
    },
    qualityOfLife: {
      healthcareRank: 25,
      educationIndex: 0.93,
      safetyIndex: 82,
      environmentIndex: 72,
      workLifeBalance: 7,
      internetSpeed: 120,
    },
    lgbtqRights: {
      index: 78,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Same-sex marriage by referendum (2015). Very progressive.',
    },
    positivePoints: {
      lifestyle: ['Friendly culture', 'English speaking', 'Pub culture', 'Music scene'],
      economy: ['Tech hub of Europe', 'Low corporate tax', 'EU access', 'English speaking'],
      culture: ['Literary tradition', 'Celtic heritage', 'Warm hospitality', 'Festivals'],
      infrastructure: ['Good airports', 'Growing transport', 'Fast internet', 'Modern cities'],
      opportunities: ['Tech sector', 'Finance', 'Pharma', 'EU headquarters'],
      nature: ['Wild Atlantic Way', 'Green countryside', 'Cliffs of Moher', 'Historic sites'],
    },
    naturalRisks: {
      seismicRisk: 'none',
      tsunamiRisk: 'none',
      floodRisk: 'moderate',
      droughtRisk: 'low',
      cycloneRisk: 'none',
      volcanoRisk: 'none',
      extremeHeat: 'rare',
      extremeCold: 'rare',
      climateNotes: 'Mild but wet. Occasional flooding. Atlantic storms.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 78,
      accessScore: 65,
      emergencyResponse: 'good',
      specialistAccess: 'limited',
      chronicCareQuality: 'good',
      costForExpats: 'moderate',
      insuranceRequired: true,
      notes: 'Public system strained. Private insurance common and recommended.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'new_zealand',
    name: 'New Zealand',
    nameLocal: 'Aotearoa',
    iso2: 'NZ',
    region: 'Oceania',
    pyramidType: 'COMPETENCE_TRUST' as PyramidType,
    ruleOfGold: 'Skills matter, but the tall poppy gets cut. Stay humble.',
    pyramid: {
      top: 'Property owners, established businesses, political class',
      institutions: 'Strong and transparent but slow',
      gatekeepers: 'Professional bodies, immigration system, local networks',
      valueCreators: 'Skilled workers, entrepreneurs, exporters',
      base: 'Renters, young workers priced out',
      realAsset: 'Skills plus the right attitude',
    },
    risks: {
      legal: 15,
      safety: 15,
      corruption: 15,
      volatility: 25,
      bureaucracy: 35,
    },
    whoWins: [
      'Skilled migrants in demand sectors',
      'Entrepreneurs in export industries',
      'Property owners',
      'Those embracing Kiwi culture',
    ],
    whoLoses: [
      'Those showing off success (tall poppy)',
      'Priced out renters',
      'Those expecting fast processes',
      'Arrogant outsiders',
    ],
    playbook: {
      do: [
        'Embrace humble Kiwi culture',
        'Apply through skilled migrant pathway',
        'Be prepared for high costs',
        'Learn about Māori culture',
        'Network through industry associations',
      ],
      dont: [
        'Brag about achievements (tall poppy)',
        'Underestimate housing costs',
        'Ignore immigration complexity',
        'Dismiss local ways',
        'Expect fast decisions',
      ],
      plan30Days: [
        'Explore Auckland, Wellington, Queenstown',
        'Assess skill shortage lists',
        'Understand cost of living reality',
        'Connect with industry networks',
      ],
      plan12Months: [
        'Secure job offer or business',
        'Apply for appropriate visa',
        'Navigate housing market',
        'Build local network',
      ],
      plan5Years: [
        'Apply for residence',
        'Integrate into community',
        'Consider property purchase',
        'Citizenship after 5 years residence',
      ],
      planB: 'Australia for larger economy, Canada for similar immigration system.',
    },
    snapshot: {
      gdpPerCapita: 48802,
      population: 5100000,
      passportRank: 5,
      corruptionIndex: 87,
      freedomIndex: 99,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'Points-based skilled migrant system. Working holiday visas for many.',
    },
    costOfLiving: {
      index: 72,
      rentIndex: 38,
      groceriesIndex: 68,
      monthlyBudgetSingle: 2000,
      monthlyBudgetFamily: 4500,
    },
    qualityOfLife: {
      healthcareRank: 20,
      educationIndex: 0.92,
      safetyIndex: 88,
      environmentIndex: 85,
      workLifeBalance: 8,
      internetSpeed: 140,
    },
    lgbtqRights: {
      index: 85,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Very progressive. Marriage equality since 2013.',
    },
    positivePoints: {
      lifestyle: ['Work-life balance', 'Outdoor culture', 'Safe environment', 'Clean air'],
      economy: ['Stable economy', 'Tourism', 'Agriculture', 'Growing tech'],
      culture: ['Māori heritage', 'Friendly people', 'Rugby culture', 'Arts scene'],
      infrastructure: ['Good roads', 'Modern airports', 'Clean energy', 'Fast internet'],
      opportunities: ['Tech sector', 'Agriculture', 'Tourism', 'Film industry'],
      nature: ['Stunning landscapes', 'Adventure sports', 'National parks', 'Clean beaches'],
    },
    naturalRisks: {
      seismicRisk: 'high',
      tsunamiRisk: 'moderate',
      floodRisk: 'moderate',
      droughtRisk: 'moderate',
      cycloneRisk: 'low',
      volcanoRisk: 'moderate',
      extremeHeat: 'rare',
      extremeCold: 'rare',
      climateNotes: 'Earthquake risk (Wellington especially). Volcanic activity North Island.',
    },
    healthcare: {
      systemType: 'universal',
      qualityScore: 82,
      accessScore: 75,
      emergencyResponse: 'good',
      specialistAccess: 'limited',
      chronicCareQuality: 'good',
      costForExpats: 'low',
      insuranceRequired: false,
      notes: 'Public healthcare for residents. Private options available.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'malaysia',
    name: 'Malaysia',
    nameLocal: 'Malaysia',
    iso2: 'MY',
    region: 'Southeast Asia',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Understand the racial hierarchy. Play the long game.',
    pyramid: {
      top: 'Political elite (UMNO legacy), royal families, connected businessmen',
      institutions: 'Functional but ethnically structured',
      gatekeepers: 'Bumiputera policies, political connections, religious authorities',
      valueCreators: 'Chinese business community, skilled professionals, entrepreneurs',
      base: 'Migrant workers, rural populations',
      realAsset: 'Understanding and navigating ethnic dynamics',
    },
    risks: {
      legal: 40,
      safety: 35,
      corruption: 50,
      volatility: 35,
      bureaucracy: 50,
    },
    whoWins: [
      'Those understanding local dynamics',
      'Long-term investors',
      'Regional headquarters seekers',
      'Retirees (MM2H program)',
    ],
    whoLoses: [
      'Those ignoring ethnic complexity',
      'Businesses competing in protected sectors',
      'Short-term thinkers',
      'LGBTQ+ individuals',
    ],
    playbook: {
      do: [
        'Understand Bumiputera policies',
        'Consider MM2H or similar programs',
        'Network across ethnic communities',
        'Respect Islamic practices',
        'Use as regional hub',
      ],
      dont: [
        'Ignore ethnic sensitivities',
        'Criticize religious or royal institutions',
        'Underestimate bureaucracy',
        'Expect equal treatment in all sectors',
        'Be openly LGBTQ+',
      ],
      plan30Days: [
        'Explore KL, Penang, Langkawi',
        'Understand visa options (MM2H)',
        'Connect with expat community',
        'Research business environment',
      ],
      plan12Months: [
        'Secure appropriate visa/permit',
        'Establish local presence',
        'Build multi-ethnic network',
        'Learn Malay basics',
      ],
      plan5Years: [
        'Consider MM2H or work permit renewal',
        'Expand business across Malaysia',
        'Deep integration',
        'Use as ASEAN gateway',
      ],
      planB: 'Singapore for efficiency, Thailand for tourism.',
    },
    snapshot: {
      gdpPerCapita: 12570,
      population: 33000000,
      passportRank: 13,
      corruptionIndex: 50,
      freedomIndex: 50,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 0,
      notes: 'MM2H program for long-term stay. DE Rantau for digital nomads.',
    },
    costOfLiving: {
      index: 38,
      rentIndex: 15,
      groceriesIndex: 35,
      monthlyBudgetSingle: 1000,
      monthlyBudgetFamily: 2300,
    },
    qualityOfLife: {
      healthcareRank: 34,
      educationIndex: 0.72,
      safetyIndex: 62,
      environmentIndex: 48,
      workLifeBalance: 6,
      internetSpeed: 100,
    },
    lgbtqRights: {
      index: 18,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Criminalized. Extreme discretion essential, especially for Muslims.',
    },
    positivePoints: {
      lifestyle: ['Low cost of living', 'Food paradise', 'Tropical climate', 'English widely spoken'],
      economy: ['Growing middle class', 'Regional hub', 'Diverse economy', 'ASEAN member'],
      culture: ['Multicultural society', 'Rich heritage', 'Diverse cuisine', 'Festivals'],
      infrastructure: ['Modern cities', 'Good roads', 'Fast internet', 'Efficient airports'],
      opportunities: ['Tech sector', 'Manufacturing', 'Tourism', 'Regional hub'],
      nature: ['Beaches', 'Rainforests', 'Islands', 'Highlands'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'low',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Monsoon flooding common. Hot and humid year-round.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 75,
      accessScore: 72,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Excellent private healthcare at low cost. Medical tourism destination.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Numbeo'],
  },
  {
    id: 'spain',
    name: 'Spain',
    nameLocal: 'España',
    iso2: 'ES',
    region: 'Southern Europe',
    pyramidType: 'STABILITY_REDIS' as PyramidType,
    ruleOfGold: 'Quality of life first. The system protects work-life balance over pure growth.',
    pyramid: {
      top: 'State institutions and regional autonomies',
      institutions: 'Social welfare system and labor protections',
      gatekeepers: 'Diplomas, regional connections, language proficiency',
      valueCreators: 'Workers, entrepreneurs, tourism sector',
      base: 'Citizens benefiting from strong social protections',
      realAsset: 'Quality of life and social stability',
    },
    risks: {
      legal: 22,
      safety: 20,
      corruption: 40,
      volatility: 35,
      bureaucracy: 65,
    },
    whoWins: [
      'Those who value lifestyle over pure earnings',
      'Remote workers with foreign income',
      'Entrepreneurs in tourism and hospitality',
      'Those who master the bureaucratic system',
    ],
    whoLoses: [
      'High-ambition salary seekers',
      'Impatient entrepreneurs',
      'Those without Spanish/Catalan language skills',
      'Young job seekers in saturated markets',
    ],
    playbook: {
      do: [
        'Learn Spanish and regional language if applicable',
        'Build local network before formal opportunities',
        'Leverage siesta culture for work-life balance',
        'Explore regional differences (Catalonia, Basque, Andalusia)',
        'Consider digital nomad or non-lucrative visa',
      ],
      dont: [
        'Expect German-level efficiency',
        'Ignore regional identities and languages',
        'Rush bureaucratic processes',
        'Underestimate importance of personal relationships',
        'Expect high salaries outside tech/finance',
      ],
      plan30Days: [
        'Research visa options (NLV, digital nomad, Golden Visa)',
        'Explore target regions (Madrid, Barcelona, Valencia, Malaga)',
        'Connect with expat communities',
        'Understand healthcare system (NIE, empadronamiento)',
      ],
      plan12Months: [
        'Secure appropriate visa/residency',
        'Complete NIE and empadronamiento',
        'Build Spanish language proficiency (B2 minimum)',
        'Establish local professional network',
      ],
      plan5Years: [
        'Apply for permanent residency',
        'Consider citizenship path (10 years, 2 for Latin Americans)',
        'Integrate into local community',
        'Build Spain-based business or career',
      ],
      planB: 'Portugal for similar lifestyle with easier bureaucracy. Italy for EU alternative. France for higher salaries.',
    },
    snapshot: {
      gdpPerCapita: 32110,
      population: 47500000,
      passportRank: 3,
      corruptionIndex: 60,
      freedomIndex: 90,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      investmentMinimum: 500000,
      citizenshipYears: 10,
      notes: 'Digital Nomad Visa since 2023. Non-Lucrative Visa popular. Golden Visa for investors. Faster citizenship for Latin Americans (2 years).',
    },
    costOfLiving: {
      index: 58,
      rentIndex: 35,
      groceriesIndex: 52,
      monthlyBudgetSingle: 1600,
      monthlyBudgetFamily: 3500,
    },
    qualityOfLife: {
      healthcareRank: 8,
      educationIndex: 0.80,
      safetyIndex: 68,
      environmentIndex: 72,
      workLifeBalance: 9,
      internetSpeed: 180,
    },
    lgbtqRights: {
      index: 90,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'One of the most LGBTQ+ friendly countries in the world. Same-sex marriage since 2005. Strong legal protections.',
    },
    positivePoints: {
      lifestyle: ['Exceptional work-life balance', 'Mediterranean climate', 'World-renowned cuisine', 'Vibrant social life', 'Siesta culture'],
      economy: ['Strong tourism sector', 'Growing tech hub (Barcelona, Madrid)', 'EU market access', 'Digital nomad-friendly'],
      culture: ['Rich history (Moorish, Roman heritage)', 'Flamenco, art, and architecture', 'Diverse regional cultures', 'Festivals year-round (La Tomatina, Las Fallas, Semana Santa)'],
      infrastructure: ['High-speed AVE trains', 'Modern airports', 'Excellent public healthcare', 'Good fiber internet coverage'],
      opportunities: ['Remote work paradise', 'Tourism and hospitality', 'Tech sector growth', 'Real estate investment'],
      nature: ['Beautiful beaches (Costa Brava, Costa del Sol)', 'Pyrenees and Sierra Nevada mountains', 'Balearic and Canary Islands', 'Diverse landscapes'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'low',
      floodRisk: 'moderate',
      droughtRisk: 'high',
      cycloneRisk: 'none',
      volcanoRisk: 'low',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Mediterranean climate with hot, dry summers. Increasing drought and heat waves due to climate change. Occasional flooding in Valencia region.',
    },
    healthcare: {
      systemType: 'universal',
      qualityScore: 88,
      accessScore: 85,
      emergencyResponse: 'excellent',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'low',
      insuranceRequired: false,
      notes: 'Excellent public healthcare system (SNS). Private insurance affordable and recommended for faster access. Residents have full coverage.',
    },
    lastUpdated: '2024-12-20',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
];
