import { Country } from './types';

export const countries: Country[] = [
  {
    id: 'cameroon',
    name: 'Cameroon',
    nameLocal: 'Cameroun',
    iso2: 'CM',
    region: 'Central Africa',
    pyramidType: 'PROBLEM_RENT',
    ruleOfGold: 'Never solve a visible problem. Never become indispensable. Never centralize.',
    pyramid: {
      top: 'Political elites and connected networks',
      institutions: 'State apparatus serving private interests',
      gatekeepers: 'Bureaucrats, middlemen, and informal brokers',
      valueCreators: 'Entrepreneurs, farmers, and informal workers',
      base: 'General population financing the system',
      realAsset: 'The problem itself — dysfunction is profitable',
    },
    risks: {
      legal: 75,
      safety: 65,
      corruption: 85,
      volatility: 60,
      bureaucracy: 80,
    },
    whoWins: [
      'Connected insiders with political access',
      'Gatekeepers who control bottlenecks',
      'Those who monetize dysfunction',
      'International actors extracting resources',
    ],
    whoLoses: [
      'Competent people without connections',
      'Transparent entrepreneurs',
      'Anyone who solves problems publicly',
      'The young and ambitious without networks',
    ],
    playbook: {
      do: [
        'Stay invisible, build quietly',
        'Diversify income streams',
        'Build exportable skills',
        'Create offshore options progressively',
        'Network with diaspora',
      ],
      dont: [
        'Publicly solve systemic problems',
        'Become visibly successful without protection',
        'Centralize assets or power',
        'Trust formal institutions blindly',
        'Moralize or criticize openly',
      ],
      plan30Days: [
        'Secure documents and identity papers',
        'Start emergency fund (even small)',
        'Identify one exportable skill to develop',
        'Map your current network value',
      ],
      plan12Months: [
        'Develop secondary income source',
        'Build international connections',
        'Learn remote-work skills',
        'Create first offshore account if possible',
      ],
      plan5Years: [
        'Establish residence option abroad',
        'Diversify assets geographically',
        'Build reputation in international network',
        'Create passive income streams',
      ],
      planB: 'Focus on French-speaking destinations with easier visa access (Morocco, Senegal, France, Canada-Quebec). Build digital skills for remote work.',
    },
    snapshot: {
      gdpPerCapita: 1660,
      population: 28000000,
      passportRank: 91,
      corruptionIndex: 26,
      freedomIndex: 25,
    },
    visa: {
      workVisa: 'difficult',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 5,
      notes: 'Limited formal visa programs; informal connections often required',
    },
    costOfLiving: {
      index: 28,
      rentIndex: 12,
      groceriesIndex: 32,
      monthlyBudgetSingle: 450,
      monthlyBudgetFamily: 1200,
    },
    qualityOfLife: {
      healthcareRank: 142,
      educationIndex: 0.52,
      safetyIndex: 42,
      environmentIndex: 48,
      workLifeBalance: 5,
      internetSpeed: 12,
    },
    lgbtqRights: {
      index: 25,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexuality criminalized; significant social stigma',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'france',
    name: 'France',
    nameLocal: 'France',
    iso2: 'FR',
    region: 'Western Europe',
    pyramidType: 'STABILITY_REDIS',
    ruleOfGold: 'The system protects stability, not explosion. Play the long game within the rules.',
    pyramid: {
      top: 'State institutions and social model',
      institutions: 'Heavy bureaucracy ensuring redistribution',
      gatekeepers: 'Diplomas, certifications, and procedures',
      valueCreators: 'Workers, entrepreneurs (constrained)',
      base: 'Taxpayers funding the social contract',
      realAsset: 'Stability and predictability',
    },
    risks: {
      legal: 20,
      safety: 25,
      corruption: 30,
      volatility: 25,
      bureaucracy: 75,
    },
    whoWins: [
      'Those who master the system rules',
      'Public sector employees',
      'Those with right diplomas and networks',
      'Patient long-term planners',
    ],
    whoLoses: [
      'High ambition, low patience profiles',
      'Outsiders without French credentials',
      'Those seeking explosive growth',
      'Non-conformists and innovators',
    ],
    playbook: {
      do: [
        'Understand and use the system',
        'Optimize tax structure legally',
        'Build multiple income streams',
        'Develop international options',
        'Invest in quality of life',
      ],
      dont: [
        'Depend on single income source',
        'Ignore administrative requirements',
        'Expect meritocracy alone to win',
        'Burn bridges with institutions',
        'Underestimate bureaucracy time',
      ],
      plan30Days: [
        'Audit your current situation',
        'Understand your tax bracket',
        'Start automation savings',
        'Research side income options',
      ],
      plan12Months: [
        'Establish secondary revenue',
        'Optimize your legal structure',
        'Build transferable certifications',
        'Create international portfolio',
      ],
      plan5Years: [
        'Geographic diversification',
        'Build location-independent income',
        'Establish EU alternatives',
        'Create wealth outside system reach',
      ],
      planB: 'EU mobility is your advantage. Consider Portugal, Spain, or Netherlands for lower friction. Switzerland for higher ambition. Keep French benefits while building elsewhere.',
    },
    snapshot: {
      gdpPerCapita: 44850,
      population: 68000000,
      passportRank: 4,
      corruptionIndex: 71,
      freedomIndex: 89,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 300000,
      citizenshipYears: 5,
      notes: 'Talent Passport visa for skilled workers; EU citizens have free movement',
    },
    costOfLiving: {
      index: 74,
      rentIndex: 38,
      groceriesIndex: 78,
      monthlyBudgetSingle: 2200,
      monthlyBudgetFamily: 4500,
    },
    qualityOfLife: {
      healthcareRank: 14,
      educationIndex: 0.81,
      safetyIndex: 52,
      environmentIndex: 78,
      workLifeBalance: 8,
      internetSpeed: 185,
    },
    lgbtqRights: {
      index: 85,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Full legal equality; marriage since 2013',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    nameLocal: 'Schweiz / Suisse',
    iso2: 'CH',
    region: 'Western Europe',
    pyramidType: 'COMPETENCE_TRUST',
    ruleOfGold: 'Excellence + rules + reputation = security. No shortcuts, no approximations.',
    pyramid: {
      top: 'Trust, precision, and institutional reliability',
      institutions: 'Efficient, rule-based governance',
      gatekeepers: 'Quality standards and professional requirements',
      valueCreators: 'Highly skilled workers and entrepreneurs',
      base: 'Citizens invested in maintaining the system',
      realAsset: 'Competence and collective trust',
    },
    risks: {
      legal: 10,
      safety: 5,
      corruption: 15,
      volatility: 10,
      bureaucracy: 40,
    },
    whoWins: [
      'Highly competent specialists',
      'Rule-followers with excellence',
      'Long-term reputation builders',
      'Those who value precision',
    ],
    whoLoses: [
      'Approximators and shortcuts-takers',
      'Impatient disruptors',
      'Those without recognized credentials',
      'Cultural outsiders unwilling to adapt',
    ],
    playbook: {
      do: [
        'Master your craft to excellence',
        'Follow rules precisely',
        'Build reputation over time',
        'Integrate culturally',
        'Invest in certifications',
      ],
      dont: [
        'Take shortcuts ever',
        'Cheat or bend rules',
        'Oversell or exaggerate',
        'Ignore local norms',
        'Rush integration process',
      ],
      plan30Days: [
        'Research credential recognition',
        'Understand local professional standards',
        'Start language learning seriously',
        'Map integration requirements',
      ],
      plan12Months: [
        'Achieve required certifications',
        'Build professional network locally',
        'Demonstrate consistent performance',
        'Establish financial stability',
      ],
      plan5Years: [
        'Achieve permanent residence/citizenship',
        'Become reference in your field',
        'Build long-term wealth',
        'Integrate fully while keeping options',
      ],
      planB: 'Other COMPETENCE_TRUST systems: Germany, Netherlands, Austria, Singapore. Build credentials that transfer across these systems.',
    },
    snapshot: {
      gdpPerCapita: 93260,
      population: 8800000,
      passportRank: 2,
      corruptionIndex: 82,
      freedomIndex: 96,
    },
    visa: {
      workVisa: 'difficult',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 10,
      notes: 'Very restrictive; quota system for non-EU citizens; high skill requirements',
    },
    costOfLiving: {
      index: 122,
      rentIndex: 62,
      groceriesIndex: 118,
      monthlyBudgetSingle: 4200,
      monthlyBudgetFamily: 8500,
    },
    qualityOfLife: {
      healthcareRank: 5,
      educationIndex: 0.90,
      safetyIndex: 79,
      environmentIndex: 86,
      workLifeBalance: 7,
      internetSpeed: 220,
    },
    lgbtqRights: {
      index: 72,
      sameSecMarriage: false,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Registered partnerships; strong legal protections',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'usa',
    name: 'United States',
    nameLocal: 'United States',
    iso2: 'US',
    region: 'North America',
    pyramidType: 'GROWTH_RISK',
    ruleOfGold: 'Win fast, secure gains, diversify. The system rewards velocity, not stability.',
    pyramid: {
      top: 'Capital and growth potential',
      institutions: 'Markets and opportunity structures',
      gatekeepers: 'Access to capital and networks',
      valueCreators: 'Entrepreneurs and high performers',
      base: 'Workers in competitive environment',
      realAsset: 'Growth and scalability',
    },
    risks: {
      legal: 25,
      safety: 35,
      corruption: 33,
      volatility: 45,
      bureaucracy: 35,
    },
    whoWins: [
      'High-velocity entrepreneurs',
      'Those with capital access',
      'Scalable skill owners',
      'Network builders',
    ],
    whoLoses: [
      'Stability-seekers',
      'Those relying on social safety net',
      'Slow-and-steady types',
      'Those without health/wealth buffer',
    ],
    playbook: {
      do: [
        'Move fast and scale',
        'Build multiple income streams',
        'Secure private safety nets',
        'Network aggressively',
        'Diversify geographically',
      ],
      dont: [
        'Rely on social systems',
        'Stay in one income stream',
        'Ignore health insurance',
        'Burn out without exit plan',
        'Assume stability exists',
      ],
      plan30Days: [
        'Secure health coverage',
        'Start emergency fund',
        'Identify growth opportunities',
        'Map your network value',
      ],
      plan12Months: [
        'Build scalable income',
        'Create investment strategy',
        'Establish professional reputation',
        'Build safety buffers',
      ],
      plan5Years: [
        'Achieve financial independence',
        'Diversify internationally',
        'Build passive income',
        'Create exit options',
      ],
      planB: 'Consider Canada for stability with growth, Portugal for EU access, Dubai for tax optimization. Keep US income while building options.',
    },
    snapshot: {
      gdpPerCapita: 76330,
      population: 335000000,
      passportRank: 8,
      corruptionIndex: 69,
      freedomIndex: 83,
    },
    visa: {
      workVisa: 'difficult',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 800000,
      citizenshipYears: 5,
      notes: 'H1B lottery system; EB-5 investor visa; highly competitive',
    },
    costOfLiving: {
      index: 72,
      rentIndex: 48,
      groceriesIndex: 75,
      monthlyBudgetSingle: 2800,
      monthlyBudgetFamily: 5800,
    },
    qualityOfLife: {
      healthcareRank: 37,
      educationIndex: 0.90,
      safetyIndex: 51,
      environmentIndex: 62,
      workLifeBalance: 5,
      internetSpeed: 195,
    },
    lgbtqRights: {
      index: 75,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Marriage legal nationwide since 2015; varies by state',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'germany',
    name: 'Germany',
    nameLocal: 'Deutschland',
    iso2: 'DE',
    region: 'Western Europe',
    pyramidType: 'COMPETENCE_TRUST',
    ruleOfGold: 'Precision, process, and patience. The system rewards those who master the rules.',
    pyramid: {
      top: 'Industrial excellence and institutional trust',
      institutions: 'Efficient bureaucracy and strong unions',
      gatekeepers: 'Professional qualifications and certifications',
      valueCreators: 'Engineers, skilled workers, Mittelstand entrepreneurs',
      base: 'Taxpayers supporting the social market economy',
      realAsset: 'Technical competence and reliability',
    },
    risks: {
      legal: 15,
      safety: 15,
      corruption: 20,
      volatility: 20,
      bureaucracy: 65,
    },
    whoWins: [
      'Technical specialists and engineers',
      'Those with recognized qualifications',
      'Patient long-term builders',
      'Mittelstand entrepreneurs',
    ],
    whoLoses: [
      'Those seeking quick wins',
      'Outsiders without German credentials',
      'Impatient disruptors',
      'Those who resist bureaucracy',
    ],
    playbook: {
      do: [
        'Get your qualifications recognized',
        'Learn German seriously',
        'Build professional network methodically',
        'Embrace process and procedure',
        'Think long-term stability',
      ],
      dont: [
        'Rush or cut corners',
        'Ignore paperwork requirements',
        'Underestimate language importance',
        'Expect American-style flexibility',
        'Dismiss union and worker rights',
      ],
      plan30Days: [
        'Start intensive German language course',
        'Research credential recognition process',
        'Register with relevant authorities',
        'Understand tax and social system',
      ],
      plan12Months: [
        'Achieve B2 German level minimum',
        'Complete credential recognition',
        'Build professional network',
        'Establish stable employment',
      ],
      plan5Years: [
        'Qualify for permanent residence',
        'Build expertise reputation',
        'Consider homeownership',
        'Integrate into local community',
      ],
      planB: 'Other COMPETENCE_TRUST options: Austria, Netherlands, Switzerland. Your German qualifications transfer well within DACH region.',
    },
    snapshot: {
      gdpPerCapita: 51380,
      population: 84000000,
      passportRank: 3,
      corruptionIndex: 79,
      freedomIndex: 94,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 8,
      notes: 'Blue Card for skilled workers; Opportunity Card (2024); startup visa available',
    },
    costOfLiving: {
      index: 65,
      rentIndex: 32,
      groceriesIndex: 58,
      monthlyBudgetSingle: 1800,
      monthlyBudgetFamily: 3800,
    },
    qualityOfLife: {
      healthcareRank: 12,
      educationIndex: 0.94,
      safetyIndex: 65,
      environmentIndex: 77,
      workLifeBalance: 8,
      internetSpeed: 135,
    },
    lgbtqRights: {
      index: 90,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Marriage since 2017; one of most LGBTQ+ friendly countries',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'canada',
    name: 'Canada',
    nameLocal: 'Canada',
    iso2: 'CA',
    region: 'North America',
    pyramidType: 'STABILITY_REDIS',
    ruleOfGold: 'Moderate ambition, strong safety net. The system rewards patience over speed.',
    pyramid: {
      top: 'Social stability and multicultural harmony',
      institutions: 'Government services and public sector',
      gatekeepers: 'Immigration points system and credentials',
      valueCreators: 'Skilled immigrants and established professionals',
      base: 'Taxpayers funding healthcare and services',
      realAsset: 'Stability and quality of life',
    },
    risks: {
      legal: 15,
      safety: 20,
      corruption: 25,
      volatility: 25,
      bureaucracy: 55,
    },
    whoWins: [
      'Skilled immigrants with points',
      'Those seeking stability over speed',
      'Professionals in healthcare, tech, trades',
      'Families prioritizing quality of life',
    ],
    whoLoses: [
      'Those seeking explosive wealth',
      'Impatient entrepreneurs',
      'Those with non-recognized credentials',
      'Those needing warm climate',
    ],
    playbook: {
      do: [
        'Maximize Express Entry points',
        'Get credentials assessed early',
        'Build Canadian work experience',
        'Network in your professional community',
        'Embrace multicultural integration',
      ],
      dont: [
        'Expect US-level salaries',
        'Underestimate housing costs',
        'Ignore credential recognition',
        'Skip language testing',
        'Assume quick wealth building',
      ],
      plan30Days: [
        'Complete language tests (IELTS/TEF)',
        'Start credential assessment (WES)',
        'Research Provincial Nominee Programs',
        'Calculate Express Entry points',
      ],
      plan12Months: [
        'Obtain PR or work permit',
        'Establish Canadian work history',
        'Build credit and banking history',
        'Network professionally',
      ],
      plan5Years: [
        'Apply for citizenship',
        'Build investment portfolio',
        'Consider real estate',
        'Establish professional reputation',
      ],
      planB: 'If Canada is too slow, consider Australia (similar system, warmer), or US if you have entrepreneurial drive. Keep Canadian PR as safety net.',
    },
    snapshot: {
      gdpPerCapita: 52720,
      population: 40000000,
      passportRank: 7,
      corruptionIndex: 74,
      freedomIndex: 98,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 200000,
      citizenshipYears: 3,
      notes: 'Express Entry points-based system; Provincial Nominee Programs; Start-up Visa',
    },
    costOfLiving: {
      index: 69,
      rentIndex: 42,
      groceriesIndex: 72,
      monthlyBudgetSingle: 2400,
      monthlyBudgetFamily: 5000,
    },
    qualityOfLife: {
      healthcareRank: 26,
      educationIndex: 0.89,
      safetyIndex: 60,
      environmentIndex: 72,
      workLifeBalance: 7,
      internetSpeed: 175,
    },
    lgbtqRights: {
      index: 95,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Marriage since 2005; among world leaders in LGBTQ+ rights',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'uae',
    name: 'United Arab Emirates',
    nameLocal: 'الإمارات العربية المتحدة',
    iso2: 'AE',
    region: 'Middle East',
    pyramidType: 'GROWTH_RISK',
    ruleOfGold: 'Produce value, stay visible, stay useful. You exist as long as you contribute.',
    pyramid: {
      top: 'Ruling families and sovereign wealth',
      institutions: 'Business-friendly free zones',
      gatekeepers: 'Visa sponsors and business connections',
      valueCreators: 'Entrepreneurs, executives, skilled expats',
      base: 'Labor force on temporary contracts',
      realAsset: 'Capital attraction and tax efficiency',
    },
    risks: {
      legal: 40,
      safety: 15,
      corruption: 35,
      volatility: 30,
      bureaucracy: 45,
    },
    whoWins: [
      'High-earning professionals',
      'Entrepreneurs with capital',
      'Tax optimizers',
      'Network builders in business',
    ],
    whoLoses: [
      'Low-income workers',
      'Those seeking permanent roots',
      'Cultural non-conformists',
      'Those dependent on legal protections',
    ],
    playbook: {
      do: [
        'Maximize income during stay',
        'Build regional network',
        'Save aggressively tax-free',
        'Create exit strategy early',
        'Maintain home country ties',
      ],
      dont: [
        'Expect permanent residence easily',
        'Ignore cultural norms',
        'Get into legal disputes',
        'Burn bridges with sponsors',
        'Assume rights work like home',
      ],
      plan30Days: [
        'Secure sponsorship/visa',
        'Open local bank account',
        'Understand legal requirements',
        'Map business opportunities',
      ],
      plan12Months: [
        'Maximize income/savings',
        'Build professional network',
        'Explore business options',
        'Start investment portfolio',
      ],
      plan5Years: [
        'Build significant savings',
        'Create portable income',
        'Establish multi-country presence',
        'Plan exit to next destination',
      ],
      planB: 'UAE is a wealth-building station, not a final destination for most. Plan next move to Portugal (Golden Visa), Singapore, or return home with capital.',
    },
    snapshot: {
      gdpPerCapita: 47790,
      population: 10000000,
      passportRank: 15,
      corruptionIndex: 67,
      freedomIndex: 17,
    },
    visa: {
      workVisa: 'easy',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      investmentMinimum: 550000,
      citizenshipYears: 30,
      notes: 'Golden Visa for investors/skilled; Freelancer visa; Remote work visa available',
    },
    costOfLiving: {
      index: 62,
      rentIndex: 45,
      groceriesIndex: 55,
      monthlyBudgetSingle: 2500,
      monthlyBudgetFamily: 5500,
    },
    qualityOfLife: {
      healthcareRank: 27,
      educationIndex: 0.78,
      safetyIndex: 85,
      environmentIndex: 45,
      workLifeBalance: 6,
      internetSpeed: 210,
    },
    lgbtqRights: {
      index: 10,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexuality illegal; severe penalties; extreme caution required',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'singapore',
    name: 'Singapore',
    nameLocal: 'Singapore / 新加坡',
    iso2: 'SG',
    region: 'Southeast Asia',
    pyramidType: 'COMPETENCE_TRUST',
    ruleOfGold: 'Deliver results, follow rules, build wealth quietly. Excellence is expected.',
    pyramid: {
      top: 'Government-led meritocratic elite',
      institutions: 'Efficient, corruption-free bureaucracy',
      gatekeepers: 'Education credentials and professional standards',
      valueCreators: 'Skilled professionals and entrepreneurs',
      base: 'Migrant workers and service economy',
      realAsset: 'Competence, efficiency, and rule of law',
    },
    risks: {
      legal: 15,
      safety: 5,
      corruption: 10,
      volatility: 15,
      bureaucracy: 25,
    },
    whoWins: [
      'High-performing professionals',
      'Entrepreneurs with capital',
      'Meritocracy believers',
      'Rule-followers with skills',
    ],
    whoLoses: [
      'Free speech advocates',
      'Those who challenge authority',
      'Low-income workers',
      'Those seeking social mobility without credentials',
    ],
    playbook: {
      do: [
        'Excel at your profession',
        'Build savings and investments',
        'Network within your industry',
        'Follow all rules meticulously',
        'Plan for housing early (CPF)',
      ],
      dont: [
        'Criticize government publicly',
        'Ignore legal requirements',
        'Expect social safety nets',
        'Underestimate cost of living',
        'Take shortcuts',
      ],
      plan30Days: [
        'Secure employment pass',
        'Open bank and CPF accounts',
        'Find housing within budget',
        'Understand legal constraints',
      ],
      plan12Months: [
        'Build professional reputation',
        'Start investment portfolio',
        'Network actively',
        'Apply for permanent residence',
      ],
      plan5Years: [
        'Achieve PR or citizenship',
        'Build property equity',
        'Establish regional network',
        'Create passive income',
      ],
      planB: 'Singapore is a high-income hub. Consider Malaysia for lower costs, Hong Kong for finance, or return home with capital and credentials.',
    },
    snapshot: {
      gdpPerCapita: 82810,
      population: 5900000,
      passportRank: 1,
      corruptionIndex: 83,
      freedomIndex: 48,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 2500000,
      citizenshipYears: 2,
      notes: 'Employment Pass for professionals; EntrePass for entrepreneurs; high salary thresholds',
    },
    costOfLiving: {
      index: 85,
      rentIndex: 75,
      groceriesIndex: 72,
      monthlyBudgetSingle: 3200,
      monthlyBudgetFamily: 6800,
    },
    qualityOfLife: {
      healthcareRank: 6,
      educationIndex: 0.93,
      safetyIndex: 82,
      environmentIndex: 58,
      workLifeBalance: 5,
      internetSpeed: 255,
    },
    lgbtqRights: {
      index: 45,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Decriminalized in 2022; no legal recognition; improving but limited',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'portugal',
    name: 'Portugal',
    nameLocal: 'Portugal',
    iso2: 'PT',
    region: 'Southern Europe',
    pyramidType: 'STABILITY_REDIS',
    ruleOfGold: 'Patience and relationships matter more than speed. Integrate slowly but surely.',
    pyramid: {
      top: 'European integration and stability',
      institutions: 'Bureaucratic but accessible government',
      gatekeepers: 'Residency permits and local networks',
      valueCreators: 'Tech workers, digital nomads, retirees',
      base: 'Local economy and traditional sectors',
      realAsset: 'Quality of life and EU access',
    },
    risks: {
      legal: 20,
      safety: 15,
      corruption: 35,
      volatility: 25,
      bureaucracy: 65,
    },
    whoWins: [
      'Remote workers with foreign income',
      'Retirees with pensions',
      'Digital nomads seeking EU base',
      'Patient relationship builders',
    ],
    whoLoses: [
      'Those expecting high local salaries',
      'Impatient entrepreneurs',
      'Those needing fast bureaucracy',
      'Non-EU citizens without income',
    ],
    playbook: {
      do: [
        'Bring foreign income or savings',
        'Learn Portuguese eventually',
        'Build local relationships slowly',
        'Use NHR tax regime if eligible',
        'Explore D7 or Digital Nomad visa',
      ],
      dont: [
        'Expect high local wages',
        'Rush bureaucratic processes',
        'Ignore tax implications',
        'Dismiss local culture',
        'Burn through savings quickly',
      ],
      plan30Days: [
        'Research visa options (D7/D8)',
        'Calculate cost of living',
        'Open bank account',
        'Start Portuguese basics',
      ],
      plan12Months: [
        'Secure residence permit',
        'Establish income streams',
        'Build local network',
        'Explore NHR benefits',
      ],
      plan5Years: [
        'Qualify for permanent residence',
        'Apply for citizenship',
        'Build EU network',
        'Establish long-term base',
      ],
      planB: 'Portugal offers EU citizenship path. Consider Spain for more economy, Netherlands for higher income, or use Portuguese passport for global mobility.',
    },
    snapshot: {
      gdpPerCapita: 26260,
      population: 10300000,
      passportRank: 5,
      corruptionIndex: 62,
      freedomIndex: 95,
    },
    visa: {
      workVisa: 'easy',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      investmentMinimum: 500000,
      citizenshipYears: 5,
      notes: 'D7 passive income visa; Digital Nomad visa; Golden Visa (modified 2023)',
    },
    costOfLiving: {
      index: 51,
      rentIndex: 32,
      groceriesIndex: 48,
      monthlyBudgetSingle: 1500,
      monthlyBudgetFamily: 3200,
    },
    qualityOfLife: {
      healthcareRank: 22,
      educationIndex: 0.76,
      safetyIndex: 72,
      environmentIndex: 74,
      workLifeBalance: 8,
      internetSpeed: 165,
    },
    lgbtqRights: {
      index: 88,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Marriage since 2010; comprehensive protections; very progressive',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    nameLocal: 'Nigeria',
    iso2: 'NG',
    region: 'West Africa',
    pyramidType: 'PROBLEM_RENT',
    ruleOfGold: 'Navigate the chaos, never depend on the system, always have multiple options.',
    pyramid: {
      top: 'Political elite and oil interests',
      institutions: 'Weak, often captured by private interests',
      gatekeepers: 'Connections, bribery, and informal networks',
      valueCreators: 'Entrepreneurs, tech innovators, diaspora',
      base: 'Massive young population with limited opportunity',
      realAsset: 'Controlled dysfunction and resource extraction',
    },
    risks: {
      legal: 75,
      safety: 70,
      corruption: 85,
      volatility: 75,
      bureaucracy: 80,
    },
    whoWins: [
      'Connected political insiders',
      'Entrepreneurs who move fast',
      'Tech-savvy problem solvers',
      'Those with diaspora networks',
    ],
    whoLoses: [
      'Rule followers without connections',
      'Those dependent on formal systems',
      'Transparent operators',
      'Those without exit options',
    ],
    playbook: {
      do: [
        'Build multiple income streams',
        'Create international options early',
        'Network within diaspora',
        'Develop exportable tech skills',
        'Stay politically neutral',
      ],
      dont: [
        'Trust formal institutions',
        'Become too visible without protection',
        'Centralize all assets locally',
        'Ignore security concerns',
        'Get involved in politics',
      ],
      plan30Days: [
        'Secure all important documents',
        'Start emergency fund in stable currency',
        'Identify exportable skill to develop',
        'Map diaspora connections',
      ],
      plan12Months: [
        'Build remote income capability',
        'Open international bank account',
        'Create passive income stream',
        'Research visa options',
      ],
      plan5Years: [
        'Establish residence option abroad',
        'Diversify assets internationally',
        'Build global professional network',
        'Create location-independent business',
      ],
      planB: 'Target UK, Canada, or US for diaspora communities. Ghana for regional option. Build tech skills for remote work opportunities globally.',
    },
    snapshot: {
      gdpPerCapita: 2180,
      population: 220000000,
      passportRank: 94,
      corruptionIndex: 24,
      freedomIndex: 43,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 15,
      notes: 'Limited formal immigration; diaspora return programs exist',
    },
    costOfLiving: {
      index: 32,
      rentIndex: 18,
      groceriesIndex: 38,
      monthlyBudgetSingle: 600,
      monthlyBudgetFamily: 1500,
    },
    qualityOfLife: {
      healthcareRank: 163,
      educationIndex: 0.53,
      safetyIndex: 28,
      environmentIndex: 35,
      workLifeBalance: 4,
      internetSpeed: 25,
    },
    lgbtqRights: {
      index: 5,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Criminalized with severe penalties up to 14 years; death penalty in some states',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'japan',
    name: 'Japan',
    nameLocal: '日本',
    iso2: 'JP',
    region: 'East Asia',
    pyramidType: 'COMPETENCE_TRUST',
    ruleOfGold: 'Patience, precision, and group harmony. Individual excellence serves the collective.',
    pyramid: {
      top: 'Corporate hierarchies and institutional trust',
      institutions: 'Highly efficient, consensus-driven',
      gatekeepers: 'Seniority, credentials, and cultural fit',
      valueCreators: 'Skilled workers within the system',
      base: 'Aging population maintaining traditions',
      realAsset: 'Trust, quality, and social cohesion',
    },
    risks: {
      legal: 10,
      safety: 5,
      corruption: 20,
      volatility: 15,
      bureaucracy: 55,
    },
    whoWins: [
      'Patient long-term builders',
      'Those who master Japanese language/culture',
      'Technical specialists',
      'Group-oriented team players',
    ],
    whoLoses: [
      'Individualistic achievers',
      'Those who challenge hierarchy',
      'Impatient career climbers',
      'Cultural outsiders',
    ],
    playbook: {
      do: [
        'Learn Japanese seriously (N2 minimum)',
        'Understand group dynamics',
        'Build long-term relationships',
        'Respect hierarchy and seniority',
        'Demonstrate consistent reliability',
      ],
      dont: [
        'Challenge authority directly',
        'Expect rapid advancement',
        'Ignore cultural norms',
        'Job-hop frequently',
        'Stand out too much',
      ],
      plan30Days: [
        'Secure visa/residence status',
        'Start intensive Japanese study',
        'Understand workplace culture',
        'Find stable housing',
      ],
      plan12Months: [
        'Achieve N3+ Japanese level',
        'Build workplace relationships',
        'Understand local systems',
        'Establish financial stability',
      ],
      plan5Years: [
        'Achieve N2/N1 Japanese',
        'Apply for permanent residence',
        'Build professional reputation',
        'Integrate into community',
      ],
      planB: 'Japan rewards patience. Consider Singapore for faster advancement, Taiwan for similar culture with less hierarchy, or return home with Japanese credentials.',
    },
    snapshot: {
      gdpPerCapita: 33820,
      population: 125000000,
      passportRank: 1,
      corruptionIndex: 73,
      freedomIndex: 96,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: false,
      citizenshipYears: 5,
      notes: 'Highly Skilled Professional visa; startup visa in select cities; digital nomad visa (2024)',
    },
    costOfLiving: {
      index: 76,
      rentIndex: 32,
      groceriesIndex: 82,
      monthlyBudgetSingle: 2000,
      monthlyBudgetFamily: 4200,
    },
    qualityOfLife: {
      healthcareRank: 10,
      educationIndex: 0.85,
      safetyIndex: 78,
      environmentIndex: 68,
      workLifeBalance: 4,
      internetSpeed: 185,
    },
    lgbtqRights: {
      index: 50,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'No legal recognition; some cities offer partnership certificates; socially improving',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'brazil',
    name: 'Brazil',
    nameLocal: 'Brasil',
    iso2: 'BR',
    region: 'South America',
    pyramidType: 'PROBLEM_RENT',
    ruleOfGold: 'Connections matter more than competence. Navigate the jeitinho brasileiro.',
    pyramid: {
      top: 'Political and economic elite',
      institutions: 'Complex bureaucracy with informal workarounds',
      gatekeepers: 'Cartórios, connections, and informal networks',
      valueCreators: 'Entrepreneurs navigating the sistema',
      base: 'Large population with limited mobility',
      realAsset: 'Complexity creates opportunity for insiders',
    },
    risks: {
      legal: 55,
      safety: 65,
      corruption: 70,
      volatility: 55,
      bureaucracy: 80,
    },
    whoWins: [
      'Connected insiders',
      'Relationship builders',
      'Patient navigators of bureaucracy',
      'Entrepreneurs with foreign income',
    ],
    whoLoses: [
      'Those expecting formal meritocracy',
      'Foreign investors without local partners',
      'Rule followers in informal economy',
      'Those without safety buffers',
    ],
    playbook: {
      do: [
        'Build strong local relationships',
        'Learn to navigate bureaucracy',
        'Diversify income sources',
        'Have foreign income if possible',
        'Build international options',
      ],
      dont: [
        'Expect formal rules to apply equally',
        'Ignore security precautions',
        'Centralize all assets in Brazil',
        'Trust the legal system blindly',
        'Underestimate bureaucracy',
      ],
      plan30Days: [
        'Get CPF and local documents',
        'Open bank account',
        'Understand visa requirements',
        'Start Portuguese learning',
      ],
      plan12Months: [
        'Build local professional network',
        'Establish income streams',
        'Learn bureaucratic navigation',
        'Create emergency fund',
      ],
      plan5Years: [
        'Build permanent residence',
        'Diversify assets internationally',
        'Create location-independent income',
        'Establish regional network',
      ],
      planB: 'Brazil offers good lifestyle but complex systems. Consider Portugal for EU access (language advantage), Argentina for regional option, or US for more straightforward rules.',
    },
    snapshot: {
      gdpPerCapita: 9670,
      population: 216000000,
      passportRank: 19,
      corruptionIndex: 36,
      freedomIndex: 72,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      investmentMinimum: 100000,
      citizenshipYears: 4,
      notes: 'Digital Nomad visa (2024); investment visa available; relatively accessible',
    },
    costOfLiving: {
      index: 38,
      rentIndex: 18,
      groceriesIndex: 35,
      monthlyBudgetSingle: 1000,
      monthlyBudgetFamily: 2400,
    },
    qualityOfLife: {
      healthcareRank: 89,
      educationIndex: 0.69,
      safetyIndex: 32,
      environmentIndex: 52,
      workLifeBalance: 7,
      internetSpeed: 95,
    },
    lgbtqRights: {
      index: 60,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'caution',
      notes: 'Marriage since 2013; but high violence against LGBTQ+ people',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    nameLocal: 'Nederland',
    iso2: 'NL',
    region: 'Western Europe',
    pyramidType: 'COMPETENCE_TRUST',
    ruleOfGold: 'Be direct, be competent, be integrated. The system rewards those who contribute.',
    pyramid: {
      top: 'Consensus-driven institutions and trade',
      institutions: 'Efficient, transparent bureaucracy',
      gatekeepers: 'Professional credentials and integration',
      valueCreators: 'Skilled professionals, entrepreneurs, traders',
      base: 'Well-protected workforce with strong rights',
      realAsset: 'Trust, efficiency, and trade networks',
    },
    risks: {
      legal: 10,
      safety: 15,
      corruption: 15,
      volatility: 15,
      bureaucracy: 45,
    },
    whoWins: [
      'Highly skilled professionals',
      'Tech workers and entrepreneurs',
      'Those who integrate culturally',
      'Direct communicators',
    ],
    whoLoses: [
      'Those avoiding integration',
      'Non-Dutch speakers long-term',
      'Hierarchical personalities',
      'Those seeking tax optimization',
    ],
    playbook: {
      do: [
        'Get 30% ruling if eligible',
        'Learn Dutch eventually',
        'Integrate into local culture',
        'Build professional network',
        'Embrace direct communication',
      ],
      dont: [
        'Stay in expat bubble long-term',
        'Ignore Dutch language',
        'Expect hierarchy to work',
        'Underestimate housing market',
        'Ignore integration requirements',
      ],
      plan30Days: [
        'Secure residence/work permit',
        'Apply for 30% ruling',
        'Register with gemeente',
        'Open Dutch bank account',
      ],
      plan12Months: [
        'Start Dutch language course',
        'Build professional network',
        'Understand housing market',
        'Integrate into local life',
      ],
      plan5Years: [
        'Achieve Dutch proficiency',
        'Apply for permanent residence',
        'Consider citizenship',
        'Build long-term career',
      ],
      planB: 'Netherlands offers EU hub with English. Consider Germany for more opportunities, Belgium for lower costs, or UK for pure English environment.',
    },
    snapshot: {
      gdpPerCapita: 57410,
      population: 17800000,
      passportRank: 5,
      corruptionIndex: 79,
      freedomIndex: 97,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 5,
      notes: 'Highly Skilled Migrant visa; 30% ruling tax benefit; startup visa program',
    },
    costOfLiving: {
      index: 76,
      rentIndex: 48,
      groceriesIndex: 62,
      monthlyBudgetSingle: 2400,
      monthlyBudgetFamily: 4800,
    },
    qualityOfLife: {
      healthcareRank: 17,
      educationIndex: 0.92,
      safetyIndex: 68,
      environmentIndex: 75,
      workLifeBalance: 9,
      internetSpeed: 195,
    },
    lgbtqRights: {
      index: 98,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'First country to legalize same-sex marriage (2001); world leader',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'morocco',
    name: 'Morocco',
    nameLocal: 'المغرب / Maroc',
    iso2: 'MA',
    region: 'North Africa',
    pyramidType: 'PROBLEM_RENT',
    ruleOfGold: 'Relationships unlock everything. Build trust before expecting results.',
    pyramid: {
      top: 'Monarchy and established elite',
      institutions: 'Modernizing but relationship-driven',
      gatekeepers: 'Family networks and traditional connections',
      valueCreators: 'Entrepreneurs, tourism, and outsourcing',
      base: 'Large informal economy and youth',
      realAsset: 'Strategic position and relationships',
    },
    risks: {
      legal: 50,
      safety: 35,
      corruption: 60,
      volatility: 40,
      bureaucracy: 65,
    },
    whoWins: [
      'Those with strong local connections',
      'French/Arabic speakers',
      'Patient relationship builders',
      'Entrepreneurs in tourism/outsourcing',
    ],
    whoLoses: [
      'Those expecting Western efficiency',
      'Impatient operators',
      'Non-French/Arabic speakers',
      'Rule followers in informal contexts',
    ],
    playbook: {
      do: [
        'Learn French and Arabic basics',
        'Build local relationships first',
        'Be patient with bureaucracy',
        'Embrace cultural integration',
        'Use Morocco as bridge to Africa',
      ],
      dont: [
        'Expect Western-style efficiency',
        'Ignore relationship building',
        'Rush business decisions',
        'Dismiss local customs',
        'Centralize all assets locally',
      ],
      plan30Days: [
        'Secure visa/residence',
        'Start French/Arabic learning',
        'Build initial network',
        'Understand local customs',
      ],
      plan12Months: [
        'Establish local relationships',
        'Navigate bureaucracy',
        'Build income streams',
        'Integrate culturally',
      ],
      plan5Years: [
        'Build permanent residence',
        'Establish business/career',
        'Create regional network',
        'Consider EU alternatives',
      ],
      planB: 'Morocco is a bridge. Consider France/Spain for EU access (cultural ties), UAE for business, or Senegal for Francophone Africa expansion.',
    },
    snapshot: {
      gdpPerCapita: 3790,
      population: 37500000,
      passportRank: 80,
      corruptionIndex: 38,
      freedomIndex: 37,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 5,
      notes: 'Relatively open to visitors; work permits through employers; limited formal programs',
    },
    costOfLiving: {
      index: 35,
      rentIndex: 12,
      groceriesIndex: 32,
      monthlyBudgetSingle: 700,
      monthlyBudgetFamily: 1600,
    },
    qualityOfLife: {
      healthcareRank: 84,
      educationIndex: 0.56,
      safetyIndex: 55,
      environmentIndex: 52,
      workLifeBalance: 6,
      internetSpeed: 45,
    },
    lgbtqRights: {
      index: 15,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Criminalized; up to 3 years imprisonment; social stigma',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'australia',
    name: 'Australia',
    nameLocal: 'Australia',
    iso2: 'AU',
    region: 'Oceania',
    pyramidType: 'STABILITY_REDIS',
    ruleOfGold: 'Fair go for those who contribute. The system rewards persistence and skills.',
    pyramid: {
      top: 'Resource wealth and institutional stability',
      institutions: 'Strong, fair, and accessible',
      gatekeepers: 'Points-based immigration and credentials',
      valueCreators: 'Skilled migrants, miners, professionals',
      base: 'Well-protected workforce with high wages',
      realAsset: 'Resources, stability, and quality of life',
    },
    risks: {
      legal: 10,
      safety: 15,
      corruption: 20,
      volatility: 20,
      bureaucracy: 45,
    },
    whoWins: [
      'Skilled migrants with points',
      'Professionals in demand fields',
      'Those seeking work-life balance',
      'Families prioritizing quality of life',
    ],
    whoLoses: [
      'Those seeking explosive wealth',
      'Non-skilled workers',
      'Those in oversupplied professions',
      'Those needing proximity to Europe/Asia',
    ],
    playbook: {
      do: [
        'Maximize points for skilled migration',
        'Get credentials assessed early',
        'Target in-demand occupations',
        'Build Australian work experience',
        'Embrace outdoor lifestyle',
      ],
      dont: [
        'Underestimate cost of living',
        'Ignore credential requirements',
        'Expect European-level culture access',
        'Ignore geographic isolation',
        'Rush the immigration process',
      ],
      plan30Days: [
        'Complete skills assessment',
        'Research visa options',
        'Calculate points score',
        'Understand cost of living',
      ],
      plan12Months: [
        'Secure visa pathway',
        'Establish Australian work history',
        'Build professional network',
        'Open local financial accounts',
      ],
      plan5Years: [
        'Achieve permanent residence',
        'Apply for citizenship',
        'Build investment portfolio',
        'Establish long-term career',
      ],
      planB: 'Australia offers great lifestyle but isolation. Consider New Zealand for similar culture, Canada for Northern Hemisphere option, or Singapore for Asia access.',
    },
    snapshot: {
      gdpPerCapita: 64670,
      population: 26500000,
      passportRank: 6,
      corruptionIndex: 75,
      freedomIndex: 95,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 2500000,
      citizenshipYears: 4,
      notes: 'Points-based skilled migration; GTI for exceptional talent; investor visas available',
    },
    costOfLiving: {
      index: 73,
      rentIndex: 45,
      groceriesIndex: 78,
      monthlyBudgetSingle: 2600,
      monthlyBudgetFamily: 5400,
    },
    qualityOfLife: {
      healthcareRank: 32,
      educationIndex: 0.93,
      safetyIndex: 58,
      environmentIndex: 74,
      workLifeBalance: 8,
      internetSpeed: 78,
    },
    lgbtqRights: {
      index: 82,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Marriage since 2017; strong legal protections; very progressive',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  // ============== HYBRID_TRANSITION Countries ==============
  {
    id: 'china',
    name: 'China',
    nameLocal: '中国',
    iso2: 'CN',
    region: 'East Asia',
    pyramidType: 'HYBRID_TRANSITION',
    ruleOfGold: 'Align with the Party line publicly, build privately. Never become a political symbol.',
    pyramid: {
      top: 'Communist Party and state-aligned capital',
      institutions: 'State apparatus blending control and market',
      gatekeepers: 'Party connections, guanxi networks, regulatory approvals',
      valueCreators: 'Entrepreneurs operating within political boundaries',
      base: 'Workers navigating rapid transformation',
      realAsset: 'Adaptation speed and political alignment',
    },
    risks: {
      legal: 70,
      safety: 40,
      corruption: 55,
      volatility: 65,
      bureaucracy: 75,
    },
    whoWins: [
      'Those who read political winds correctly',
      'State-aligned entrepreneurs',
      'Tech-savvy adaptors',
      'Those with strong guanxi networks',
    ],
    whoLoses: [
      'Politically outspoken individuals',
      'Those who grow too visible too fast',
      'Foreign-dependent businesses',
      'Those betting against state direction',
    ],
    playbook: {
      do: [
        'Understand political signals deeply',
        'Build multiple income streams quietly',
        'Maintain political neutrality publicly',
        'Develop international options discreetly',
        'Master guanxi without dependence',
      ],
      dont: [
        'Become politically prominent',
        'Criticize the system publicly',
        'Depend on single sector or patron',
        'Ignore regulatory changes',
        'Flaunt wealth ostentatiously',
      ],
      plan30Days: [
        'Map your current political exposure',
        'Identify your guanxi network value',
        'Start VPN and information alternatives',
        'Assess your sector political sensitivity',
      ],
      plan12Months: [
        'Build diversified income streams',
        'Establish international connections quietly',
        'Develop portable skills',
        'Create offshore financial options',
      ],
      plan5Years: [
        'Secure residence options abroad',
        'Diversify assets internationally',
        'Build reputation in global networks',
        'Create location-independent income',
      ],
      planB: 'Singapore for Chinese business continuity, Canada/Australia for family emigration, Portugal for EU access. Keep mainland presence while building alternatives.',
    },
    snapshot: {
      gdpPerCapita: 12720,
      population: 1412000000,
      passportRank: 62,
      corruptionIndex: 42,
      freedomIndex: 9,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 10,
      notes: 'Citizenship nearly impossible for foreigners; work visas tied to employer',
    },
    costOfLiving: {
      index: 42,
      rentIndex: 28,
      groceriesIndex: 38,
      monthlyBudgetSingle: 1100,
      monthlyBudgetFamily: 2800,
    },
    qualityOfLife: {
      healthcareRank: 48,
      educationIndex: 0.72,
      safetyIndex: 68,
      environmentIndex: 45,
      workLifeBalance: 4,
      internetSpeed: 165,
    },
    lgbtqRights: {
      index: 35,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Not criminalized but no protections; social stigma varies by region',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'russia',
    name: 'Russia',
    nameLocal: 'Россия',
    iso2: 'RU',
    region: 'Eastern Europe',
    pyramidType: 'HYBRID_TRANSITION',
    ruleOfGold: 'Stay below the radar, diversify abroad, never challenge power directly.',
    pyramid: {
      top: 'Political elite and state-connected oligarchs',
      institutions: 'State apparatus mixing Soviet legacy and capitalism',
      gatekeepers: 'Security services, regional bosses, connected businessmen',
      valueCreators: 'Entrepreneurs navigating unpredictable rules',
      base: 'Population adapting to constant change',
      realAsset: 'Survival skills and adaptability',
    },
    risks: {
      legal: 80,
      safety: 55,
      corruption: 75,
      volatility: 85,
      bureaucracy: 70,
    },
    whoWins: [
      'Those with Kremlin connections',
      'Adaptable survivors',
      'Resource sector insiders',
      'Those with international diversification',
    ],
    whoLoses: [
      'Political opponents',
      'Visible wealthy without protection',
      'Foreign-dependent businesses',
      'Those expecting stable rules',
    ],
    playbook: {
      do: [
        'Stay politically invisible',
        'Diversify internationally immediately',
        'Build portable skills and assets',
        'Maintain multiple passports if possible',
        'Keep cash and assets abroad',
      ],
      dont: [
        'Challenge political power',
        'Concentrate wealth visibly',
        'Depend on domestic institutions',
        'Trust long-term stability',
        'Ignore exit planning',
      ],
      plan30Days: [
        'Assess your political exposure',
        'Open foreign bank accounts',
        'Secure important documents',
        'Identify immediate exit options',
      ],
      plan12Months: [
        'Establish residence permit abroad',
        'Build remote income capabilities',
        'Diversify assets geographically',
        'Create emergency relocation plan',
      ],
      plan5Years: [
        'Achieve permanent residence elsewhere',
        'Build international income streams',
        'Secure family exit options',
        'Create sustainable life abroad',
      ],
      planB: 'UAE for business continuity, Georgia/Armenia for easy relocation, Serbia for visa-free access. Israel if eligible. Europe increasingly difficult.',
    },
    snapshot: {
      gdpPerCapita: 12200,
      population: 144000000,
      passportRank: 52,
      corruptionIndex: 28,
      freedomIndex: 16,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 5,
      notes: 'Citizenship possible but complex; current sanctions affect international integration',
    },
    costOfLiving: {
      index: 35,
      rentIndex: 15,
      groceriesIndex: 32,
      monthlyBudgetSingle: 800,
      monthlyBudgetFamily: 2000,
    },
    qualityOfLife: {
      healthcareRank: 58,
      educationIndex: 0.82,
      safetyIndex: 45,
      environmentIndex: 52,
      workLifeBalance: 6,
      internetSpeed: 85,
    },
    lgbtqRights: {
      index: 15,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Propaganda law restricts LGBTQ+ visibility; significant discrimination and violence',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  // ============== RESOURCE_EXTRACTION Countries ==============
  {
    id: 'norway',
    name: 'Norway',
    nameLocal: 'Norge',
    iso2: 'NO',
    region: 'Northern Europe',
    pyramidType: 'RESOURCE_EXTRACTION',
    ruleOfGold: 'Resources are collective wealth. Excellence within egalitarian norms wins.',
    pyramid: {
      top: 'Sovereign wealth fund and democratic institutions',
      institutions: 'Transparent state managing resource wealth',
      gatekeepers: 'Education system and professional standards',
      valueCreators: 'Skilled workers in energy and tech sectors',
      base: 'Citizens benefiting from resource redistribution',
      realAsset: 'Well-managed natural resources and social trust',
    },
    risks: {
      legal: 8,
      safety: 5,
      corruption: 10,
      volatility: 15,
      bureaucracy: 35,
    },
    whoWins: [
      'Those embracing egalitarian values',
      'Energy sector professionals',
      'Long-term planners',
      'Those valuing work-life balance',
    ],
    whoLoses: [
      'Those seeking extreme wealth display',
      'Outsiders not learning Norwegian',
      'Those expecting class distinctions',
      'Impatient disruptors',
    ],
    playbook: {
      do: [
        'Learn Norwegian seriously',
        'Embrace Janteloven (egalitarian culture)',
        'Build expertise in energy/tech',
        'Value work-life balance genuinely',
        'Integrate into local community',
      ],
      dont: [
        'Display wealth ostentatiously',
        'Act superior or elitist',
        'Ignore language requirements',
        'Expect quick networking wins',
        'Underestimate winter challenges',
      ],
      plan30Days: [
        'Start Norwegian language course',
        'Research residence requirements',
        'Understand tax and benefits system',
        'Identify relevant industry sector',
      ],
      plan12Months: [
        'Achieve basic Norwegian fluency',
        'Establish professional network',
        'Integrate into local community',
        'Understand regulatory landscape',
      ],
      plan5Years: [
        'Achieve permanent residence',
        'Build strong professional reputation',
        'Consider citizenship path',
        'Establish deep community roots',
      ],
      planB: 'Other Nordic countries (Sweden, Denmark) for similar values. Netherlands or Germany for EU alternatives. Canada for similar work-life culture.',
    },
    snapshot: {
      gdpPerCapita: 89150,
      population: 5400000,
      passportRank: 8,
      corruptionIndex: 84,
      freedomIndex: 100,
    },
    visa: {
      workVisa: 'difficult',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 7,
      notes: 'Skilled worker visa requires job offer; high salary requirements; not in EU but EEA',
    },
    costOfLiving: {
      index: 105,
      rentIndex: 48,
      groceriesIndex: 85,
      monthlyBudgetSingle: 3200,
      monthlyBudgetFamily: 6500,
    },
    qualityOfLife: {
      healthcareRank: 11,
      educationIndex: 0.91,
      safetyIndex: 75,
      environmentIndex: 88,
      workLifeBalance: 9,
      internetSpeed: 175,
    },
    lgbtqRights: {
      index: 90,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Marriage since 2009; one of the most progressive countries globally',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'qatar',
    name: 'Qatar',
    nameLocal: 'قطر',
    iso2: 'QA',
    region: 'Middle East',
    pyramidType: 'RESOURCE_EXTRACTION',
    ruleOfGold: 'You are a guest in the system. Perform, save, and plan your exit.',
    pyramid: {
      top: 'Royal family and ruling elite',
      institutions: 'State-controlled resource distribution',
      gatekeepers: 'Kafala sponsors and government connections',
      valueCreators: 'Expatriate professionals and workers',
      base: 'Migrant labor force with limited rights',
      realAsset: 'Access to oil and gas wealth flows',
    },
    risks: {
      legal: 60,
      safety: 20,
      corruption: 45,
      volatility: 40,
      bureaucracy: 55,
    },
    whoWins: [
      'High-value expatriate professionals',
      'Those with strong sponsor relationships',
      'Short-term wealth builders',
      'Networkers in business community',
    ],
    whoLoses: [
      'Those seeking permanent belonging',
      'Low-skilled workers',
      'Those challenging local customs',
      'Long-term planners without exit strategy',
    ],
    playbook: {
      do: [
        'Maximize income and save aggressively',
        'Build international professional network',
        'Respect local customs publicly',
        'Plan your exit from day one',
        'Develop portable skills',
      ],
      dont: [
        'Expect permanent residence or citizenship',
        'Criticize government or culture',
        'Depend on single employer',
        'Ignore cultural expectations',
        'Spend all your income locally',
      ],
      plan30Days: [
        'Understand your visa and sponsor terms',
        'Open international bank accounts',
        'Set up savings automation',
        'Map your professional network potential',
      ],
      plan12Months: [
        'Save 50%+ of income consistently',
        'Build strong professional reputation',
        'Develop portable credentials',
        'Research next destination options',
      ],
      plan5Years: [
        'Accumulate significant savings',
        'Secure next destination residence',
        'Build international income sources',
        'Execute exit plan',
      ],
      planB: 'UAE for regional continuity, Singapore for Asian hub, Europe (Portugal, Netherlands) for permanent residence. Use Gulf savings to fund transition.',
    },
    snapshot: {
      gdpPerCapita: 66840,
      population: 2700000,
      passportRank: 54,
      corruptionIndex: 58,
      freedomIndex: 25,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 200000,
      citizenshipYears: 99,
      notes: 'Citizenship essentially impossible; permanent residency very limited; kafala system for workers',
    },
    costOfLiving: {
      index: 68,
      rentIndex: 52,
      groceriesIndex: 60,
      monthlyBudgetSingle: 2400,
      monthlyBudgetFamily: 5000,
    },
    qualityOfLife: {
      healthcareRank: 34,
      educationIndex: 0.78,
      safetyIndex: 85,
      environmentIndex: 58,
      workLifeBalance: 5,
      internetSpeed: 145,
    },
    lgbtqRights: {
      index: 8,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexuality illegal; severe penalties; extreme caution required',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'saudi-arabia',
    name: 'Saudi Arabia',
    nameLocal: 'المملكة العربية السعودية',
    iso2: 'SA',
    region: 'Middle East',
    pyramidType: 'RESOURCE_EXTRACTION',
    ruleOfGold: 'Perform your role, accumulate wealth, never challenge the order. You are temporary.',
    pyramid: {
      top: 'Royal family and religious authority',
      institutions: 'State controlling oil wealth distribution',
      gatekeepers: 'Government sponsors, connected businesses',
      valueCreators: 'Expatriate professionals and Vision 2030 sectors',
      base: 'Migrant labor force',
      realAsset: 'Proximity to oil wealth and royal favor',
    },
    risks: {
      legal: 70,
      safety: 25,
      corruption: 50,
      volatility: 45,
      bureaucracy: 60,
    },
    whoWins: [
      'High-value expatriate professionals',
      'Vision 2030 sector pioneers',
      'Those with royal or government connections',
      'Short-term wealth maximizers',
    ],
    whoLoses: [
      'Those seeking permanent belonging',
      'Women and minorities with limited rights',
      'Low-skilled workers',
      'Those challenging social norms',
    ],
    playbook: {
      do: [
        'Maximize income and save 60%+',
        'Build transferable global credentials',
        'Network in Vision 2030 sectors',
        'Plan exit strategy from day one',
        'Respect all social and religious norms publicly',
      ],
      dont: [
        'Expect citizenship or permanent stay',
        'Challenge religious or social norms',
        'Depend on single employer',
        'Display non-conforming behavior',
        'Invest heavily in local assets',
      ],
      plan30Days: [
        'Understand iqama and sponsorship terms',
        'Open international bank accounts',
        'Set up aggressive savings automation',
        'Map Vision 2030 opportunities',
      ],
      plan12Months: [
        'Save minimum 50% of income',
        'Build reputation in growth sectors',
        'Develop international network',
        'Research next destination',
      ],
      plan5Years: [
        'Accumulate substantial capital',
        'Secure residence in target country',
        'Build location-independent income',
        'Execute planned transition',
      ],
      planB: 'UAE for continued Gulf presence, Singapore or Europe for next stage. Use accumulated capital to buy residence elsewhere.',
    },
    snapshot: {
      gdpPerCapita: 27540,
      population: 36000000,
      passportRank: 64,
      corruptionIndex: 53,
      freedomIndex: 7,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 200000,
      citizenshipYears: 99,
      notes: 'Citizenship essentially impossible; work visa tied to sponsor; new premium residency program exists',
    },
    costOfLiving: {
      index: 48,
      rentIndex: 25,
      groceriesIndex: 42,
      monthlyBudgetSingle: 1800,
      monthlyBudgetFamily: 4000,
    },
    qualityOfLife: {
      healthcareRank: 26,
      educationIndex: 0.77,
      safetyIndex: 80,
      environmentIndex: 55,
      workLifeBalance: 5,
      internetSpeed: 125,
    },
    lgbtqRights: {
      index: 5,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexuality punishable by death; extreme danger; complete discretion required',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  // ============== PROBLEM_RENT Countries ==============
  {
    id: 'venezuela',
    name: 'Venezuela',
    nameLocal: 'Venezuela',
    iso2: 'VE',
    region: 'South America',
    pyramidType: 'PROBLEM_RENT',
    ruleOfGold: 'The crisis is the system. Survive through parallel economies and exit options.',
    pyramid: {
      top: 'Political elite and military connected to state resources',
      institutions: 'Collapsed state apparatus serving insiders',
      gatekeepers: 'Party connections, military contacts, currency controllers',
      valueCreators: 'Survivors in parallel economies',
      base: 'Population navigating hyperinflation and scarcity',
      realAsset: 'Access to dollars and connections to power',
    },
    risks: {
      legal: 85,
      safety: 80,
      corruption: 90,
      volatility: 95,
      bureaucracy: 85,
    },
    whoWins: [
      'Those with dollar income sources',
      'Connected regime insiders',
      'Remittance receivers',
      'Informal economy operators',
    ],
    whoLoses: [
      'Salaried workers in bolivars',
      'Small business owners',
      'Those without exit options',
      'Anyone visibly opposing the system',
    ],
    playbook: {
      do: [
        'Secure dollar income immediately',
        'Build exit options urgently',
        'Stay politically invisible',
        'Diversify across currencies',
        'Maintain connections abroad',
      ],
      dont: [
        'Keep savings in local currency',
        'Become politically visible',
        'Trust any institution',
        'Concentrate assets locally',
        'Display wealth publicly',
      ],
      plan30Days: [
        'Secure identification documents',
        'Open accounts for dollar reception',
        'Identify immediate exit routes',
        'Start emergency dollar reserve',
      ],
      plan12Months: [
        'Build remote income in dollars',
        'Establish foreign residence option',
        'Create offshore financial base',
        'Develop diaspora network',
      ],
      plan5Years: [
        'Relocate primary life abroad',
        'Maintain minimal Venezuela presence',
        'Build sustainable income elsewhere',
        'Help family members exit',
      ],
      planB: 'Colombia, Chile, Spain, or US for diaspora integration. Focus on legal status and remote work capabilities.',
    },
    snapshot: {
      gdpPerCapita: 3970,
      population: 28000000,
      passportRank: 91,
      corruptionIndex: 14,
      freedomIndex: 14,
    },
    visa: {
      workVisa: 'easy',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 5,
      notes: 'Easy entry but extreme country risk; most focus on emigrating',
    },
    costOfLiving: {
      index: 32,
      rentIndex: 8,
      groceriesIndex: 28,
      monthlyBudgetSingle: 400,
      monthlyBudgetFamily: 1000,
    },
    qualityOfLife: {
      healthcareRank: 176,
      educationIndex: 0.60,
      safetyIndex: 18,
      environmentIndex: 42,
      workLifeBalance: 4,
      internetSpeed: 15,
    },
    lgbtqRights: {
      index: 42,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Not criminalized but no protections; safety concerns due to general instability',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  // ============== More HYBRID_TRANSITION Countries ==============
  {
    id: 'india',
    name: 'India',
    nameLocal: 'भारत',
    iso2: 'IN',
    region: 'South Asia',
    pyramidType: 'HYBRID_TRANSITION',
    ruleOfGold: 'Navigate caste, connections, and rapid change. Build across formal and informal simultaneously.',
    pyramid: {
      top: 'Political-business nexus and traditional elites',
      institutions: 'Democratic but complex bureaucracy',
      gatekeepers: 'Caste networks, political connections, bureaucratic gatekeepers',
      valueCreators: 'Tech entrepreneurs, professionals, and small business owners',
      base: 'Massive informal workforce',
      realAsset: 'Jugaad (creative problem-solving) and network capital',
    },
    risks: {
      legal: 50,
      safety: 55,
      corruption: 60,
      volatility: 50,
      bureaucracy: 75,
    },
    whoWins: [
      'Tech sector entrepreneurs',
      'Those with strong caste/community networks',
      'Adaptable problem-solvers',
      'English-fluent professionals with global exposure',
    ],
    whoLoses: [
      'Those from marginalized communities',
      'Those expecting straightforward systems',
      'Small players without connections',
      'Women in traditional sectors',
    ],
    playbook: {
      do: [
        'Build strong community networks',
        'Develop tech and English skills',
        'Navigate both formal and informal systems',
        'Create international connections',
        'Stay adaptable to policy changes',
      ],
      dont: [
        'Ignore the importance of relationships',
        'Expect pure meritocracy',
        'Underestimate bureaucratic requirements',
        'Put all eggs in one sector',
        'Ignore regional variations',
      ],
      plan30Days: [
        'Map your network and community resources',
        'Assess your sector regulatory environment',
        'Identify skill gaps for global competitiveness',
        'Start emergency fund',
      ],
      plan12Months: [
        'Build transferable tech skills',
        'Establish income diversification',
        'Create international professional network',
        'Develop formal documentation',
      ],
      plan5Years: [
        'Achieve financial independence',
        'Build international options',
        'Create passive income streams',
        'Consider residence alternatives',
      ],
      planB: 'UAE/Singapore for regional options, US/Canada/UK for diaspora integration, Europe for quality of life. Strong IT skills are your passport.',
    },
    snapshot: {
      gdpPerCapita: 2410,
      population: 1428000000,
      passportRank: 80,
      corruptionIndex: 40,
      freedomIndex: 66,
    },
    visa: {
      workVisa: 'easy',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 150000,
      citizenshipYears: 12,
      notes: 'Long path to citizenship; OCI card available for persons of Indian origin',
    },
    costOfLiving: {
      index: 24,
      rentIndex: 8,
      groceriesIndex: 28,
      monthlyBudgetSingle: 500,
      monthlyBudgetFamily: 1200,
    },
    qualityOfLife: {
      healthcareRank: 112,
      educationIndex: 0.57,
      safetyIndex: 45,
      environmentIndex: 41,
      workLifeBalance: 5,
      internetSpeed: 75,
    },
    lgbtqRights: {
      index: 35,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Decriminalized in 2018 but no legal protections; varies significantly by region',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'turkey',
    name: 'Turkey',
    nameLocal: 'Türkiye',
    iso2: 'TR',
    region: 'Middle East',
    pyramidType: 'HYBRID_TRANSITION',
    ruleOfGold: 'Political winds shift constantly. Build across borders and stay adaptable.',
    pyramid: {
      top: 'Political leadership and connected business elite',
      institutions: 'State apparatus between secular and religious tensions',
      gatekeepers: 'Political connections, business networks, regional power brokers',
      valueCreators: 'Entrepreneurs navigating between systems',
      base: 'Population caught between modernization and tradition',
      realAsset: 'Adaptability and multi-directional connections',
    },
    risks: {
      legal: 55,
      safety: 50,
      corruption: 55,
      volatility: 70,
      bureaucracy: 60,
    },
    whoWins: [
      'Those reading political signals accurately',
      'Exporters and euro/dollar earners',
      'Connected business operators',
      'Adaptable entrepreneurs',
    ],
    whoLoses: [
      'Politically outspoken individuals',
      'Those dependent on lira income',
      'Journalists and activists',
      'Those expecting stable rules',
    ],
    playbook: {
      do: [
        'Earn in hard currency when possible',
        'Stay politically neutral publicly',
        'Build European and Middle Eastern connections',
        'Diversify income geographically',
        'Keep exit options open',
      ],
      dont: [
        'Criticize leadership publicly',
        'Concentrate assets in lira',
        'Ignore political shifts',
        'Depend on single market',
        'Underestimate economic volatility',
      ],
      plan30Days: [
        'Assess political exposure',
        'Open foreign currency accounts',
        'Evaluate export/remote income options',
        'Secure travel documents',
      ],
      plan12Months: [
        'Build hard currency income stream',
        'Establish EU connections',
        'Create offshore financial base',
        'Develop portable skills',
      ],
      plan5Years: [
        'Secure residence option abroad',
        'Diversify assets internationally',
        'Build sustainable income elsewhere',
        'Create family exit options',
      ],
      planB: 'Germany for established diaspora, UK/Netherlands for business, UAE for regional base. Turkish passport gives good visa-free access.',
    },
    snapshot: {
      gdpPerCapita: 10650,
      population: 85000000,
      passportRank: 50,
      corruptionIndex: 36,
      freedomIndex: 32,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 400000,
      citizenshipYears: 5,
      notes: 'Citizenship by investment available; relatively open to foreigners in key sectors',
    },
    costOfLiving: {
      index: 34,
      rentIndex: 15,
      groceriesIndex: 38,
      monthlyBudgetSingle: 700,
      monthlyBudgetFamily: 1800,
    },
    qualityOfLife: {
      healthcareRank: 51,
      educationIndex: 0.72,
      safetyIndex: 52,
      environmentIndex: 58,
      workLifeBalance: 6,
      internetSpeed: 45,
    },
    lgbtqRights: {
      index: 28,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Not criminalized but increasing social hostility; Pride events banned in major cities',
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
];

export function getCountryById(id: string): Country | undefined {
  return countries.find(country => country.id === id);
}
