import { Country } from './types';

export const countries: Country[] = [
  {
    id: 'cameroon',
    name: 'Cameroon',
    nameLocal: 'Cameroun',
    iso2: 'CM',
    region: 'Central Africa',
    pyramidType: 'PROBLEM_RENT',
    ruleOfGold: 'Never solve a visible problem. Never become indispensable. Never centralize.',
    pyramid: {
      top: 'Political elites and connected networks',
      institutions: 'State apparatus serving private interests',
      gatekeepers: 'Bureaucrats, middlemen, and informal brokers',
      valueCreators: 'Entrepreneurs, farmers, and informal workers',
      base: 'General population financing the system',
      realAsset: 'The problem itself — dysfunction is profitable',
    },
    risks: {
      legal: 75,
      safety: 65,
      corruption: 85,
      volatility: 60,
      bureaucracy: 80,
    },
    whoWins: [
      'Connected insiders with political access',
      'Gatekeepers who control bottlenecks',
      'Those who monetize dysfunction',
      'International actors extracting resources',
    ],
    whoLoses: [
      'Competent people without connections',
      'Transparent entrepreneurs',
      'Anyone who solves problems publicly',
      'The young and ambitious without networks',
    ],
    playbook: {
      do: [
        'Stay invisible, build quietly',
        'Diversify income streams',
        'Build exportable skills',
        'Create offshore options progressively',
        'Network with diaspora',
      ],
      dont: [
        'Publicly solve systemic problems',
        'Become visibly successful without protection',
        'Centralize assets or power',
        'Trust formal institutions blindly',
        'Moralize or criticize openly',
      ],
      plan30Days: [
        'Secure documents and identity papers',
        'Start emergency fund (even small)',
        'Identify one exportable skill to develop',
        'Map your current network value',
      ],
      plan12Months: [
        'Develop secondary income source',
        'Build international connections',
        'Learn remote-work skills',
        'Create first offshore account if possible',
      ],
      plan5Years: [
        'Establish residence option abroad',
        'Diversify assets geographically',
        'Build reputation in international network',
        'Create passive income streams',
      ],
      planB: 'Focus on French-speaking destinations with easier visa access (Morocco, Senegal, France, Canada-Quebec). Build digital skills for remote work.',
    },
    snapshot: {
      gdpPerCapita: 1660,
      population: 28000000,
      passportRank: 91,
      corruptionIndex: 26,
      freedomIndex: 25,
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index'],
  },
  {
    id: 'france',
    name: 'France',
    nameLocal: 'France',
    iso2: 'FR',
    region: 'Western Europe',
    pyramidType: 'STABILITY_REDIS',
    ruleOfGold: 'The system protects stability, not explosion. Play the long game within the rules.',
    pyramid: {
      top: 'State institutions and social model',
      institutions: 'Heavy bureaucracy ensuring redistribution',
      gatekeepers: 'Diplomas, certifications, and procedures',
      valueCreators: 'Workers, entrepreneurs (constrained)',
      base: 'Taxpayers funding the social contract',
      realAsset: 'Stability and predictability',
    },
    risks: {
      legal: 20,
      safety: 25,
      corruption: 30,
      volatility: 25,
      bureaucracy: 75,
    },
    whoWins: [
      'Those who master the system rules',
      'Public sector employees',
      'Those with right diplomas and networks',
      'Patient long-term planners',
    ],
    whoLoses: [
      'High ambition, low patience profiles',
      'Outsiders without French credentials',
      'Those seeking explosive growth',
      'Non-conformists and innovators',
    ],
    playbook: {
      do: [
        'Understand and use the system',
        'Optimize tax structure legally',
        'Build multiple income streams',
        'Develop international options',
        'Invest in quality of life',
      ],
      dont: [
        'Depend on single income source',
        'Ignore administrative requirements',
        'Expect meritocracy alone to win',
        'Burn bridges with institutions',
        'Underestimate bureaucracy time',
      ],
      plan30Days: [
        'Audit your current situation',
        'Understand your tax bracket',
        'Start automation savings',
        'Research side income options',
      ],
      plan12Months: [
        'Establish secondary revenue',
        'Optimize your legal structure',
        'Build transferable certifications',
        'Create international portfolio',
      ],
      plan5Years: [
        'Geographic diversification',
        'Build location-independent income',
        'Establish EU alternatives',
        'Create wealth outside system reach',
      ],
      planB: 'EU mobility is your advantage. Consider Portugal, Spain, or Netherlands for lower friction. Switzerland for higher ambition. Keep French benefits while building elsewhere.',
    },
    snapshot: {
      gdpPerCapita: 44850,
      population: 68000000,
      passportRank: 4,
      corruptionIndex: 71,
      freedomIndex: 89,
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index'],
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    nameLocal: 'Schweiz / Suisse',
    iso2: 'CH',
    region: 'Western Europe',
    pyramidType: 'COMPETENCE_TRUST',
    ruleOfGold: 'Excellence + rules + reputation = security. No shortcuts, no approximations.',
    pyramid: {
      top: 'Trust, precision, and institutional reliability',
      institutions: 'Efficient, rule-based governance',
      gatekeepers: 'Quality standards and professional requirements',
      valueCreators: 'Highly skilled workers and entrepreneurs',
      base: 'Citizens invested in maintaining the system',
      realAsset: 'Competence and collective trust',
    },
    risks: {
      legal: 10,
      safety: 5,
      corruption: 15,
      volatility: 10,
      bureaucracy: 40,
    },
    whoWins: [
      'Highly competent specialists',
      'Rule-followers with excellence',
      'Long-term reputation builders',
      'Those who value precision',
    ],
    whoLoses: [
      'Approximators and shortcuts-takers',
      'Impatient disruptors',
      'Those without recognized credentials',
      'Cultural outsiders unwilling to adapt',
    ],
    playbook: {
      do: [
        'Master your craft to excellence',
        'Follow rules precisely',
        'Build reputation over time',
        'Integrate culturally',
        'Invest in certifications',
      ],
      dont: [
        'Take shortcuts ever',
        'Cheat or bend rules',
        'Oversell or exaggerate',
        'Ignore local norms',
        'Rush integration process',
      ],
      plan30Days: [
        'Research credential recognition',
        'Understand local professional standards',
        'Start language learning seriously',
        'Map integration requirements',
      ],
      plan12Months: [
        'Achieve required certifications',
        'Build professional network locally',
        'Demonstrate consistent performance',
        'Establish financial stability',
      ],
      plan5Years: [
        'Achieve permanent residence/citizenship',
        'Become reference in your field',
        'Build long-term wealth',
        'Integrate fully while keeping options',
      ],
      planB: 'Other COMPETENCE_TRUST systems: Germany, Netherlands, Austria, Singapore. Build credentials that transfer across these systems.',
    },
    snapshot: {
      gdpPerCapita: 93260,
      population: 8800000,
      passportRank: 2,
      corruptionIndex: 82,
      freedomIndex: 96,
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index'],
  },
  {
    id: 'usa',
    name: 'United States',
    nameLocal: 'United States',
    iso2: 'US',
    region: 'North America',
    pyramidType: 'GROWTH_RISK',
    ruleOfGold: 'Win fast, secure gains, diversify. The system rewards velocity, not stability.',
    pyramid: {
      top: 'Capital and growth potential',
      institutions: 'Markets and opportunity structures',
      gatekeepers: 'Access to capital and networks',
      valueCreators: 'Entrepreneurs and high performers',
      base: 'Workers in competitive environment',
      realAsset: 'Growth and scalability',
    },
    risks: {
      legal: 25,
      safety: 35,
      corruption: 33,
      volatility: 45,
      bureaucracy: 35,
    },
    whoWins: [
      'High-velocity entrepreneurs',
      'Those with capital access',
      'Scalable skill owners',
      'Network builders',
    ],
    whoLoses: [
      'Stability-seekers',
      'Those relying on social safety net',
      'Slow-and-steady types',
      'Those without health/wealth buffer',
    ],
    playbook: {
      do: [
        'Move fast and scale',
        'Build multiple income streams',
        'Secure private safety nets',
        'Network aggressively',
        'Diversify geographically',
      ],
      dont: [
        'Rely on social systems',
        'Stay in one income stream',
        'Ignore health insurance',
        'Burn out without exit plan',
        'Assume stability exists',
      ],
      plan30Days: [
        'Secure health coverage',
        'Start emergency fund',
        'Identify growth opportunities',
        'Map your network value',
      ],
      plan12Months: [
        'Build scalable income',
        'Create investment strategy',
        'Establish professional reputation',
        'Build safety buffers',
      ],
      plan5Years: [
        'Achieve financial independence',
        'Diversify internationally',
        'Build passive income',
        'Create exit options',
      ],
      planB: 'Consider Canada for stability with growth, Portugal for EU access, Dubai for tax optimization. Keep US income while building options.',
    },
    snapshot: {
      gdpPerCapita: 76330,
      population: 335000000,
      passportRank: 8,
      corruptionIndex: 69,
      freedomIndex: 83,
    },
    lastUpdated: '2024-12-15',
    sources: ['World Bank', 'Transparency International', 'Freedom House', 'Henley Passport Index'],
  },
];

export const getCountryById = (id: string): Country | undefined => {
  return countries.find((c) => c.id === id);
};

export const getCountriesByType = (type: Country['pyramidType']): Country[] => {
  return countries.filter((c) => c.pyramidType === type);
};
