import type { Country, PyramidType } from './types';

/**
 * Expansion de 16 pays supplémentaires pour atteindre 60 pays
 * Régions couvertes : Asie du Sud-Est, Amérique latine, Afrique
 * Types de pyramides : PROBLEM_RENT, STABILITY_REDIS, COMPETENCE_TRUST, GROWTH_RISK, HYBRID_TRANSITION, RESOURCE_EXTRACTION
 */
export const expansionCountries: Country[] = [
  // ============================================================
  // ASIE DU SUD-EST & ASIE DU SUD
  // ============================================================
  {
    id: 'cambodia',
    name: 'Cambodia',
    nameLocal: 'កម្ពុជា (Cambodge)',
    iso2: 'KH',
    region: 'Asie du Sud-Est',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Construisez en silence, payez les bons intermédiaires, ne défiez jamais le pouvoir en place.',
    pyramid: {
      top: 'Parti au pouvoir et élites militaro-économiques connectées',
      institutions: 'Appareil étatique au service des intérêts du parti',
      gatekeepers: 'Fonctionnaires locaux, militaires, hommes d\'affaires connectés',
      valueCreators: 'Entrepreneurs étrangers, travailleurs du textile, agriculteurs',
      base: 'Population rurale et travailleurs informels',
      realAsset: 'La terre et l\'accès aux concessions foncières',
    },
    risks: {
      legal: 70,
      safety: 55,
      corruption: 80,
      volatility: 50,
      bureaucracy: 70,
    },
    whoWins: [
      'Investisseurs avec des connexions politiques locales',
      'Entrepreneurs étrangers dans le tourisme et l\'immobilier',
      'Ceux qui comprennent l\'économie informelle',
      'Les intermédiaires et fixeurs bien placés',
    ],
    whoLoses: [
      'Ceux qui défient le pouvoir politique',
      'Les investisseurs naïfs sans partenaire local',
      'Les militants des droits fonciers',
      'Les travailleurs sans protection syndicale',
    ],
    playbook: {
      do: [
        'Trouver un partenaire local de confiance avant tout investissement',
        'Commencer par Phnom Penh ou Siem Reap',
        'Apprendre les bases du khmer — avantage énorme',
        'Construire des relations avant de parler affaires',
        'Rester discret sur vos revenus et projets',
      ],
      dont: [
        'Critiquer le gouvernement ou la famille royale publiquement',
        'Acheter un terrain sans vérification juridique approfondie',
        'Ignorer les dynamiques de pouvoir locales',
        'Afficher sa richesse ostensiblement',
        'Sous-estimer la complexité foncière',
      ],
      plan30Days: [
        'Obtenir un visa touriste ou e-visa',
        'Explorer Phnom Penh et Siem Reap',
        'Rejoindre les communautés d\'expatriés',
        'Comprendre le coût de la vie sur place',
      ],
      plan12Months: [
        'Obtenir un visa business ou de travail',
        'Établir des partenariats locaux solides',
        'Ouvrir un compte bancaire local',
        'Développer un réseau professionnel cambodgien',
      ],
      plan5Years: [
        'Consolider les investissements immobiliers (via structure locale)',
        'Diversifier les activités dans la région ASEAN',
        'Construire une réputation locale durable',
        'Explorer la résidence permanente',
      ],
      planB: 'La Thaïlande ou le Vietnam comme alternatives avec des écosystèmes plus matures. Le Laos pour un environnement similaire mais plus calme.',
    },
    snapshot: {
      gdpPerCapita: 1760,
      population: 17000000,
      passportRank: 90,
      corruptionIndex: 23,
      freedomIndex: 24,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 7,
      notes: 'Visa business facilement renouvelable. Pas de visa nomade digital officiel mais tolérance de fait. Investissement immobilier possible via des structures locales.',
    },
    costOfLiving: {
      index: 30,
      rentIndex: 10,
      groceriesIndex: 25,
      monthlyBudgetSingle: 600,
      monthlyBudgetFamily: 1400,
    },
    qualityOfLife: {
      healthcareRank: 160,
      educationIndex: 0.46,
      safetyIndex: 55,
      environmentIndex: 38,
      workLifeBalance: 5,
      internetSpeed: 30,
    },
    lgbtqRights: {
      index: 40,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Pas de criminalisation mais pas de protections légales. Tolérance sociale variable.',
    },
    positivePoints: {
      lifestyle: ['Coût de la vie très bas', 'Climat tropical toute l\'année', 'Nourriture délicieuse et abordable', 'Communauté expatriée dynamique'],
      economy: ['Dollar américain largement utilisé', 'Économie en croissance rapide', 'Secteur touristique florissant', 'Hub émergent pour les startups'],
      culture: ['Temples d\'Angkor — patrimoine mondial', 'Peuple accueillant et souriant', 'Riche héritage culturel khmer', 'Scène artistique en renaissance'],
      infrastructure: ['Internet fibre en expansion', 'Aéroports modernes', 'Couverture mobile 4G étendue'],
      opportunities: ['Tourisme en pleine croissance', 'Immobilier abordable', 'Marché ASEAN accessible', 'Enseignement de l\'anglais'],
      nature: ['Temples d\'Angkor', 'Plages de Sihanoukville et Koh Rong', 'Tonlé Sap — plus grand lac d\'Asie du Sud-Est', 'Forêts tropicales'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'none',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'low',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Inondations fréquentes pendant la mousson (juin-octobre). Sécheresses occasionnelles. Chaleur intense d\'avril à mai.',
    },
    healthcare: {
      systemType: 'limited',
      qualityScore: 30,
      accessScore: 25,
      emergencyResponse: 'poor',
      specialistAccess: 'poor',
      chronicCareQuality: 'poor',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Infrastructure médicale très limitée. Cliniques privées à Phnom Penh de qualité acceptable. Évacuation vers Bangkok recommandée pour les cas graves.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'philippines',
    name: 'Philippines',
    nameLocal: 'Pilipinas',
    iso2: 'PH',
    region: 'Asie du Sud-Est',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Les familles puissantes contrôlent tout. Trouvez le bon patron, ou devenez indispensable.',
    pyramid: {
      top: 'Dynasties politiques et oligarques familiaux',
      institutions: 'Démocratie formelle dominée par les clans familiaux',
      gatekeepers: 'Politiciens locaux, maires, intermédiaires familiaux',
      valueCreators: 'Travailleurs OFW à l\'étranger, BPO, entrepreneurs',
      base: 'Masse populaire dépendante du patronage',
      realAsset: 'Les réseaux familiaux et le patronage politique',
    },
    risks: {
      legal: 55,
      safety: 55,
      corruption: 65,
      volatility: 45,
      bureaucracy: 60,
    },
    whoWins: [
      'Les entreprises BPO et d\'externalisation',
      'Les investisseurs dans l\'immobilier avec partenaires locaux',
      'Ceux qui maîtrisent les réseaux familiaux',
      'Les entrepreneurs digitaux anglophones',
    ],
    whoLoses: [
      'Les investisseurs étrangers sans connexions locales',
      'Ceux qui ignorent la culture du patronage',
      'Les critiques ouverts du pouvoir en place',
      'Les entrepreneurs qui sous-estiment la bureaucratie',
    ],
    playbook: {
      do: [
        'Profiter de l\'anglais courant — avantage majeur',
        'Commencer par Manille, Cebu ou Davao',
        'Construire des relations personnelles avant les affaires',
        'Explorer le secteur BPO et tech',
        'Respecter les dynamiques familiales et religieuses',
      ],
      dont: [
        'Ignorer le rôle central de la famille dans la société',
        'Sous-estimer les typhons et risques naturels',
        'Investir dans l\'immobilier sans partenaire philippin (limite 40% étranger)',
        'Critiquer la religion catholique publiquement',
        'Négliger la sécurité dans certaines régions (Mindanao)',
      ],
      plan30Days: [
        'Obtenir un visa touriste de 30 jours (sans visa pour beaucoup)',
        'Explorer Manille et Cebu',
        'Rejoindre les communautés d\'expatriés et nomades',
        'Évaluer les opportunités dans le BPO/tech',
      ],
      plan12Months: [
        'Obtenir un visa spécial pour retraité ou investisseur (SRRV)',
        'Établir une entreprise locale avec partenaire philippin',
        'Construire un réseau professionnel solide',
        'Apprendre les bases du tagalog',
      ],
      plan5Years: [
        'Consolider les investissements via des structures locales',
        'Explorer la résidence permanente',
        'Diversifier dans la région ASEAN',
        'Développer des revenus passifs locaux',
      ],
      planB: 'La Malaisie ou la Thaïlande comme alternatives. L\'Indonésie pour un marché plus vaste.',
    },
    snapshot: {
      gdpPerCapita: 3460,
      population: 115000000,
      passportRank: 76,
      corruptionIndex: 34,
      freedomIndex: 56,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 75000,
      citizenshipYears: 10,
      notes: 'Visa SRRV populaire pour les retraités. Restriction de propriété étrangère à 40%. Zone économique spéciale pour investisseurs.',
    },
    costOfLiving: {
      index: 33,
      rentIndex: 12,
      groceriesIndex: 30,
      monthlyBudgetSingle: 700,
      monthlyBudgetFamily: 1600,
    },
    qualityOfLife: {
      healthcareRank: 83,
      educationIndex: 0.66,
      safetyIndex: 48,
      environmentIndex: 40,
      workLifeBalance: 5,
      internetSpeed: 45,
    },
    lgbtqRights: {
      index: 45,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Pas de criminalisation. Culture relativement tolérante malgré l\'influence catholique. Pas de protections légales formelles.',
    },
    positivePoints: {
      lifestyle: ['Anglais largement parlé', 'Peuple extrêmement accueillant', 'Coût de la vie très bas', 'Vie nocturne animée'],
      economy: ['Hub mondial du BPO', 'Main-d\'oeuvre anglophone qualifiée', 'Croissance économique soutenue', 'Remises des travailleurs à l\'étranger'],
      culture: ['Hospitalité légendaire (Bayanihan)', 'Fêtes et festivals colorés', 'Mélange unique asiatique-hispanique', 'Cuisine riche et variée'],
      infrastructure: ['Aéroports en expansion', 'Couverture mobile étendue', 'Internet en amélioration rapide'],
      opportunities: ['BPO et services numériques', 'Tourisme en croissance', 'Enseignement de l\'anglais', 'E-commerce'],
      nature: ['7641 îles paradisiaques', 'Rizières de Banaue', 'Plages de Palawan et Boracay', 'Spots de plongée de classe mondiale'],
    },
    naturalRisks: {
      seismicRisk: 'high',
      tsunamiRisk: 'high',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'high',
      volcanoRisk: 'high',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Pays le plus exposé aux typhons au monde (20+/an). Risque sismique élevé (ceinture de feu). Volcans actifs (Taal, Mayon). Inondations fréquentes.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 55,
      accessScore: 50,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Bons hôpitaux privés à Manille et Cebu. PhilHealth couvre les résidents. Tourisme médical en développement. Qualité variable hors grandes villes.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    nameLocal: 'ශ්‍රී ලංකාව / இலங்கை',
    iso2: 'LK',
    region: 'Asie du Sud',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Pays en reconstruction après la crise. Opportunités pour les patients, risques pour les pressés.',
    pyramid: {
      top: 'Élites politiques et familles dirigeantes historiques',
      institutions: 'État en reconstruction post-crise économique 2022',
      gatekeepers: 'Bureaucratie coloniale héritée, réseaux ethniques',
      valueCreators: 'Diaspora, entrepreneurs du thé et du textile, tech émergente',
      base: 'Population rurale et travailleurs du secteur informel',
      realAsset: 'Position stratégique dans l\'océan Indien et capital humain éduqué',
    },
    risks: {
      legal: 50,
      safety: 40,
      corruption: 55,
      volatility: 70,
      bureaucracy: 60,
    },
    whoWins: [
      'Les investisseurs patients qui entrent pendant la reconstruction',
      'Les entrepreneurs du tourisme de luxe',
      'La diaspora qui revient avec des capitaux',
      'Les entreprises tech exploitant le talent local',
    ],
    whoLoses: [
      'Ceux qui investissent sans comprendre l\'instabilité politique',
      'Les investisseurs à court terme',
      'Ceux qui ignorent les tensions ethniques résiduelles',
      'Les entreprises dépendantes de l\'importation (contrôle des changes)',
    ],
    playbook: {
      do: [
        'Étudier la situation politique et économique actuelle en profondeur',
        'Commencer par Colombo pour les affaires',
        'Explorer le tourisme haut de gamme comme secteur porteur',
        'Profiter du niveau d\'éducation élevé de la population',
        'Construire des relations avec la diaspora sri-lankaise',
      ],
      dont: [
        'Ignorer l\'histoire du conflit ethnique',
        'Investir massivement avant stabilisation complète',
        'Sous-estimer les contrôles de change',
        'Négliger les sensibilités religieuses et ethniques',
        'Compter sur des retours rapides',
      ],
      plan30Days: [
        'Obtenir l\'ETA (Electronic Travel Authorization)',
        'Explorer Colombo et la côte sud',
        'Évaluer les opportunités post-crise',
        'Rencontrer la communauté d\'affaires locale',
      ],
      plan12Months: [
        'Obtenir un visa de résidence ou business',
        'Établir des partenariats avec des entreprises locales',
        'Ouvrir un compte bancaire (si stabilisation des changes)',
        'Développer un projet pilote dans le tourisme ou la tech',
      ],
      plan5Years: [
        'Consolider les investissements à mesure que l\'économie se stabilise',
        'Développer des activités d\'exportation',
        'Explorer la résidence permanente',
        'Diversifier entre Sri Lanka et Inde du Sud',
      ],
      planB: 'L\'Inde du Sud (Kerala, Tamil Nadu) comme alternative culturellement proche. Les Maldives pour le tourisme de luxe.',
    },
    snapshot: {
      gdpPerCapita: 3350,
      population: 22000000,
      passportRank: 100,
      corruptionIndex: 36,
      freedomIndex: 55,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 7,
      notes: 'ETA pour le tourisme. Visa business disponible. Marché en reconstruction post-crise 2022. Contrôles de change en vigueur.',
    },
    costOfLiving: {
      index: 28,
      rentIndex: 8,
      groceriesIndex: 24,
      monthlyBudgetSingle: 550,
      monthlyBudgetFamily: 1300,
    },
    qualityOfLife: {
      healthcareRank: 76,
      educationIndex: 0.78,
      safetyIndex: 60,
      environmentIndex: 52,
      workLifeBalance: 6,
      internetSpeed: 25,
    },
    lgbtqRights: {
      index: 20,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexualité encore criminalisée (héritage colonial). Application rare mais stigmate social important.',
    },
    positivePoints: {
      lifestyle: ['Île magnifique avec diversité de paysages', 'Cuisine savoureuse et épicée', 'Coût de la vie très bas', 'Population éduquée et accueillante'],
      economy: ['Main-d\'oeuvre qualifiée et éduquée', 'Secteur tech en émergence', 'Thé de Ceylan — marque mondiale', 'Opportunités post-crise'],
      culture: ['2500 ans d\'histoire', 'Sites UNESCO (Sigiriya, Polonnaruwa)', 'Diversité religieuse (bouddhisme, hindouisme)', 'Ayurveda et bien-être traditionnel'],
      infrastructure: ['Bon réseau routier pour la région', 'Port de Colombo stratégique', 'Aéroport international moderne'],
      opportunities: ['Tourisme de luxe en reprise', 'Tech et BPO', 'Thé et agriculture', 'Position stratégique océan Indien'],
      nature: ['Plages tropicales', 'Montagnes du thé (Ella, Nuwara Eliya)', 'Parcs nationaux (léopards, éléphants)', 'Récifs coralliens'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'moderate',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'moderate',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Risque de tsunami (mémoire de 2004). Mousson et inondations fréquentes. Cyclones occasionnels. Chaleur tropicale constante.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 60,
      accessScore: 55,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Système de santé public gratuit mais surchargé. Hôpitaux privés de bonne qualité à Colombo. Médecine ayurvédique traditionnelle populaire.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'nepal',
    name: 'Nepal',
    nameLocal: 'नेपाल',
    iso2: 'NP',
    region: 'Asie du Sud',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Jeune république fédérale en transition. Patience et humilité sont les clés.',
    pyramid: {
      top: 'Partis politiques et élites traditionnelles (castes supérieures)',
      institutions: 'État fédéral jeune, bureaucratie héritée de la monarchie',
      gatekeepers: 'Bureaucrates, leaders de partis, intermédiaires de castes',
      valueCreators: 'Travailleurs migrants, entrepreneurs du tourisme, agriculteurs',
      base: 'Population rurale, castes marginalisées',
      realAsset: 'Les remises des travailleurs à l\'étranger (25% du PIB)',
    },
    risks: {
      legal: 55,
      safety: 45,
      corruption: 65,
      volatility: 55,
      bureaucracy: 70,
    },
    whoWins: [
      'Les entrepreneurs du tourisme et du trekking',
      'Les organisations internationales et ONG',
      'Les intermédiaires dans l\'hydroélectricité',
      'Ceux qui comprennent les dynamiques de castes',
    ],
    whoLoses: [
      'Les investisseurs cherchant des retours rapides',
      'Ceux qui ignorent la bureaucratie lourde',
      'Les outsiders sans connexions politiques',
      'Les jeunes talents qui émigrent massivement',
    ],
    playbook: {
      do: [
        'Explorer le tourisme d\'aventure comme secteur clé',
        'Comprendre le système de castes et ses implications',
        'Commencer par Katmandou et Pokhara',
        'Construire des relations avec les communautés locales',
        'S\'intéresser à l\'hydroélectricité — potentiel énorme',
      ],
      dont: [
        'Sous-estimer la complexité politique',
        'Ignorer les sensibilités culturelles et religieuses',
        'Investir sans comprendre la bureaucratie fédérale',
        'Négliger les risques sismiques',
        'Compter sur les infrastructures modernes',
      ],
      plan30Days: [
        'Obtenir un visa à l\'arrivée',
        'Explorer Katmandou et la vallée',
        'Rencontrer les communautés d\'expatriés et d\'ONG',
        'Évaluer les opportunités dans le tourisme',
      ],
      plan12Months: [
        'Obtenir un visa business ou de travail',
        'Établir des partenariats avec des opérateurs locaux',
        'Apprendre les bases du népali',
        'Développer un projet pilote',
      ],
      plan5Years: [
        'Consolider une présence dans le tourisme ou l\'énergie',
        'Explorer les opportunités dans l\'éducation',
        'Construire un réseau régional (Inde, Tibet)',
        'Envisager la résidence à long terme',
      ],
      planB: 'L\'Inde du Nord comme alternative plus développée. Le Bhoutan pour un environnement similaire mais plus régulé.',
    },
    snapshot: {
      gdpPerCapita: 1340,
      population: 30000000,
      passportRank: 104,
      corruptionIndex: 34,
      freedomIndex: 56,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 15,
      notes: 'Visa à l\'arrivée pour la plupart des nationalités. Processus bureaucratique lent. Citoyenneté très difficile à obtenir.',
    },
    costOfLiving: {
      index: 24,
      rentIndex: 6,
      groceriesIndex: 22,
      monthlyBudgetSingle: 450,
      monthlyBudgetFamily: 1100,
    },
    qualityOfLife: {
      healthcareRank: 148,
      educationIndex: 0.52,
      safetyIndex: 62,
      environmentIndex: 45,
      workLifeBalance: 5,
      internetSpeed: 18,
    },
    lgbtqRights: {
      index: 38,
      sameSecMarriage: true,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Mariage homosexuel reconnu par la Cour suprême en 2023. Progressiste pour la région mais acceptation sociale encore limitée.',
    },
    positivePoints: {
      lifestyle: ['Coût de la vie extrêmement bas', 'Cadre himalayen spectaculaire', 'Rythme de vie paisible', 'Spiritualité omniprésente'],
      economy: ['Tourisme d\'aventure en croissance', 'Potentiel hydroélectrique immense', 'Main-d\'oeuvre jeune', 'Position entre Inde et Chine'],
      culture: ['Berceau de Bouddha (Lumbini)', 'Richesse culturelle néwar', 'Festivals hindous et bouddhistes', 'Artisanat traditionnel'],
      infrastructure: ['Nouvel aéroport de Pokhara', 'Réseau mobile en expansion', 'Routes en amélioration'],
      opportunities: ['Trekking et tourisme d\'aventure', 'Hydroélectricité', 'Artisanat d\'exportation', 'ONG et développement'],
      nature: ['8 des 14 sommets de plus de 8000m', 'Parc national de Chitwan (tigres, rhinocéros)', 'Vallées spectaculaires', 'Biodiversité exceptionnelle'],
    },
    naturalRisks: {
      seismicRisk: 'very_high',
      tsunamiRisk: 'none',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'none',
      extremeHeat: 'occasional',
      extremeCold: 'frequent',
      climateNotes: 'Risque sismique majeur (tremblement de terre de 2015). Glissements de terrain et inondations pendant la mousson. Froid extrême en altitude.',
    },
    healthcare: {
      systemType: 'limited',
      qualityScore: 30,
      accessScore: 20,
      emergencyResponse: 'poor',
      specialistAccess: 'poor',
      chronicCareQuality: 'poor',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Infrastructure médicale très limitée, surtout hors Katmandou. Évacuation héliportée nécessaire en montagne. Assurance avec rapatriement indispensable.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'laos',
    name: 'Laos',
    nameLocal: 'ລາວ',
    iso2: 'LA',
    region: 'Asie du Sud-Est',
    pyramidType: 'RESOURCE_EXTRACTION' as PyramidType,
    ruleOfGold: 'Le parti contrôle les ressources. Restez discret, travaillez via les bons canaux.',
    pyramid: {
      top: 'Parti révolutionnaire populaire lao et militaires',
      institutions: 'État à parti unique contrôlant les concessions',
      gatekeepers: 'Fonctionnaires du parti, investisseurs chinois, militaires',
      valueCreators: 'Agriculteurs, travailleurs des barrages, petits commerçants',
      base: 'Population rurale et ethnies minoritaires',
      realAsset: 'Hydroélectricité, minerais, terres et forêts',
    },
    risks: {
      legal: 70,
      safety: 40,
      corruption: 75,
      volatility: 55,
      bureaucracy: 75,
    },
    whoWins: [
      'Les investisseurs chinois avec des connexions au parti',
      'Les entreprises dans l\'hydroélectricité',
      'Les intermédiaires du commerce transfrontalier',
      'Ceux qui comprennent le système communiste local',
    ],
    whoLoses: [
      'Les petits investisseurs sans connexions',
      'Les populations déplacées par les barrages',
      'Les critiques du gouvernement',
      'Les entrepreneurs cherchant la transparence',
    ],
    playbook: {
      do: [
        'Comprendre l\'influence massive de la Chine',
        'Commencer par Vientiane ou Luang Prabang',
        'Travailler avec des partenaires locaux connectés au parti',
        'Explorer le tourisme durable comme niche',
        'Rester discret et patient',
      ],
      dont: [
        'Critiquer le parti ou le gouvernement',
        'Ignorer les dynamiques géopolitiques (Chine)',
        'Afficher de l\'arrogance culturelle',
        'Investir massivement sans connexions fiables',
        'Sous-estimer l\'opacité administrative',
      ],
      plan30Days: [
        'Obtenir un visa touriste ou e-visa',
        'Explorer Vientiane et Luang Prabang',
        'Comprendre le rythme de vie local',
        'Évaluer le coût de la vie sur place',
      ],
      plan12Months: [
        'Obtenir un visa business avec sponsorship local',
        'Établir des relations avec des entreprises locales',
        'Apprendre les bases du lao',
        'Développer un petit projet pilote',
      ],
      plan5Years: [
        'Consolider les partenariats locaux',
        'Explorer les opportunités liées au train Chine-Laos',
        'Diversifier dans la sous-région (Thaïlande, Vietnam)',
        'Maintenir un profil discret et stable',
      ],
      planB: 'La Thaïlande comme alternative plus ouverte et développée. Le Cambodge pour un environnement similaire.',
    },
    snapshot: {
      gdpPerCapita: 2050,
      population: 7500000,
      passportRank: 93,
      corruptionIndex: 28,
      freedomIndex: 13,
    },
    visa: {
      workVisa: 'difficult',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 10,
      notes: 'Visa touriste à l\'arrivée. Visa business nécessite un sponsor local. Pas de programme d\'investissement formel. Citoyenneté très rare pour les étrangers.',
    },
    costOfLiving: {
      index: 26,
      rentIndex: 7,
      groceriesIndex: 23,
      monthlyBudgetSingle: 500,
      monthlyBudgetFamily: 1200,
    },
    qualityOfLife: {
      healthcareRank: 165,
      educationIndex: 0.45,
      safetyIndex: 65,
      environmentIndex: 42,
      workLifeBalance: 6,
      internetSpeed: 15,
    },
    lgbtqRights: {
      index: 30,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Pas de criminalisation. Tolérance sociale mais pas de protections légales. Sujet rarement discuté.',
    },
    positivePoints: {
      lifestyle: ['Rythme de vie très détendu', 'Coût de la vie très bas', 'Paysages préservés', 'Gastronomie savoureuse'],
      economy: ['Croissance tirée par l\'hydroélectricité', 'Train à grande vitesse Chine-Laos', 'Positionnement stratégique en ASEAN'],
      culture: ['Temples bouddhistes magnifiques', 'Luang Prabang — patrimoine UNESCO', 'Culture laotienne authentique', 'Baci et traditions spirituelles'],
      infrastructure: ['Nouveau train Chine-Laos', 'Réseau mobile en expansion', 'Vientiane en modernisation'],
      opportunities: ['Tourisme durable', 'Commerce transfrontalier', 'Hydroélectricité', 'Agriculture biologique'],
      nature: ['Mékong et ses affluents', 'Grottes de Vang Vieng', 'Forêts tropicales préservées', 'Plateau des Bolovens'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'none',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'low',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Inondations majeures fréquentes liées au Mékong. Mousson intense de mai à octobre. Bombes non explosées (UXO) dans certaines régions.',
    },
    healthcare: {
      systemType: 'limited',
      qualityScore: 25,
      accessScore: 20,
      emergencyResponse: 'poor',
      specialistAccess: 'poor',
      chronicCareQuality: 'poor',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Infrastructure médicale très basique. Évacuation vers la Thaïlande (Udon Thani) nécessaire pour les cas graves. Assurance rapatriement indispensable.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'myanmar',
    name: 'Myanmar',
    nameLocal: 'မြန်မာ',
    iso2: 'MM',
    region: 'Asie du Sud-Est',
    pyramidType: 'PROBLEM_RENT' as PyramidType,
    ruleOfGold: 'Le chaos militaire est le système. Ne pas entrer sans comprendre les risques extrêmes.',
    pyramid: {
      top: 'Junte militaire (Tatmadaw) et conglomérats militaires',
      institutions: 'État en guerre civile, institutions effondrées',
      gatekeepers: 'Généraux, cronies militaires, trafiquants',
      valueCreators: 'Population en résistance, économie de survie',
      base: 'Civils pris entre les feux',
      realAsset: 'Le contrôle des ressources naturelles (jade, gaz, bois)',
    },
    risks: {
      legal: 90,
      safety: 90,
      corruption: 90,
      volatility: 95,
      bureaucracy: 85,
    },
    whoWins: [
      'Les militaires et leurs réseaux commerciaux',
      'Les trafiquants transfrontaliers',
      'Les entreprises chinoises connectées à la junte',
      'Personne de manière durable — système destructeur',
    ],
    whoLoses: [
      'La population civile tout entière',
      'Les minorités ethniques (Rohingyas, Karen, Kachin)',
      'Les investisseurs étrangers piégés',
      'Les démocrates et militants',
    ],
    playbook: {
      do: [
        'Éviter le pays dans les circonstances actuelles',
        'Suivre la situation depuis l\'extérieur',
        'Soutenir la diaspora birmane si pertinent',
        'Préparer des plans pour un éventuel retour à la stabilité',
        'Consulter les sanctions internationales en vigueur',
      ],
      dont: [
        'Investir tant que le conflit perdure',
        'Voyager dans les zones de conflit',
        'Faire des affaires avec des entités liées à la junte',
        'Ignorer les sanctions internationales',
        'Sous-estimer le danger physique',
      ],
      plan30Days: [
        'Étudier la situation sécuritaire actuelle',
        'Comprendre les sanctions en vigueur',
        'Identifier les alternatives régionales',
        'Connecter avec la diaspora birmane',
      ],
      plan12Months: [
        'Suivre l\'évolution politique',
        'Développer des compétences pertinentes pour la région',
        'Construire un réseau dans les pays voisins',
        'Préparer un plan d\'entrée conditionnel',
      ],
      plan5Years: [
        'Réévaluer si la situation se stabilise',
        'Être prêt à saisir des opportunités de reconstruction',
        'Maintenir les connexions avec la diaspora',
        'Diversifier les options en Asie du Sud-Est',
      ],
      planB: 'La Thaïlande, le Cambodge ou le Vietnam comme alternatives immédiates. Attendre la stabilisation avant tout engagement.',
    },
    snapshot: {
      gdpPerCapita: 1210,
      population: 54000000,
      passportRank: 96,
      corruptionIndex: 20,
      freedomIndex: 9,
    },
    visa: {
      workVisa: 'difficult',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: false,
      citizenshipYears: 0,
      notes: 'Voyages fortement déconseillés. Situation de guerre civile. Sanctions internationales en vigueur. Visas limités et processus imprévisible.',
    },
    costOfLiving: {
      index: 25,
      rentIndex: 8,
      groceriesIndex: 22,
      monthlyBudgetSingle: 400,
      monthlyBudgetFamily: 1000,
    },
    qualityOfLife: {
      healthcareRank: 170,
      educationIndex: 0.42,
      safetyIndex: 15,
      environmentIndex: 30,
      workLifeBalance: 3,
      internetSpeed: 12,
    },
    lgbtqRights: {
      index: 15,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexualité criminalisée. Persécution active possible. Situation extrêmement dangereuse.',
    },
    positivePoints: {
      lifestyle: ['Peuple birman d\'une gentillesse remarquable', 'Culture bouddhiste profonde', 'Cuisine unique et savoureuse'],
      economy: ['Ressources naturelles immenses (jade, gaz, bois)', 'Main-d\'oeuvre jeune', 'Potentiel de reconstruction futur'],
      culture: ['Temples de Bagan — merveille mondiale', 'Traditions bouddhistes vivantes', 'Diversité ethnique exceptionnelle', 'Artisanat traditionnel'],
      infrastructure: ['Potentiel de développement massif si stabilisation'],
      opportunities: ['Reconstruction future si paix', 'Ressources naturelles', 'Position stratégique entre Inde et Chine'],
      nature: ['Temples de Bagan', 'Lac Inle', 'Plages d\'Arakan', 'Forêts tropicales de Kachin'],
    },
    naturalRisks: {
      seismicRisk: 'high',
      tsunamiRisk: 'moderate',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'high',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Cyclones dévastateurs (Nargis 2008). Inondations de mousson fréquentes. Risque sismique significatif. Chaleur extrême dans les plaines centrales.',
    },
    healthcare: {
      systemType: 'limited',
      qualityScore: 15,
      accessScore: 10,
      emergencyResponse: 'poor',
      specialistAccess: 'poor',
      chronicCareQuality: 'poor',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Système de santé effondré depuis le coup d\'État. Grève des médecins. Évacuation vers la Thaïlande ou Singapour indispensable. Situation humanitaire critique.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  // ============================================================
  // AMÉRIQUE LATINE
  // ============================================================
  {
    id: 'costa-rica',
    name: 'Costa Rica',
    nameLocal: 'Costa Rica',
    iso2: 'CR',
    region: 'Amérique centrale',
    pyramidType: 'COMPETENCE_TRUST' as PyramidType,
    ruleOfGold: 'La stabilité et l\'éducation sont les vrais actifs. Le système récompense la patience et le respect des règles.',
    pyramid: {
      top: 'Institutions démocratiques et élites éduquées',
      institutions: 'Démocratie stable, état social fort, pas d\'armée',
      gatekeepers: 'Bureaucratie lourde mais légitime, diplômes et certifications',
      valueCreators: 'Entrepreneurs du tourisme, tech, agriculture bio',
      base: 'Classe moyenne éduquée, travailleurs agricoles',
      realAsset: 'La stabilité politique, la biodiversité et le capital humain',
    },
    risks: {
      legal: 30,
      safety: 35,
      corruption: 40,
      volatility: 25,
      bureaucracy: 55,
    },
    whoWins: [
      'Les entrepreneurs du tourisme écologique',
      'Les retraités et nomades numériques',
      'Les entreprises tech (zones franches)',
      'Les investisseurs dans l\'immobilier côtier',
    ],
    whoLoses: [
      'Ceux qui cherchent des retours rapides',
      'Les impatients face à la bureaucratie',
      'Les investisseurs ignorant le droit du travail strict',
      'Ceux qui sous-estiment le coût de la vie (élevé pour la région)',
    ],
    playbook: {
      do: [
        'Explorer le tourisme durable et l\'écotourisme',
        'S\'installer dans la Vallée Centrale ou sur les côtes',
        'Comprendre le droit du travail très protecteur',
        'Profiter des zones franches pour la tech',
        'Apprendre l\'espagnol — essentiel',
      ],
      dont: [
        'Sous-estimer le coût de la vie (plus élevé que les voisins)',
        'Ignorer la bureaucratie — elle est réelle mais fonctionnelle',
        'Employer sans respecter le Code du Travail',
        'Négliger l\'assurance maladie (CAJA)',
        'Comparer avec le reste de l\'Amérique centrale',
      ],
      plan30Days: [
        'Entrer avec visa touriste (90 jours pour la plupart)',
        'Explorer San José, côte Pacifique et Caraïbes',
        'Rejoindre la communauté d\'expatriés',
        'Évaluer le coût de la vie réel',
      ],
      plan12Months: [
        'Demander un visa de rentista, retraité ou investisseur',
        'S\'inscrire à la CAJA (sécurité sociale)',
        'Établir un projet d\'entreprise ou de freelance',
        'Perfectionner l\'espagnol',
      ],
      plan5Years: [
        'Obtenir la résidence permanente',
        'Consolider les investissements',
        'Explorer la citoyenneté (7 ans de résidence)',
        'S\'intégrer pleinement à la communauté locale',
      ],
      planB: 'Le Panama pour un environnement plus orienté business. La Colombie pour un coût plus bas. Le Mexique pour un marché plus vaste.',
    },
    snapshot: {
      gdpPerCapita: 12500,
      population: 5200000,
      passportRank: 28,
      corruptionIndex: 54,
      freedomIndex: 91,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      investmentMinimum: 150000,
      citizenshipYears: 7,
      notes: 'Visa nomade digital disponible. Programme Rentista populaire. Résidence par investissement (150K USD). Pas d\'armée — budget alloué à l\'éducation et la santé.',
    },
    costOfLiving: {
      index: 48,
      rentIndex: 20,
      groceriesIndex: 42,
      monthlyBudgetSingle: 1200,
      monthlyBudgetFamily: 2800,
    },
    qualityOfLife: {
      healthcareRank: 36,
      educationIndex: 0.74,
      safetyIndex: 58,
      environmentIndex: 82,
      workLifeBalance: 7,
      internetSpeed: 50,
    },
    lgbtqRights: {
      index: 70,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Mariage homosexuel légal depuis 2020. Premier pays d\'Amérique centrale. Protections légales fortes.',
    },
    positivePoints: {
      lifestyle: ['Pura Vida — philosophie de vie détendue', 'Biodiversité incroyable', 'Climat tropical agréable', 'Communauté expatriée établie'],
      economy: ['Démocratie la plus stable d\'Amérique latine', 'Pas d\'armée — budget pour le social', 'Zones franches attractives', 'Économie diversifiée'],
      culture: ['Culture Pura Vida unique', 'Peuple accueillant et éduqué', 'Engagement environnemental national', 'Musique et arts vivants'],
      infrastructure: ['Bon système de santé (CAJA)', 'Aéroports internationaux', 'Internet fiable', 'Routes principales en bon état'],
      opportunities: ['Écotourisme mondial', 'Tech et services partagés', 'Énergies renouvelables (98%)', 'Agriculture bio et café'],
      nature: ['5% de la biodiversité mondiale', 'Volcans actifs', 'Plages Pacifique et Caraïbes', 'Forêts tropicales et cloud forests'],
    },
    naturalRisks: {
      seismicRisk: 'high',
      tsunamiRisk: 'moderate',
      floodRisk: 'moderate',
      droughtRisk: 'low',
      cycloneRisk: 'low',
      volcanoRisk: 'high',
      extremeHeat: 'occasional',
      extremeCold: 'rare',
      climateNotes: 'Zone sismique active. Volcans actifs (Arenal, Turrialba). Inondations pendant la saison des pluies. Climat agréable en altitude.',
    },
    healthcare: {
      systemType: 'universal',
      qualityScore: 78,
      accessScore: 75,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'low',
      insuranceRequired: false,
      notes: 'CAJA — système de santé universel de qualité. Résidents couverts. Cliniques privées abordables. Tourisme médical en développement.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'panama',
    name: 'Panama',
    nameLocal: 'Panamá',
    iso2: 'PA',
    region: 'Amérique centrale',
    pyramidType: 'GROWTH_RISK' as PyramidType,
    ruleOfGold: 'Le Canal fait tout tourner. Positionnez-vous sur les flux — commerce, finance, logistique.',
    pyramid: {
      top: 'Oligarchie commerciale et financière liée au Canal',
      institutions: 'État orienté business, hub financier, zones franches',
      gatekeepers: 'Avocats d\'affaires, banquiers, courtiers immobiliers',
      valueCreators: 'Entrepreneurs, commerçants, travailleurs de la logistique',
      base: 'Populations indigènes et travailleurs informels',
      realAsset: 'Le Canal de Panama et le statut de hub financier',
    },
    risks: {
      legal: 40,
      safety: 45,
      corruption: 55,
      volatility: 35,
      bureaucracy: 45,
    },
    whoWins: [
      'Les entrepreneurs dans la logistique et le commerce',
      'Les investisseurs immobiliers à Panama City',
      'Les retraités étrangers (programme Pensionado)',
      'Les entreprises utilisant le hub financier',
    ],
    whoLoses: [
      'Ceux qui ignorent la réglementation financière post-Panama Papers',
      'Les investisseurs dans les zones rurales sans infrastructure',
      'Les entrepreneurs sans conseil juridique local',
      'Les populations indigènes marginalisées',
    ],
    playbook: {
      do: [
        'S\'installer à Panama City pour les affaires',
        'Explorer le programme de résidence Friendly Nations',
        'Utiliser le dollar américain comme avantage (monnaie officielle)',
        'Travailler avec un avocat panaméen réputé',
        'Explorer la zone franche de Colón',
      ],
      dont: [
        'Ignorer les obligations de conformité financière',
        'Sous-estimer la chaleur et l\'humidité',
        'Investir sans due diligence juridique',
        'Négliger les taxes (même si fiscalité avantageuse)',
        'Oublier que la réputation post-Panama Papers exige plus de transparence',
      ],
      plan30Days: [
        'Entrer avec visa touriste',
        'Explorer Panama City et les zones côtières',
        'Consulter un avocat pour les options de résidence',
        'Évaluer les opportunités business',
      ],
      plan12Months: [
        'Obtenir le visa Friendly Nations ou Pensionado',
        'Ouvrir un compte bancaire (processus strict)',
        'Créer une société panaméenne si pertinent',
        'Construire un réseau professionnel local',
      ],
      plan5Years: [
        'Obtenir la résidence permanente',
        'Consolider les investissements immobiliers',
        'Explorer la citoyenneté (5 ans)',
        'Développer des activités régionales depuis le hub',
      ],
      planB: 'Le Costa Rica pour plus de stabilité sociale. La Colombie pour un coût plus bas. Miami pour un hub similaire aux USA.',
    },
    snapshot: {
      gdpPerCapita: 14600,
      population: 4400000,
      passportRank: 36,
      corruptionIndex: 36,
      freedomIndex: 83,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      investmentMinimum: 300000,
      citizenshipYears: 5,
      notes: 'Programme Friendly Nations très attractif. Visa Pensionado pour retraités. Dollar américain comme monnaie. Fiscalité territoriale avantageuse.',
    },
    costOfLiving: {
      index: 45,
      rentIndex: 22,
      groceriesIndex: 38,
      monthlyBudgetSingle: 1100,
      monthlyBudgetFamily: 2600,
    },
    qualityOfLife: {
      healthcareRank: 48,
      educationIndex: 0.67,
      safetyIndex: 52,
      environmentIndex: 58,
      workLifeBalance: 6,
      internetSpeed: 60,
    },
    lgbtqRights: {
      index: 35,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Pas de reconnaissance légale. Société conservatrice mais tolérance en milieu urbain. Pas de criminalisation.',
    },
    positivePoints: {
      lifestyle: ['Dollar américain — pas de risque de change', 'Climat tropical toute l\'année', 'Cosmopolite et international', 'Programme de retraite excellent'],
      economy: ['Hub logistique mondial (Canal)', 'Centre financier international', 'Fiscalité territoriale avantageuse', 'Zone franche de Colón'],
      culture: ['Mélange culturel unique (afro, indigène, hispanique)', 'Carnaval animé', 'Gastronomie diverse', 'Casco Viejo historique'],
      infrastructure: ['Canal de Panama', 'Métro moderne', 'Aéroport hub régional (Tocumen)', 'Gratte-ciels modernes'],
      opportunities: ['Logistique et commerce international', 'Finance et banque', 'Immobilier en croissance', 'Tourisme'],
      nature: ['Canal de Panama', 'Archipel de Bocas del Toro', 'Forêt tropicale du Darién', 'Volcán Barú'],
    },
    naturalRisks: {
      seismicRisk: 'moderate',
      tsunamiRisk: 'low',
      floodRisk: 'moderate',
      droughtRisk: 'low',
      cycloneRisk: 'none',
      volcanoRisk: 'moderate',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Hors de la ceinture des ouragans. Inondations pendant la saison des pluies. Chaleur et humidité constantes. Risque sismique modéré.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 72,
      accessScore: 65,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'moderate',
      insuranceRequired: true,
      notes: 'Bons hôpitaux privés à Panama City (Punta Pacífica affilié Johns Hopkins). CSS publique pour les cotisants. Tourisme médical en développement.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'ecuador',
    name: 'Ecuador',
    nameLocal: 'Ecuador',
    iso2: 'EC',
    region: 'Amérique du Sud',
    pyramidType: 'RESOURCE_EXTRACTION' as PyramidType,
    ruleOfGold: 'Le pétrole finance le système. Quand le prix chute, tout tremble. Diversifiez.',
    pyramid: {
      top: 'Élites pétrolières et politiques, familles de Quito et Guayaquil',
      institutions: 'État dépendant des revenus pétroliers, instabilité politique chronique',
      gatekeepers: 'Politiciens, militaires, syndicats du secteur public',
      valueCreators: 'Agriculteurs (bananes, cacao, crevettes), entrepreneurs',
      base: 'Populations indigènes et travailleurs informels',
      realAsset: 'Le pétrole et les ressources naturelles',
    },
    risks: {
      legal: 55,
      safety: 60,
      corruption: 60,
      volatility: 65,
      bureaucracy: 60,
    },
    whoWins: [
      'Les retraités étrangers (excellent rapport qualité-vie)',
      'Les exportateurs agricoles (cacao, bananes, crevettes)',
      'Les investisseurs dans le tourisme des Galápagos',
      'Ceux qui profitent du dollar américain',
    ],
    whoLoses: [
      'Les investisseurs piégés par l\'instabilité politique',
      'Les entreprises pétrolières en période de prix bas',
      'Les populations indigènes face à l\'extraction',
      'Ceux qui ne planifient pas la sécurité (narco-violence en hausse)',
    ],
    playbook: {
      do: [
        'Profiter du dollar américain comme monnaie officielle',
        'Explorer Cuenca ou Quito pour la résidence',
        'Investir dans le tourisme durable (Galápagos)',
        'Comprendre les dynamiques régionales (Sierra vs Costa)',
        'Surveiller la situation sécuritaire attentivement',
      ],
      dont: [
        'Ignorer la montée de l\'insécurité (narcotrafic)',
        'Investir dans le pétrole sans diversifier',
        'Sous-estimer l\'instabilité politique',
        'Négliger les tremblements de terre (zone sismique)',
        'Voyager seul dans les zones rurales frontalières',
      ],
      plan30Days: [
        'Entrer sans visa (90 jours pour la plupart)',
        'Explorer Quito, Cuenca et la côte',
        'Évaluer la situation sécuritaire actuelle',
        'Rejoindre la communauté d\'expatriés à Cuenca',
      ],
      plan12Months: [
        'Obtenir un visa de rentista ou d\'investisseur',
        'Ouvrir un compte bancaire local',
        'Établir un projet dans le tourisme ou l\'agriculture',
        'Perfectionner l\'espagnol',
      ],
      plan5Years: [
        'Obtenir la résidence permanente',
        'Consolider les investissements',
        'Explorer la citoyenneté (3 ans de résidence)',
        'Diversifier entre Équateur et pays voisins',
      ],
      planB: 'La Colombie pour un marché plus grand. Le Pérou pour plus de diversité économique. Le Costa Rica pour plus de sécurité.',
    },
    snapshot: {
      gdpPerCapita: 5600,
      population: 18000000,
      passportRank: 59,
      corruptionIndex: 36,
      freedomIndex: 62,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      investmentMinimum: 42000,
      citizenshipYears: 3,
      notes: 'Dollar américain comme monnaie officielle. Visa de rentista avec dépôt modeste. Citoyenneté en 3 ans seulement. Cuenca très populaire auprès des retraités.',
    },
    costOfLiving: {
      index: 32,
      rentIndex: 12,
      groceriesIndex: 28,
      monthlyBudgetSingle: 800,
      monthlyBudgetFamily: 1800,
    },
    qualityOfLife: {
      healthcareRank: 65,
      educationIndex: 0.67,
      safetyIndex: 38,
      environmentIndex: 55,
      workLifeBalance: 6,
      internetSpeed: 35,
    },
    lgbtqRights: {
      index: 50,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'caution',
      notes: 'Mariage homosexuel légal depuis 2019 (décision judiciaire). Protections légales mais acceptation sociale variable.',
    },
    positivePoints: {
      lifestyle: ['Dollar américain — stabilité monétaire', 'Coût de la vie très abordable', 'Quatre régions climatiques', 'Cuenca — ville coloniale charmante'],
      economy: ['Dollar américain', 'Agriculture d\'exportation (bananes, cacao, crevettes)', 'Tourisme Galápagos', 'Citoyenneté rapide (3 ans)'],
      culture: ['Patrimoine inca et colonial', 'Richesse des cultures indigènes', 'Marché d\'Otavalo', 'Gastronomie andine et côtière'],
      infrastructure: ['Aéroports modernes (Quito, Guayaquil)', 'Routes inter-cités améliorées', 'Réseau mobile correct'],
      opportunities: ['Tourisme Galápagos', 'Agriculture bio', 'Retraite abordable', 'Immobilier accessible'],
      nature: ['Îles Galápagos — unique au monde', 'Volcans andins', 'Forêt amazonienne', 'Côte Pacifique'],
    },
    naturalRisks: {
      seismicRisk: 'very_high',
      tsunamiRisk: 'high',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'high',
      extremeHeat: 'occasional',
      extremeCold: 'rare',
      climateNotes: 'Zone sismique majeure (séisme de 2016). Volcans très actifs (Cotopaxi, Tungurahua). El Niño cause inondations et sécheresses. Tsunami possible sur la côte.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 62,
      accessScore: 58,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'IESS système public pour les cotisants. Cliniques privées de qualité à Quito et Guayaquil. Cuenca a de bons hôpitaux. Coût très abordable.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'peru',
    name: 'Peru',
    nameLocal: 'Perú',
    iso2: 'PE',
    region: 'Amérique du Sud',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'Économie résiliente malgré le chaos politique. Misez sur le secteur privé, pas sur l\'État.',
    pyramid: {
      top: 'Élites économiques de Lima et oligarchie minière',
      institutions: 'Institutions faibles, présidents qui tombent régulièrement',
      gatekeepers: 'Avocats, politiciens régionaux, intermédiaires miniers',
      valueCreators: 'Entrepreneurs informels, secteur minier, agriculture d\'exportation',
      base: 'Population informelle massive (70% de l\'économie)',
      realAsset: 'Les ressources minières (cuivre, or, argent) et la résilience économique',
    },
    risks: {
      legal: 50,
      safety: 50,
      corruption: 60,
      volatility: 55,
      bureaucracy: 55,
    },
    whoWins: [
      'Les investisseurs dans le secteur minier',
      'Les entrepreneurs de la gastronomie et du tourisme',
      'Les entreprises d\'exportation agricole',
      'Les nomades numériques à Lima ou Cusco',
    ],
    whoLoses: [
      'Ceux qui dépendent de la stabilité politique',
      'Les investisseurs sans partenaire local',
      'Les populations rurales andines',
      'Les entreprises ne gérant pas l\'informalité',
    ],
    playbook: {
      do: [
        'Commencer par Lima (Miraflores, Barranco) pour les affaires',
        'Explorer la gastronomie comme secteur (boom international)',
        'Investir dans le tourisme (Machu Picchu, Cusco)',
        'Comprendre l\'économie informelle massive',
        'Apprendre l\'espagnol péruvien',
      ],
      dont: [
        'Miser sur la stabilité politique',
        'Ignorer le secteur informel (70% de l\'économie)',
        'Investir dans les zones de conflit social (mines)',
        'Négliger les risques sismiques',
        'Sous-estimer l\'altitude (Cusco à 3400m)',
      ],
      plan30Days: [
        'Entrer sans visa (183 jours pour la plupart)',
        'Explorer Lima, Cusco et Arequipa',
        'Rejoindre les communautés d\'expatriés',
        'Tester la gastronomie et le tourisme',
      ],
      plan12Months: [
        'Obtenir un visa de travail ou d\'investisseur',
        'Établir une entreprise locale (SAC)',
        'Construire un réseau professionnel',
        'Ouvrir un compte bancaire',
      ],
      plan5Years: [
        'Obtenir la résidence permanente',
        'Développer les affaires dans la région',
        'Explorer la citoyenneté (2 ans de résidence)',
        'Diversifier entre Lima et les régions',
      ],
      planB: 'La Colombie pour un écosystème similaire. Le Chili pour plus de stabilité. Le Mexique pour un marché plus grand.',
    },
    snapshot: {
      gdpPerCapita: 6600,
      population: 34000000,
      passportRank: 35,
      corruptionIndex: 36,
      freedomIndex: 64,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 2,
      notes: 'Séjour touristique de 183 jours. Visa nomade digital récent. Citoyenneté possible après seulement 2 ans de résidence — l\'un des plus rapides au monde.',
    },
    costOfLiving: {
      index: 32,
      rentIndex: 13,
      groceriesIndex: 28,
      monthlyBudgetSingle: 850,
      monthlyBudgetFamily: 2000,
    },
    qualityOfLife: {
      healthcareRank: 55,
      educationIndex: 0.70,
      safetyIndex: 42,
      environmentIndex: 45,
      workLifeBalance: 5,
      internetSpeed: 55,
    },
    lgbtqRights: {
      index: 30,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Pas de reconnaissance légale. Société conservatrice mais tolérance croissante dans les grandes villes. Lima plus ouverte.',
    },
    positivePoints: {
      lifestyle: ['Gastronomie mondialement reconnue (Lima — capitale culinaire)', 'Coût de la vie abordable', 'Climat varié selon les régions', 'Vie culturelle riche'],
      economy: ['Économie la plus résiliente d\'Amérique latine', 'Boom gastronomique international', 'Secteur minier puissant (cuivre, or)', 'Citoyenneté en 2 ans'],
      culture: ['Machu Picchu et civilisation inca', 'Gastronomie péruvienne — meilleure au monde', 'Culture musicale andine', 'Patrimoine colonial de Lima et Cusco'],
      infrastructure: ['Aéroport de Lima en expansion', 'Internet rapide dans les villes', 'Routes principales en bon état'],
      opportunities: ['Gastronomie et tourisme culinaire', 'Mines et ressources naturelles', 'Tourisme culturel', 'Agriculture d\'exportation (avocat, quinoa)'],
      nature: ['Machu Picchu', 'Amazonie péruvienne', 'Lac Titicaca', 'Andes spectaculaires et désert de Nazca'],
    },
    naturalRisks: {
      seismicRisk: 'very_high',
      tsunamiRisk: 'high',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'high',
      extremeHeat: 'occasional',
      extremeCold: 'occasional',
      climateNotes: 'Zone sismique majeure (ceinture de feu du Pacifique). El Niño cause inondations côtières et sécheresses andines. Froid extrême en altitude.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 58,
      accessScore: 50,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Bonnes cliniques privées à Lima (Ricardo Palma, Clínica Internacional). EsSalud pour les cotisants. Qualité variable hors Lima. Assurance privée recommandée.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'chile',
    name: 'Chile',
    nameLocal: 'Chile',
    iso2: 'CL',
    region: 'Amérique du Sud',
    pyramidType: 'COMPETENCE_TRUST' as PyramidType,
    ruleOfGold: 'Les diplômes comptent, mais le bon réseau ouvre toutes les portes. La méritocratie est réelle mais inégale.',
    pyramid: {
      top: 'Élite économique (6 familles contrôlent 90% de la richesse)',
      institutions: 'Institutions fortes mais servant les intérêts établis',
      gatekeepers: 'Réseaux universitaires, associations professionnelles',
      valueCreators: 'Professionnels, entrepreneurs, travailleurs qualifiés',
      base: 'Classe moyenne et travailleurs informels',
      realAsset: 'L\'apparence de méritocratie tandis que les réseaux dominent',
    },
    risks: {
      legal: 35,
      safety: 45,
      corruption: 35,
      volatility: 40,
      bureaucracy: 45,
    },
    whoWins: [
      'Les professionnels bien connectés',
      'Les diplômés des universités d\'élite',
      'Ceux avec le bon background familial',
      'Les investisseurs internationaux',
    ],
    whoLoses: [
      'Les autodidactes sans diplômes reconnus',
      'Ceux en dehors des réseaux traditionnels',
      'Les aspirants de la classe moyenne-basse',
      'Les populations rurales et indigènes',
    ],
    playbook: {
      do: [
        'Obtenir des diplômes d\'institutions reconnues',
        'Réseauter via les associations professionnelles',
        'Apprendre les nuances de l\'espagnol chilien',
        'Commencer par Santiago',
        'Comprendre la culture business locale',
      ],
      dont: [
        'Compter uniquement sur le mérite sans réseauter',
        'Ignorer les codes sociaux et la hiérarchie',
        'Sous-estimer le coût de la vie à Santiago',
        'Négliger la validation des diplômes étrangers',
        'Attendre une intégration rapide',
      ],
      plan30Days: [
        'Explorer Santiago et les régions',
        'Contacter les associations professionnelles',
        'Comprendre les exigences de visa',
        'Rechercher la reconnaissance des diplômes',
      ],
      plan12Months: [
        'Obtenir un visa de travail ou de résidence',
        'Construire un réseau professionnel',
        'Valider les diplômes étrangers si nécessaire',
        'Ouvrir des comptes bancaires',
      ],
      plan5Years: [
        'Envisager la résidence permanente',
        'Élargir le réseau professionnel',
        'Construire une réputation locale',
        'Explorer la citoyenneté (5 ans)',
      ],
      planB: 'L\'Uruguay ou l\'Argentine comme alternatives avec des dynamiques différentes. Le Pérou pour plus de flexibilité.',
    },
    snapshot: {
      gdpPerCapita: 15355,
      population: 19500000,
      passportRank: 14,
      corruptionIndex: 67,
      freedomIndex: 90,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'Programme Start-Up Chile mondialement reconnu. Nouveau visa nomade digital disponible. Institutions solides.',
    },
    costOfLiving: {
      index: 48,
      rentIndex: 25,
      groceriesIndex: 42,
      monthlyBudgetSingle: 1200,
      monthlyBudgetFamily: 2800,
    },
    qualityOfLife: {
      healthcareRank: 44,
      educationIndex: 0.81,
      safetyIndex: 58,
      environmentIndex: 52,
      workLifeBalance: 6,
      internetSpeed: 150,
    },
    lgbtqRights: {
      index: 62,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Mariage homosexuel légal depuis 2022. Progressiste pour l\'Amérique latine.',
    },
    positivePoints: {
      lifestyle: ['Paysages magnifiques et variés', 'Pays du vin', 'Activités de plein air', 'Villes sûres'],
      economy: ['Économie la plus stable de la région', 'Institutions solides', 'Industrie minière', 'Secteur tech en croissance'],
      culture: ['Influence européenne', 'Tradition littéraire (Neruda, Mistral)', 'Hospitalité chaleureuse', 'Culture gastronomique'],
      infrastructure: ['Routes excellentes', 'Aéroports modernes', 'Internet rapide', 'Services publics fiables'],
      opportunities: ['Programme Start-Up Chile', 'Secteur minier', 'Énergies renouvelables', 'Agriculture et viticulture'],
      nature: ['Désert d\'Atacama', 'Patagonie', 'Île de Pâques', 'Cordillère des Andes'],
    },
    naturalRisks: {
      seismicRisk: 'very_high',
      tsunamiRisk: 'high',
      floodRisk: 'moderate',
      droughtRisk: 'high',
      cycloneRisk: 'none',
      volcanoRisk: 'high',
      extremeHeat: 'rare',
      extremeCold: 'occasional',
      climateNotes: 'Risque sismique très élevé. Menace de tsunami sur la côte. Volcans actifs. Sécheresse chronique dans le nord et le centre.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 75,
      accessScore: 72,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'moderate',
      insuranceRequired: true,
      notes: 'Bon système de santé privé. FONASA système public existant. Isapres (assurances privées) pour une meilleure couverture. Assurance recommandée.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'argentina',
    name: 'Argentina',
    nameLocal: 'Argentina',
    iso2: 'AR',
    region: 'Amérique du Sud',
    pyramidType: 'STABILITY_REDIS' as PyramidType,
    ruleOfGold: 'Le système redistribue en permanence — mais l\'inflation dévore tout. Protégez votre capital en dollars.',
    pyramid: {
      top: 'Élites politiques péronistes et oligarchie agraire',
      institutions: 'État hypertrophié redistribuant mais créant de l\'inflation',
      gatekeepers: 'Syndicats puissants, bureaucratie étatique, cambistes',
      valueCreators: 'Entrepreneurs résilients, agriculteurs, développeurs tech',
      base: 'Classe moyenne appauvrie et travailleurs informels',
      realAsset: 'La capacité à survivre et s\'adapter au chaos monétaire',
    },
    risks: {
      legal: 45,
      safety: 50,
      corruption: 55,
      volatility: 85,
      bureaucracy: 65,
    },
    whoWins: [
      'Ceux qui gagnent en dollars et dépensent en pesos',
      'Les exportateurs agricoles (soja, boeuf, vin)',
      'Les développeurs tech travaillant pour l\'étranger',
      'Les investisseurs immobiliers achetant en période de crise',
    ],
    whoLoses: [
      'Les épargnants en pesos (inflation dévoratrice)',
      'Les salariés dépendants du marché local',
      'Les entreprises ne gérant pas le risque de change',
      'Les retraités dont la pension fond',
    ],
    playbook: {
      do: [
        'Gagner en dollars, vivre en pesos — règle d\'or',
        'Explorer Buenos Aires pour la qualité de vie',
        'Profiter du talent tech argentin',
        'Apprendre l\'espagnol rioplatense',
        'Investir dans l\'immobilier en période de crise',
      ],
      dont: [
        'Épargner en pesos argentins',
        'Ignorer le marché du dollar parallèle (blue)',
        'Sous-estimer la bureaucratie et les taxes',
        'Investir sans comprendre les contrôles de change',
        'Négliger l\'inflation dans les projections',
      ],
      plan30Days: [
        'Entrer sans visa (90 jours renouvelables)',
        'Explorer Buenos Aires (Palermo, Recoleta, San Telmo)',
        'Comprendre les taux de change (officiel vs blue)',
        'Rejoindre la communauté tech et expatriée',
      ],
      plan12Months: [
        'Obtenir un visa de résidence (DNI temporaire)',
        'Ouvrir un compte bancaire (complexe mais faisable)',
        'Développer des revenus en devises étrangères',
        'Construire un réseau professionnel local',
      ],
      plan5Years: [
        'Obtenir le DNI permanent',
        'Acquérir de l\'immobilier',
        'Explorer la citoyenneté (2 ans de résidence)',
        'Diversifier les investissements (Uruguay, dollar)',
      ],
      planB: 'L\'Uruguay comme refuge stable à côté. Le Chili pour la stabilité institutionnelle. Le Brésil pour un marché plus vaste.',
    },
    snapshot: {
      gdpPerCapita: 10600,
      population: 46000000,
      passportRank: 17,
      corruptionIndex: 38,
      freedomIndex: 85,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: true,
      investmentVisa: true,
      citizenshipYears: 2,
      notes: 'Citoyenneté en 2 ans seulement — parmi les plus rapides au monde. Contrôles de change stricts. Dollar blue omniprésent. Passeport argentin bien classé.',
    },
    costOfLiving: {
      index: 30,
      rentIndex: 10,
      groceriesIndex: 25,
      monthlyBudgetSingle: 700,
      monthlyBudgetFamily: 1600,
    },
    qualityOfLife: {
      healthcareRank: 42,
      educationIndex: 0.82,
      safetyIndex: 45,
      environmentIndex: 55,
      workLifeBalance: 7,
      internetSpeed: 55,
    },
    lgbtqRights: {
      index: 75,
      sameSecMarriage: true,
      civilUnion: true,
      employmentProtection: true,
      safetyRating: 'safe',
      notes: 'Premier pays d\'Amérique latine à légaliser le mariage homosexuel (2010). Loi d\'identité de genre pionnière. Buenos Aires très LGBTQ+-friendly.',
    },
    positivePoints: {
      lifestyle: ['Buenos Aires — le Paris de l\'Amérique du Sud', 'Culture du café et des restaurants', 'Vie nocturne légendaire', 'Qualité de vie excellente en dollars'],
      economy: ['Talent tech de niveau mondial', 'Agriculture puissante (soja, boeuf, vin)', 'Citoyenneté rapide (2 ans)', 'Immobilier très abordable en dollars'],
      culture: ['Tango — patrimoine mondial', 'Littérature (Borges, Cortázar)', 'Football — religion nationale', 'Théâtre et arts vivants prolifiques'],
      infrastructure: ['Métro de Buenos Aires', 'Bon réseau aérien intérieur', 'Universités de qualité (UBA gratuite)', 'Internet fiable dans les villes'],
      opportunities: ['Tech et développement logiciel', 'Gastronomie et vin', 'Agriculture d\'exportation', 'Immobilier en période de crise'],
      nature: ['Patagonie et glaciers', 'Chutes d\'Iguazú', 'Andes et stations de ski', 'Pampas et estancias'],
    },
    naturalRisks: {
      seismicRisk: 'moderate',
      tsunamiRisk: 'low',
      floodRisk: 'moderate',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'moderate',
      extremeHeat: 'occasional',
      extremeCold: 'occasional',
      climateNotes: 'Inondations à Buenos Aires et dans les pampas. Sécheresse affectant l\'agriculture. Risque sismique dans l\'ouest (Andes). Climat très varié du nord au sud.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 72,
      accessScore: 70,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'low',
      insuranceRequired: false,
      notes: 'Système public gratuit et de bonne qualité (hôpitaux universitaires). Obras sociales (mutuelles syndicales). Prépaga (assurance privée) abordable. Buenos Aires — excellente médecine.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  // ============================================================
  // AFRIQUE
  // ============================================================
  {
    id: 'ghana',
    name: 'Ghana',
    nameLocal: 'Ghana',
    iso2: 'GH',
    region: 'Afrique de l\'Ouest',
    pyramidType: 'HYBRID_TRANSITION' as PyramidType,
    ruleOfGold: 'La démocratie fonctionne ici, mais les réseaux comptent autant que les règles. Construisez les deux.',
    pyramid: {
      top: 'Élites politiques alternant au pouvoir et chefs traditionnels',
      institutions: 'Démocratie fonctionnelle avec alternance pacifique',
      gatekeepers: 'Partis politiques, chefferies traditionnelles, bureaucratie',
      valueCreators: 'Entrepreneurs, diaspora de retour, secteur tech émergent',
      base: 'Agriculteurs, commerçants informels, jeunesse nombreuse',
      realAsset: 'La stabilité démocratique et les ressources (or, cacao, pétrole)',
    },
    risks: {
      legal: 45,
      safety: 35,
      corruption: 55,
      volatility: 50,
      bureaucracy: 55,
    },
    whoWins: [
      'Les entrepreneurs tech (Accra — hub émergent)',
      'La diaspora qui revient avec des capitaux et des compétences',
      'Les investisseurs dans l\'or et le cacao',
      'Ceux qui comprennent les dynamiques ethno-politiques',
    ],
    whoLoses: [
      'Les investisseurs ignorant les dynamiques locales',
      'Ceux qui sous-estiment la bureaucratie',
      'Les entreprises ne gérant pas la dépréciation du cedi',
      'Les outsiders sans réseau local',
    ],
    playbook: {
      do: [
        'Commencer par Accra pour les affaires et la tech',
        'Construire des relations avec la diaspora ghanéenne',
        'Explorer le programme Year of Return / Beyond the Return',
        'Investir dans la tech et le numérique',
        'Apprendre les bases du Twi — geste très apprécié',
      ],
      dont: [
        'Ignorer le rôle des chefferies traditionnelles',
        'Sous-estimer les fluctuations du cedi',
        'Investir sans comprendre la culture business locale',
        'Négliger les relations personnelles',
        'Afficher de l\'arrogance culturelle',
      ],
      plan30Days: [
        'Obtenir un visa ou utiliser le visa à l\'arrivée',
        'Explorer Accra, Kumasi et Cape Coast',
        'Rejoindre les hubs tech (Accra Digital Centre)',
        'Comprendre le coût de la vie',
      ],
      plan12Months: [
        'Obtenir un permis de résidence ou de travail',
        'Établir des partenariats commerciaux',
        'Ouvrir un compte bancaire',
        'Développer un projet pilote',
      ],
      plan5Years: [
        'Consolider la présence commerciale',
        'Explorer la résidence permanente',
        'Développer des activités régionales (CEDEAO)',
        'Construire une réputation dans l\'écosystème local',
      ],
      planB: 'Le Sénégal ou la Côte d\'Ivoire comme alternatives francophones. Le Rwanda pour un environnement plus structuré. Le Kenya pour un marché tech plus mature.',
    },
    snapshot: {
      gdpPerCapita: 2360,
      population: 33000000,
      passportRank: 75,
      corruptionIndex: 43,
      freedomIndex: 80,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'Visa à l\'arrivée pour de nombreuses nationalités africaines. Programme Beyond the Return pour la diaspora. Ghana Card numérique en développement.',
    },
    costOfLiving: {
      index: 30,
      rentIndex: 12,
      groceriesIndex: 28,
      monthlyBudgetSingle: 600,
      monthlyBudgetFamily: 1500,
    },
    qualityOfLife: {
      healthcareRank: 96,
      educationIndex: 0.60,
      safetyIndex: 62,
      environmentIndex: 45,
      workLifeBalance: 5,
      internetSpeed: 25,
    },
    lgbtqRights: {
      index: 15,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexualité criminalisée. Fort stigmate social. Projet de loi anti-LGBTQ+ en discussion. Prudence extrême nécessaire.',
    },
    positivePoints: {
      lifestyle: ['Peuple très accueillant (Akwaaba)', 'Vie sociale riche', 'Gastronomie savoureuse (jollof rice, fufu)', 'Climat tropical agréable'],
      economy: ['Démocratie la plus stable d\'Afrique de l\'Ouest', 'Ressources naturelles (or, cacao, pétrole)', 'Hub tech émergent', 'Croissance économique soutenue'],
      culture: ['Riche patrimoine Ashanti', 'Festivals colorés (Homowo, Panafest)', 'Musique highlife et afrobeats', 'Programme Year of Return'],
      infrastructure: ['Accra en modernisation rapide', 'Aéroport international Kotoka', 'Couverture mobile étendue', 'Routes principales en amélioration'],
      opportunities: ['Tech et fintech (mobile money)', 'Cacao et agriculture', 'Pétrole et gaz', 'Tourisme patrimonial'],
      nature: ['Châteaux d\'esclaves de Cape Coast', 'Parc national de Kakum', 'Lac Volta — le plus grand lac artificiel', 'Cascades de Wli'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'none',
      floodRisk: 'high',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'none',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Inondations fréquentes à Accra pendant la saison des pluies. Harmattan (vent sec du Sahara) de décembre à février. Chaleur constante.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 45,
      accessScore: 40,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'NHIS (assurance nationale) pour les résidents. Hôpitaux privés de qualité à Accra. Infrastructure variable hors grandes villes. Assurance privée recommandée.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'tanzania',
    name: 'Tanzania',
    nameLocal: 'Tanzania',
    iso2: 'TZ',
    region: 'Afrique de l\'Est',
    pyramidType: 'GROWTH_RISK' as PyramidType,
    ruleOfGold: 'Croissance rapide mais contrôlée par l\'État. Alignez-vous avec les priorités nationales pour réussir.',
    pyramid: {
      top: 'Parti au pouvoir (CCM) et présidence forte',
      institutions: 'État centralisé poussant l\'industrialisation',
      gatekeepers: 'Fonctionnaires du parti, leaders régionaux, investisseurs connectés',
      valueCreators: 'Entrepreneurs, agriculteurs, secteur touristique',
      base: 'Population rurale et paysans',
      realAsset: 'Les ressources naturelles, le tourisme et la position géostratégique',
    },
    risks: {
      legal: 55,
      safety: 40,
      corruption: 55,
      volatility: 40,
      bureaucracy: 60,
    },
    whoWins: [
      'Les investisseurs dans le tourisme (Serengeti, Zanzibar)',
      'Les entreprises alignées avec les plans nationaux',
      'Les agriculteurs d\'exportation',
      'Les entrepreneurs du mobile money',
    ],
    whoLoses: [
      'Les critiques du gouvernement',
      'Les médias indépendants',
      'Les investisseurs sans connexions gouvernementales',
      'Les entreprises non alignées avec les priorités nationales',
    ],
    playbook: {
      do: [
        'Explorer le tourisme comme secteur prioritaire',
        'Commencer par Dar es Salaam ou Zanzibar',
        'S\'aligner avec les plans de développement nationaux',
        'Apprendre le swahili — absolument essentiel',
        'Construire des relations gouvernementales',
      ],
      dont: [
        'Critiquer le gouvernement ou le parti CCM',
        'Ignorer les régulations changeantes',
        'Investir sans comprendre les dynamiques locales',
        'Négliger l\'importance du swahili',
        'Sous-estimer la bureaucratie',
      ],
      plan30Days: [
        'Obtenir un visa à l\'arrivée ou e-visa',
        'Explorer Dar es Salaam et Zanzibar',
        'Visiter les parcs nationaux (Serengeti, Ngorongoro)',
        'Rencontrer la communauté d\'affaires',
      ],
      plan12Months: [
        'Obtenir un permis de résidence et de travail',
        'Établir des partenariats locaux',
        'Apprendre le swahili conversationnel',
        'Développer un projet pilote dans le tourisme ou l\'agriculture',
      ],
      plan5Years: [
        'Consolider la présence commerciale',
        'Explorer les opportunités dans l\'énergie et les mines',
        'Développer des activités régionales (EAC)',
        'Obtenir la résidence permanente',
      ],
      planB: 'Le Kenya pour un écosystème business plus développé. Le Rwanda pour un environnement plus structuré. L\'Ouganda comme alternative régionale.',
    },
    snapshot: {
      gdpPerCapita: 1200,
      population: 65000000,
      passportRank: 73,
      corruptionIndex: 39,
      freedomIndex: 34,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: false,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'E-visa disponible. Permis de travail nécessite un sponsor. Investissement minimum pour le visa investisseur. Zanzibar a des règles partiellement distinctes.',
    },
    costOfLiving: {
      index: 26,
      rentIndex: 8,
      groceriesIndex: 24,
      monthlyBudgetSingle: 500,
      monthlyBudgetFamily: 1200,
    },
    qualityOfLife: {
      healthcareRank: 152,
      educationIndex: 0.48,
      safetyIndex: 58,
      environmentIndex: 50,
      workLifeBalance: 5,
      internetSpeed: 15,
    },
    lgbtqRights: {
      index: 10,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'dangerous',
      notes: 'Homosexualité criminalisée avec peines sévères. Persécution active dans certaines régions, surtout Zanzibar. Extrêmement dangereux.',
    },
    positivePoints: {
      lifestyle: ['Peuple chaleureux et accueillant', 'Zanzibar — île paradisiaque', 'Rythme de vie détendu', 'Coût de la vie très bas'],
      economy: ['Croissance économique rapide (7%+)', 'Ressources naturelles importantes', 'Tourisme de classe mondiale', 'Position stratégique en Afrique de l\'Est'],
      culture: ['Berceau du swahili', 'Culture Zanzibarite unique', 'Musique taarab', 'Peuple Maasai et traditions vivantes'],
      infrastructure: ['Nouvelle ligne de chemin de fer SGR', 'Ports en expansion', 'Couverture mobile en croissance'],
      opportunities: ['Safari et tourisme de luxe', 'Agriculture d\'exportation', 'Mines (tanzanite, or)', 'Mobile money et fintech'],
      nature: ['Kilimandjaro — toit de l\'Afrique', 'Serengeti et Grande Migration', 'Cratère du Ngorongoro', 'Plages de Zanzibar'],
    },
    naturalRisks: {
      seismicRisk: 'moderate',
      tsunamiRisk: 'low',
      floodRisk: 'moderate',
      droughtRisk: 'high',
      cycloneRisk: 'moderate',
      volcanoRisk: 'moderate',
      extremeHeat: 'frequent',
      extremeCold: 'rare',
      climateNotes: 'Sécheresses fréquentes affectant l\'agriculture. Inondations pendant les pluies. Ol Doinyo Lengai — volcan actif. Chaleur côtière constante.',
    },
    healthcare: {
      systemType: 'limited',
      qualityScore: 30,
      accessScore: 25,
      emergencyResponse: 'poor',
      specialistAccess: 'poor',
      chronicCareQuality: 'poor',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Infrastructure médicale limitée. Aga Khan Hospital à Dar es Salaam de bonne qualité. Évacuation vers Nairobi recommandée pour les cas graves. Assurance rapatriement indispensable.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'rwanda',
    name: 'Rwanda',
    nameLocal: 'Rwanda',
    iso2: 'RW',
    region: 'Afrique de l\'Est',
    pyramidType: 'GROWTH_RISK' as PyramidType,
    ruleOfGold: 'Le leadership fort impose l\'ordre et la croissance. Respectez les règles, et le système vous portera.',
    pyramid: {
      top: 'Présidence forte (Kagame) et parti RPF',
      institutions: 'État efficace, anti-corruption, orienté développement',
      gatekeepers: 'Parti RPF, agences gouvernementales, investisseurs approuvés',
      valueCreators: 'Entrepreneurs, secteur tech, coopératives agricoles',
      base: 'Population rurale participante au système',
      realAsset: 'La discipline institutionnelle et la vision de développement',
    },
    risks: {
      legal: 40,
      safety: 25,
      corruption: 30,
      volatility: 35,
      bureaucracy: 35,
    },
    whoWins: [
      'Les investisseurs alignés avec la vision nationale',
      'Les entrepreneurs tech (Kigali — hub africain)',
      'Les entreprises respectant les règles strictes',
      'Les investisseurs dans le tourisme des gorilles',
    ],
    whoLoses: [
      'Les dissidents politiques et critiques',
      'Les médias indépendants',
      'Les entrepreneurs ne respectant pas les régulations',
      'Ceux qui cherchent la liberté d\'expression totale',
    ],
    playbook: {
      do: [
        'Respecter scrupuleusement les lois et régulations',
        'S\'installer à Kigali — ville la plus propre d\'Afrique',
        'Explorer le secteur tech et l\'innovation',
        'S\'aligner avec Vision 2050 du Rwanda',
        'Apprécier l\'efficacité administrative rare en Afrique',
      ],
      dont: [
        'Critiquer le gouvernement ou évoquer les divisions ethniques',
        'Sous-estimer la rigueur réglementaire',
        'Apporter des sacs plastiques (interdits)',
        'Ignorer les umuganda (travaux communautaires mensuels)',
        'Comparer avec les pays voisins de manière négative',
      ],
      plan30Days: [
        'Obtenir un visa à l\'arrivée (30 jours)',
        'Explorer Kigali et le pays',
        'Visiter le Mémorial du Génocide',
        'Rencontrer l\'écosystème tech (Kigali Innovation City)',
      ],
      plan12Months: [
        'Obtenir un permis de travail ou visa investisseur',
        'Enregistrer une entreprise (processus rapide — 24h)',
        'Rejoindre les réseaux business',
        'Apprendre les bases du kinyarwanda',
      ],
      plan5Years: [
        'Consolider l\'entreprise et les investissements',
        'Développer des activités régionales (EAC)',
        'Explorer la résidence permanente',
        'Contribuer à l\'écosystème tech rwandais',
      ],
      planB: 'Le Kenya pour plus de liberté et un marché plus grand. Le Ghana pour une démocratie plus ouverte. Maurice pour un environnement business insulaire.',
    },
    snapshot: {
      gdpPerCapita: 820,
      population: 14000000,
      passportRank: 82,
      corruptionIndex: 53,
      freedomIndex: 21,
    },
    visa: {
      workVisa: 'moderate',
      startupVisa: true,
      digitalNomadVisa: false,
      investmentVisa: true,
      citizenshipYears: 5,
      notes: 'Visa à l\'arrivée pour tous les Africains et de nombreux pays. Création d\'entreprise en 24h. Environnement business parmi les meilleurs d\'Afrique (Doing Business).',
    },
    costOfLiving: {
      index: 28,
      rentIndex: 10,
      groceriesIndex: 26,
      monthlyBudgetSingle: 550,
      monthlyBudgetFamily: 1300,
    },
    qualityOfLife: {
      healthcareRank: 130,
      educationIndex: 0.50,
      safetyIndex: 82,
      environmentIndex: 60,
      workLifeBalance: 5,
      internetSpeed: 20,
    },
    lgbtqRights: {
      index: 20,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Pas de criminalisation explicite (rare en Afrique). Mais pas de protections non plus. Discrétion nécessaire. Sujet non discuté publiquement.',
    },
    positivePoints: {
      lifestyle: ['Kigali — ville la plus propre d\'Afrique', 'Sécurité exceptionnelle', 'Climat agréable toute l\'année (altitude)', 'Qualité de vie en amélioration rapide'],
      economy: ['Croissance économique rapide (8%+)', 'Anti-corruption exemplaire en Afrique', 'Environnement business excellent', 'Hub tech émergent (Kigali Innovation City)'],
      culture: ['Résilience inspirante post-génocide', 'Culture umuganda (entraide communautaire)', 'Art et musique en renaissance', 'Café rwandais de renommée mondiale'],
      infrastructure: ['Routes excellentes pour la région', 'Internet en expansion', 'Nouvel aéroport de Bugesera en construction', 'Kigali Convention Centre'],
      opportunities: ['Tech et innovation', 'Tourisme gorilles (haute valeur)', 'Agriculture (café, thé)', 'Hub de conférences africain'],
      nature: ['Gorilles des montagnes (Volcanoes NP)', 'Lac Kivu', 'Forêt de Nyungwe', 'Mille collines verdoyantes'],
    },
    naturalRisks: {
      seismicRisk: 'moderate',
      tsunamiRisk: 'none',
      floodRisk: 'moderate',
      droughtRisk: 'moderate',
      cycloneRisk: 'none',
      volcanoRisk: 'moderate',
      extremeHeat: 'rare',
      extremeCold: 'rare',
      climateNotes: 'Climat tempéré grâce à l\'altitude. Glissements de terrain pendant la saison des pluies. Proximité du volcan Nyiragongo (RDC). Risque de gaz du lac Kivu.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 45,
      accessScore: 60,
      emergencyResponse: 'adequate',
      specialistAccess: 'limited',
      chronicCareQuality: 'adequate',
      costForExpats: 'low',
      insuranceRequired: true,
      notes: 'Mutuelle de santé communautaire couvrant 90% de la population. King Faisal Hospital et hôpitaux privés à Kigali. Drones pour livraison de sang (Zipline). En amélioration rapide.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
  {
    id: 'mauritius',
    name: 'Mauritius',
    nameLocal: 'Maurice / Moris',
    iso2: 'MU',
    region: 'Océan Indien',
    pyramidType: 'COMPETENCE_TRUST' as PyramidType,
    ruleOfGold: 'Petit pays, grandes ambitions. Les institutions fonctionnent, le mérite est récompensé, la diversité est un atout.',
    pyramid: {
      top: 'Élites économiques (sucre, textile, finance) et technocrates',
      institutions: 'Démocratie stable, institutions fortes, état de droit',
      gatekeepers: 'Diplômes, réseaux professionnels, communautés ethniques',
      valueCreators: 'Entrepreneurs, professionnels de la finance, secteur tech',
      base: 'Classe moyenne éduquée et diversifiée',
      realAsset: 'La stabilité institutionnelle, la position stratégique et le capital humain multilingue',
    },
    risks: {
      legal: 25,
      safety: 20,
      corruption: 35,
      volatility: 25,
      bureaucracy: 40,
    },
    whoWins: [
      'Les investisseurs internationaux (hub financier)',
      'Les entrepreneurs tech et fintech',
      'Les retraités cherchant la qualité de vie',
      'Les professionnels multilingues',
    ],
    whoLoses: [
      'Ceux qui sous-estiment le marché restreint (1,3M d\'habitants)',
      'Les investisseurs ignorant les communautés ethniques',
      'Les entreprises sans vision internationale',
      'Ceux qui cherchent un grand marché domestique',
    ],
    playbook: {
      do: [
        'Utiliser Maurice comme hub pour l\'Afrique et l\'Asie',
        'Explorer le Premium Visa pour les travailleurs à distance',
        'Profiter de la fiscalité avantageuse (15% flat tax)',
        'Apprécier le multilinguisme (français, anglais, créole)',
        'Investir dans l\'immobilier (IRS/RES/PDS)',
      ],
      dont: [
        'Ignorer les dynamiques communautaires (indo-mauriciens, créoles, sino-mauriciens)',
        'Sous-estimer la taille limitée du marché',
        'Négliger les cyclones et risques climatiques',
        'Ignorer l\'importance des relations personnelles',
        'Comparer avec les grandes métropoles',
      ],
      plan30Days: [
        'Entrer sans visa (60-90 jours pour la plupart)',
        'Explorer Port-Louis, Grand Baie et le sud',
        'Rencontrer la communauté business',
        'Évaluer les options d\'investissement immobilier',
      ],
      plan12Months: [
        'Obtenir le Premium Visa ou l\'Occupation Permit',
        'Ouvrir un compte bancaire (processus simple)',
        'Enregistrer une entreprise si pertinent',
        'S\'intégrer dans les réseaux professionnels locaux',
      ],
      plan5Years: [
        'Obtenir la résidence permanente (3 ans avec Occupation Permit)',
        'Acquérir un bien immobilier (PDS/Smart City)',
        'Développer des activités régionales (Afrique, Asie)',
        'Explorer la citoyenneté',
      ],
      planB: 'Les Seychelles pour un paradis similaire. Singapour pour un hub asiatique plus grand. Dubaï pour un hub fiscal alternatif.',
    },
    snapshot: {
      gdpPerCapita: 10200,
      population: 1300000,
      passportRank: 32,
      corruptionIndex: 50,
      freedomIndex: 85,
    },
    visa: {
      workVisa: 'easy',
      startupVisa: true,
      digitalNomadVisa: true,
      investmentVisa: true,
      investmentMinimum: 50000,
      citizenshipYears: 5,
      notes: 'Premium Visa pour nomades digitaux (1 an renouvelable). Occupation Permit facile. Fiscalité attractive (15% flat). Hub financier pour l\'Afrique. Immobilier accessible aux étrangers via PDS.',
    },
    costOfLiving: {
      index: 40,
      rentIndex: 15,
      groceriesIndex: 35,
      monthlyBudgetSingle: 900,
      monthlyBudgetFamily: 2200,
    },
    qualityOfLife: {
      healthcareRank: 64,
      educationIndex: 0.72,
      safetyIndex: 75,
      environmentIndex: 62,
      workLifeBalance: 7,
      internetSpeed: 40,
    },
    lgbtqRights: {
      index: 30,
      sameSecMarriage: false,
      civilUnion: false,
      employmentProtection: false,
      safetyRating: 'caution',
      notes: 'Homosexualité techniquement criminalisée mais non appliquée. Société conservatrice mais tolérante en pratique. Décriminalisation en discussion.',
    },
    positivePoints: {
      lifestyle: ['Île paradisiaque toute l\'année', 'Excellente qualité de vie', 'Société multiculturelle harmonieuse', 'Gastronomie fusion (indienne, française, chinoise, créole)'],
      economy: ['Hub financier pour l\'Afrique', 'Fiscalité attractive (15% flat)', 'Stabilité économique et politique', 'Classé #1 en Afrique pour les affaires'],
      culture: ['Diversité culturelle unique (indienne, française, chinoise, africaine)', 'Festivals de toutes les religions', 'Sega — musique et danse créole', 'Multilinguisme naturel'],
      infrastructure: ['Aéroport international moderne', 'Réseau routier en bon état', 'Internet fibre disponible', 'Smart Cities en développement'],
      opportunities: ['Finance et fintech', 'Tech et outsourcing', 'Immobilier premium', 'Hub Afrique-Asie'],
      nature: ['Lagons turquoise et récifs coralliens', 'Terre des Sept Couleurs de Chamarel', 'Black River Gorges', 'Île aux Cerfs'],
    },
    naturalRisks: {
      seismicRisk: 'low',
      tsunamiRisk: 'moderate',
      floodRisk: 'moderate',
      droughtRisk: 'low',
      cycloneRisk: 'high',
      volcanoRisk: 'none',
      extremeHeat: 'occasional',
      extremeCold: 'rare',
      climateNotes: 'Cyclones tropicaux de novembre à avril (saison cyclonique). Inondations occasionnelles. Montée des eaux — menace à long terme pour l\'île. Climat tropical agréable.',
    },
    healthcare: {
      systemType: 'mixed',
      qualityScore: 65,
      accessScore: 70,
      emergencyResponse: 'good',
      specialistAccess: 'good',
      chronicCareQuality: 'good',
      costForExpats: 'moderate',
      insuranceRequired: true,
      notes: 'Système de santé public gratuit et fonctionnel. Cliniques privées de bonne qualité (Wellkin, C-Care). Évacuation vers l\'Afrique du Sud ou La Réunion pour les cas complexes.',
    },
    lastUpdated: '2024-12-20',
    sources: ['Banque Mondiale', 'Transparency International', 'Freedom House', 'Henley Passport Index', 'Numbeo'],
  },
];

/**
 * Enregistre les pays d'expansion dans un tableau existant de pays.
 * Déduplique automatiquement par ID pour éviter les conflits.
 *
 * @param existingCountries - Le tableau de pays existant
 * @returns Un nouveau tableau fusionné et dédupliqué
 */
export function registerExpansionCountries(existingCountries: Country[]): Country[] {
  const existingIds = new Set(existingCountries.map((c) => c.id));
  const newCountries = expansionCountries.filter((c) => !existingIds.has(c.id));
  return [...existingCountries, ...newCountries];
}
