export type ModuleAuditCategory = 'featureEnrichments' | 'moduleElements' | 'leastDeveloped' | 'nonWorking';

export type ModuleAudit = {
  id: string;
  title: string;
  subtitle: string;
  items: Record<ModuleAuditCategory, string[]>;
};

export const moduleAudits: ModuleAudit[] = [
  {
    id: 'country-analysis',
    title: 'Country Analysis',
    subtitle: 'Profil pays, pyramides et intelligence système.',
    items: {
      featureEnrichments: [
        'Ajouter un score d’alignement dynamique par profil utilisateur.',
        'Déployer des comparatifs multi-critères avec pondérations personnalisées.',
        'Intégrer des alertes de changement de gouvernance par pays.',
        'Proposer des scénarios “si/alors” (choc politique, crise, réforme).',
        'Ajouter un export PDF synthèse (1 page) par pays.',
      ],
      moduleElements: [
        'Cartographie des risques sectoriels par région interne.',
        'Historique des tendances sur 5–10 ans.',
        'Sources et dates de mise à jour visibles.',
        'Indicateurs de qualité de vie contextualisés par profil.',
        'Recommandations d’actions rapides par niveau de risque.',
      ],
      leastDeveloped: [
        'Couverture des micro-régions (villes secondaires).',
        'Données d’accès au logement (disponibilité/prix).',
        'Cartes d’influence locale (acteurs clés).',
        'Signalements terrain (observations utilisateurs).',
        'Bibliothèque de cas réels indexés par pays.',
      ],
      nonWorking: [
        'Pipeline d’actualisation automatique des indicateurs.',
        'Connexion aux alertes géopolitiques temps réel.',
        'Synchronisation avec les dossiers utilisateurs (liaison pays/dossiers).',
        'Exports PDF multi-langues automatisés.',
        'Version offline pour consultation en mobilité.',
      ],
    },
  },
  {
    id: 'exit-keys',
    title: 'Exit Keys',
    subtitle: 'Stratégies personnalisées selon le profil et les objectifs.',
    items: {
      featureEnrichments: [
        'Ajouter un simulateur de coûts par stratégie (CAPEX/OPEX).',
        'Introduire un score de faisabilité en temps réel.',
        'Créer des itinéraires multi-étapes (plan A/B/C).',
        'Automatiser des checklists par stratégie sélectionnée.',
        'Ajouter un mode “risque minimal” vs “vitesse maximale”.',
      ],
      moduleElements: [
        'Détails de prérequis juridiques par pays cible.',
        'Calendriers prédictifs par type de démarche.',
        'Bibliothèque d’exemples de parcours réussis.',
        'Critères d’éligibilité visibles et pondérés.',
        'Raccourcis vers ressources et contacts utiles.',
      ],
      leastDeveloped: [
        'Indicateurs de complexité administrative par pays.',
        'Scénarios fiscaux comparés (résidence, société).',
        'Mode collectif (famille/équipe) avec dépendances.',
        'Suivi post-installation (90 jours).',
        'Compatibilité des stratégies avec profils non standards.',
      ],
      nonWorking: [
        'Connexion automatique aux dossiers (création/suivi).',
        'Alertes d’échéances par stratégie.',
        'Exports en PDF des parcours personnalisés.',
        'Synchronisation des données profil avec comparateurs.',
        'Historique des itérations de stratégie.',
      ],
    },
  },
  {
    id: 'dashboard',
    title: 'Dashboard & Dossiers',
    subtitle: 'Suivi des progrès, dossiers et timelines.',
    items: {
      featureEnrichments: [
        'Ajouter un tableau de bord “risque” avec alertes prioritaires.',
        'Créer des modèles de dossiers pré-remplis par scénario.',
        'Ajouter un calendrier consolidé multi-modules.',
        'Intégrer des objectifs trimestriels et OKR personnels.',
        'Proposer une synthèse hebdo envoyée par email.',
      ],
      moduleElements: [
        'Widgets configurables par utilisateur.',
        'Timeline interactive par dossier.',
        'Archivage et duplication de dossiers.',
        'Historique des décisions et notes.',
        'Export des jalons au format calendrier.',
      ],
      leastDeveloped: [
        'Automatisation des rappels multi-canaux.',
        'Suivi des dépenses liées au projet.',
        'Tableau des risques consolidé par dossier.',
        'Vue “plan B” avec bascule rapide.',
        'Mode collaboration avec commentaires.',
      ],
      nonWorking: [
        'Synchronisation bidirectionnelle avec calendrier externe.',
        'Notifications push persistantes.',
        'Exports PDF des dossiers complets.',
        'Mise à jour automatique des statuts depuis d’autres modules.',
        'Historique complet des modifications (audit log).',
      ],
    },
  },
  {
    id: 'comparative-analysis',
    title: 'Comparative Analysis',
    subtitle: 'Comparaisons multi-pays et multi-stratégies.',
    items: {
      featureEnrichments: [
        'Ajouter des pondérations par objectif utilisateur.',
        'Intégrer des comparaisons coût de vie détaillées.',
        'Permettre l’export des comparatifs (PDF/CSV).',
        'Ajouter des visualisations radar enrichies.',
        'Créer des “shortlists” partageables.',
      ],
      moduleElements: [
        'Filtres avancés par profil et contraintes.',
        'Historique des comparaisons sauvegardées.',
        'Notes collaboratives par comparaison.',
        'Segments de population (famille, solo, entrepreneur).',
        'Comparaison d’options de résidence légales.',
      ],
      leastDeveloped: [
        'Comparaison “effet réseau” (diaspora, soutien local).',
        'Comparaison du risque juridique sectoriel.',
        'Scénarios de volatilité (inflation, stabilité).',
        'Comparaison du système de santé par profil.',
        'Simulateur de trajectoire sur 12–24 mois.',
      ],
      nonWorking: [
        'Synchronisation avec les dossiers utilisateurs.',
        'Export automatisé multi-langue.',
        'Comparaison dynamique en temps réel par API externe.',
        'Partage public sécurisé par lien.',
        'Validation automatique des données d’entrée.',
      ],
    },
  },
  {
    id: 'terrain-realities',
    title: 'Terrain Realities',
    subtitle: 'Risques, friction, acteurs et gouvernance terrain.',
    items: {
      featureEnrichments: [
        'Ajouter un module de veille et signaux faibles.',
        'Construire un score de friction par secteur.',
        'Intégrer des checklists de conformité locale.',
        'Ajouter une cartographie des acteurs de pouvoir.',
        'Créer des plans de mitigation exportables.',
      ],
      moduleElements: [
        'Fiches d’acteurs (rôle, fiabilité, influence).',
        'Registre des risques par phase de projet.',
        'Journal d’observations terrain datées.',
        'Guides d’entrée marché par secteur.',
        'Analyse des dépendances critiques.',
      ],
      leastDeveloped: [
        'Analyse des circuits informels et frictions non officielles.',
        'Benchmark des partenaires locaux fiables.',
        'Cartographie des délais administratifs réels.',
        'Revue des contreparties et concessions usuelles.',
        'Détection d’incohérences règlementaires.',
      ],
      nonWorking: [
        'Synchronisation avec TraceOS pour la traçabilité.',
        'Exports PDF des plans de mitigation.',
        'Alertes sur changements réglementaires.',
        'Historique des preuves et sources externes.',
        'Mode hors ligne pour usage terrain.',
      ],
    },
  },
  {
    id: 'pyramid-quiz',
    title: 'Pyramid Quiz & Game',
    subtitle: 'Apprentissage gamifié des systèmes pays.',
    items: {
      featureEnrichments: [
        'Ajouter des scénarios adaptatifs par niveau.',
        'Intégrer un système de saisons/événements spéciaux.',
        'Ajouter des classements anonymisés.',
        'Créer des feedbacks détaillés par décision.',
        'Déployer des défis coopératifs en équipe.',
      ],
      moduleElements: [
        'Bibliothèque de scénarios par région.',
        'Système de progression et badges.',
        'Tutoriels interactifs au démarrage.',
        'Récompenses contextuelles utiles (guides, checklists).',
        'Mode rapide “micro-sessions”.',
      ],
      leastDeveloped: [
        'Mode simulation long terme (10–20 tours).',
        'Diversité de profils jouables.',
        'Arbres de conséquences visibles.',
        'Journal de décisions exportable.',
        'Personnalisation des objectifs d’apprentissage.',
      ],
      nonWorking: [
        'Synchronisation des scores avec le profil utilisateur.',
        'Sauvegarde cloud multi-appareils.',
        'Partage sécurisé des résultats.',
        'Export des parcours de jeu.',
        'Notifications de reprise de session.',
      ],
    },
  },
  {
    id: 'life-trajectory',
    title: 'Life Trajectory',
    subtitle: 'Projection et trajectoires multi-systèmes.',
    items: {
      featureEnrichments: [
        'Ajouter des trajectoires multi-objectifs.',
        'Intégrer des jalons personnalisables.',
        'Créer une vue “plan B” parallèle.',
        'Ajouter un simulateur de risque financier.',
        'Permettre l’export des trajectoires.',
      ],
      moduleElements: [
        'Graphiques interactifs par phase.',
        'Hypothèses modifiables avec impact visuel.',
        'Comparaisons avant/après décision.',
        'Notes et commentaires par étape.',
        'Synchronisation avec le dossier principal.',
      ],
      leastDeveloped: [
        'Scénarios d’imprévus majeurs.',
        'Alignement santé/finances (coût de couverture).',
        'Prise en compte du réseau local.',
        'Modèle de temps de stabilisation.',
        'Indicatif de stress décisionnel.',
      ],
      nonWorking: [
        'Exports PDF multi-langues.',
        'Synchronisation automatique des données profil.',
        'Notifications de dérive des hypothèses.',
        'Partage sécurisé de trajectoire.',
        'Historique complet des versions.',
      ],
    },
  },
  {
    id: 'traceos',
    title: 'TraceOS',
    subtitle: 'Traçabilité décisionnelle pour organisations.',
    items: {
      featureEnrichments: [
        'Ajouter un mode audit externe exportable.',
        'Créer des rapports de conformité automatiques.',
        'Intégrer des workflows multi-étapes configurables.',
        'Ajouter un moteur de recherche avancé.',
        'Créer des tableaux de bord par unité.',
      ],
      moduleElements: [
        'Journal des décisions avec preuves.',
        'Gestion des rôles et permissions.',
        'Templates de décision par type.',
        'Alertes et rappels de validation.',
        'Intégrations webhook multi-sources.',
      ],
      leastDeveloped: [
        'Score de qualité décisionnelle.',
        'Analyse des biais par rôle.',
        'Archivage légal à long terme.',
        'Comparaison inter-équipes.',
        'Mode “post-mortem” collaboratif.',
      ],
      nonWorking: [
        'Synchronisation avec les modules Terrain/Latent.',
        'Exports multi-format (CSV, PDF, JSON).',
        'Signature électronique intégrée.',
        'Notifications push multi-canaux.',
        'Indexation sémantique des décisions.',
      ],
    },
  },
  {
    id: 'latent',
    title: 'Latent',
    subtitle: 'Zones de tension et signaux émergents.',
    items: {
      featureEnrichments: [
        'Ajouter un scoring d’intensité des tensions.',
        'Créer un mode “journal de signaux” chronologique.',
        'Intégrer des recommandations d’actions prudentes.',
        'Permettre la fusion automatique de zones proches.',
        'Ajouter des exports vers TraceOS.',
      ],
      moduleElements: [
        'Cartes de zones avec tags et priorités.',
        'Historique des évolutions de chaque zone.',
        'Notes et preuves attachées.',
        'Filtrage par catégorie et statut.',
        'Partage contrôlé entre collaborateurs.',
      ],
      leastDeveloped: [
        'Vue “cartographie” des zones par pays.',
        'Détection de signaux faibles automatisés.',
        'Analyse de corrélation entre zones.',
        'Alertes sur seuils de bascule.',
        'Bibliothèque d’exemples anonymisés.',
      ],
      nonWorking: [
        'Synchronisation temps réel multi-appareils.',
        'Exports PDF multi-langues.',
        'Connexion automatique avec dossiers.',
        'Notifications push sur changements.',
        'API d’intégration externe.',
      ],
    },
  },
  {
    id: 'irreversa',
    title: 'Irreversa',
    subtitle: 'Documentation des seuils irréversibles.',
    items: {
      featureEnrichments: [
        'Ajouter un mode “validation externe” signé.',
        'Créer des modèles de seuils par scénario.',
        'Proposer des rappels de relecture périodiques.',
        'Intégrer un score de criticité.',
        'Exporter un certificat PDF horodaté.',
      ],
      moduleElements: [
        'Fiches seuils avec contexte détaillé.',
        'Gestion des témoins et validations.',
        'Historique de version pour chaque seuil.',
        'Journal des décisions associées.',
        'Liens vers stratégies Exit Keys.',
      ],
      leastDeveloped: [
        'Règles d’irréversibilité comparées.',
        'Bibliothèque de seuils anonymisés.',
        'Rappels de check-in sur conséquences.',
        'Visualisation des impacts à 6–12 mois.',
        'Lien direct avec les jalons du dossier.',
      ],
      nonWorking: [
        'Signature électronique qualifiée.',
        'Exports multi-format certifiés.',
        'Synchronisation avec TraceOS.',
        'Notifications automatiques aux témoins.',
        'Partage sécurisé par lien.',
      ],
    },
  },
  {
    id: 'ovi',
    title: 'OVI',
    subtitle: 'Optimisation et validation d’intelligence.',
    items: {
      featureEnrichments: [
        'Ajouter un espace de collecte de preuves.',
        'Créer un score de robustesse des hypothèses.',
        'Ajouter des templates par type de décision.',
        'Intégrer un fil de discussion avec l’équipe.',
        'Exporter une synthèse exécutive.',
      ],
      moduleElements: [
        'Hypothèses centralisées et traçables.',
        'Contradictions et angles morts identifiés.',
        'Priorisation des actions de validation.',
        'Suivi des sources utilisées.',
        'Checklist de validation finale.',
      ],
      leastDeveloped: [
        'Bibliothèque d’exemples d’OVI réussies.',
        'Moteur de suggestions automatiques.',
        'Analyse de biais cognitifs.',
        'Mode review post-décision.',
        'Alignement avec la stratégie d’entreprise.',
      ],
      nonWorking: [
        'Connexion aux données Terrain/Latent.',
        'Exports multi-format.',
        'Notifications de suivi des validations.',
        'Synchronisation avec dossiers utilisateurs.',
        'Historique des versions détaillé.',
      ],
    },
  },
];
