project_id = "abysiagseykztutnbjtu"

[functions.destination-insights]
verify_jwt = false

[functions.generate-country-music]
verify_jwt = false

[functions.generate-translations]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-country-profile]
verify_jwt = false

[functions.batch-generate-countries]
verify_jwt = false
